<?php
declare(strict_types=1);
namespace VeciAhorra\Modules\Products\Admin;
use VeciAhorra\Core\Config;
use VeciAhorra\Modules\Products\Import\ProductBulkImportService;
use VeciAhorra\Modules\Products\Import\ProductCsvParser;
use VeciAhorra\Modules\Products\Import\ProductImageZipParser;

final class ProductBulkImportPage
{
    public const PAGE_SLUG='veciahorra-products-import';private const CAPABILITY='manage_options';private const PREFIX='va_product_import_';private ?string $hook=null;
    public function register():void{add_action('admin_menu',[$this,'menu']);add_action('admin_enqueue_scripts',[$this,'assets']);foreach(['preview','confirm','template','errors']as$a)add_action('admin_post_veciahorra_product_csv_'.$a,[$this,$a]);}
    public function menu():void{$h=add_submenu_page('veciahorra','Carga masiva del catálogo maestro','Carga catálogo CSV',self::CAPABILITY,self::PAGE_SLUG,[$this,'render']);$this->hook=is_string($h)?$h:null;}
    public function assets(string $h):void{if($this->hook!==null&&$h===$this->hook)wp_enqueue_style('veciahorra-product-import',VA_PLUGIN_URL.'assets/admin/css/product-import.css',[],Config::PLUGIN_VERSION);}
    public function render():void{$this->authorize();$this->cleanupExpired();$token=$this->getToken();$preview=$token!==''?get_transient($this->key($token)):false;$preview=is_array($preview)&&(int)($preview['user_id']??0)===get_current_user_id()?$preview:null;$message=isset($_GET['va_message'])?sanitize_text_field(wp_unslash((string)$_GET['va_message'])):'';$result=is_array($preview)&&!empty($preview['completed'])?($preview['result']??null):null;require dirname(__DIR__).'/Views/import.php';}
    public function preview():void{$this->authorize();check_admin_referer('veciahorra_product_csv_preview');$token=bin2hex(random_bytes(24));try{$file=$_FILES['product_csv']??null;if(!is_array($file)||(int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new \InvalidArgumentException('Seleccione un CSV válido.');if((int)$file['size']<1||(int)$file['size']>ProductCsvParser::MAX_BYTES||strtolower(pathinfo((string)$file['name'],PATHINFO_EXTENSION))!=='csv'||!is_uploaded_file((string)$file['tmp_name']))throw new \InvalidArgumentException('El CSV debe ser una carga .csv de máximo 1 MB.');$contents=file_get_contents((string)$file['tmp_name']);if(!is_string($contents))throw new \RuntimeException('No fue posible leer el CSV.');$parsed=(new ProductCsvParser())->parse($contents);$images=$this->stage($token,$this->zip($_FILES['product_images']??null));$data=(new ProductBulkImportService())->preview($parsed['rows'],$parsed['errors'],$images);if(!empty($data['errors'])){$this->cleanup($token);foreach($data['rows']as&$row)unset($row['staged_image']);unset($row);}$data['user_id']=get_current_user_id();$data['created_at']=time();if(!set_transient($this->key($token),$data,15*MINUTE_IN_SECONDS))throw new \RuntimeException('No fue posible conservar la vista previa.');wp_safe_redirect($this->url(['va_token'=>$token]));exit;}catch(\Throwable $e){$this->cleanup($token);wp_safe_redirect($this->url(['va_message'=>$this->publicError($e)]));exit;}}
    public function confirm():void{$this->authorize();check_admin_referer('veciahorra_product_csv_confirm');$token=$this->postToken();$p=$token!==''?get_transient($this->key($token)):false;if(!is_array($p)||(int)($p['user_id']??0)!==get_current_user_id()||!empty($p['completed'])){$this->redirect('La vista previa venció o ya fue consumida. Vuelva a validar el CSV.');}if(!empty($p['errors'])){$this->redirect('El archivo contiene errores. Corrige todas las filas rechazadas y vuelve a cargarlo. No se aplicó ningún cambio.',$token);}try{$result=(new ProductBulkImportService())->import($p);$p['completed']=true;$p['result']=$result;foreach($p['rows']as&$row)unset($row['staged_image']);unset($row);$this->cleanup($token);set_transient($this->key($token),$p,15*MINUTE_IN_SECONDS);wp_safe_redirect($this->url(['va_token'=>$token]));exit;}catch(\Throwable $e){$this->cleanup($token);delete_transient($this->key($token));$this->redirect($this->publicError($e));}}
    public function template():void{$this->authorize();check_admin_referer('veciahorra_product_csv_template');$this->headers('plantilla-catalogo-maestro-veciahorra.csv');$out=fopen('php://output','wb');echo"\xEF\xBB\xBF";fputcsv($out,ProductCsvParser::HEADERS);fputcsv($out,['7801234567890','Producto ejemplo','Abarrotes','','','','Descripción del producto','draft','']);fclose($out);exit;}
    public function errors():void{$this->authorize();$t=$this->getToken();check_admin_referer('veciahorra_product_csv_errors_'.$t);$p=$t!==''?get_transient($this->key($t)):false;if(!is_array($p)||(int)($p['user_id']??0)!==get_current_user_id())wp_die('El informe venció.','',['response'=>410]);$this->headers('errores-catalogo-maestro.csv');$o=fopen('php://output','wb');echo"\xEF\xBB\xBF";fputcsv($o,['fila','sku','error']);foreach($p['errors']as$e)fputcsv($o,[(int)$e['line'],$this->safe((string)$e['sku']),$this->safe((string)$e['message'])]);fclose($o);exit;}
    private function zip(mixed $file):array{if(!is_array($file)||(int)($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return[];if((int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_uploaded_file((string)$file['tmp_name'])||strtolower(pathinfo((string)$file['name'],PATHINFO_EXTENSION))!=='zip')throw new \InvalidArgumentException('Seleccione una carga ZIP válida.');return(new ProductImageZipParser())->parse((string)$file['tmp_name'],(int)$file['size']);}
    private function stage(string $token,array $images):array{if($images===[])return[];$dir=$this->directory($token);if(!wp_mkdir_p($dir))throw new \RuntimeException('No fue posible crear el staging de imágenes.');file_put_contents($dir.DIRECTORY_SEPARATOR.'index.php',"<?php http_response_code(404);\n");file_put_contents($dir.DIRECTORY_SEPARATOR.'.htaccess',"Deny from all\n");$out=[];foreach($images as$name=>$bytes){$path=$dir.DIRECTORY_SEPARATOR.hash('sha256',$name).'.bin';if(file_put_contents($path,$bytes)!==strlen($bytes))throw new \RuntimeException('No fue posible guardar una imagen en staging.');$out[$name]=['path'=>$path,'sha256'=>hash('sha256',$bytes)];}return$out;}
    private function directory(string $token):string{$u=wp_upload_dir();return trailingslashit($u['basedir']).'veciahorra-product-import-staging'.DIRECTORY_SEPARATOR.get_current_user_id().DIRECTORY_SEPARATOR.hash('sha256',$token);}
    private function cleanup(string $token):void{$dir=$this->directory($token);if(!is_dir($dir))return;foreach(scandir($dir)?:[]as$f)if($f!=='.'&&$f!=='..'&&is_file($dir.DIRECTORY_SEPARATOR.$f))@unlink($dir.DIRECTORY_SEPARATOR.$f);@rmdir($dir);@rmdir(dirname($dir));@rmdir(dirname(dirname($dir)));}
    private function cleanupExpired():void{$u=wp_upload_dir();$root=trailingslashit($u['basedir']).'veciahorra-product-import-staging'.DIRECTORY_SEPARATOR.get_current_user_id();if(!is_dir($root))return;foreach(scandir($root)?:[]as$d){$path=$root.DIRECTORY_SEPARATOR.$d;if($d!=='.'&&$d!=='..'&&is_dir($path)&&filemtime($path)<time()-HOUR_IN_SECONDS){foreach(scandir($path)?:[]as$f)if($f!=='.'&&$f!=='..'&&is_file($path.DIRECTORY_SEPARATOR.$f))@unlink($path.DIRECTORY_SEPARATOR.$f);@rmdir($path);}}}
    private function authorize():void{if(!current_user_can(self::CAPABILITY))wp_die('No autorizado.','',['response'=>403]);}
    private function key(string $t):string{return self::PREFIX.get_current_user_id().'_'.hash('sha256',$t);}private function getToken():string{$v=isset($_GET['va_token'])?sanitize_text_field(wp_unslash((string)$_GET['va_token'])):'';return preg_match('/^[a-f0-9]{48}$/D',$v)?$v:'';}private function postToken():string{$v=isset($_POST['va_token'])?sanitize_text_field(wp_unslash((string)$_POST['va_token'])):'';return preg_match('/^[a-f0-9]{48}$/D',$v)?$v:'';}
    private function url(array $a=[]):string{return add_query_arg(array_merge(['page'=>self::PAGE_SLUG],$a),admin_url('admin.php'));}private function redirect(string $m,string $t=''):never{wp_safe_redirect($this->url(array_filter(['va_token'=>$t,'va_message'=>$m])));exit;}private function publicError(\Throwable $e):string{return$e instanceof \InvalidArgumentException||$e instanceof \RuntimeException?$e->getMessage():'No fue posible procesar la importación.';}private function headers(string $n):void{nocache_headers();header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$n.'"');header('X-Content-Type-Options: nosniff');}private function safe(string $v):string{return preg_match('/^[=+\-@\t\r]/',$v)?"'".$v:$v;}
}
