<?php
declare(strict_types=1);
require_once dirname(__DIR__,5).'/wp-load.php';
use VeciAhorra\Modules\Minimarket\Onboarding\StoreOnboardingApplicationRepository;
use VeciAhorra\Modules\Minimarket\Onboarding\Verification\StoreOnboardingEmailVerification;
use VeciAhorra\Modules\Minimarket\Onboarding\Verification\StoreOnboardingEmailVerificationRepository;
function r1dbc(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$database=(string)getenv('VA_R1DA_DISPOSABLE_DATABASE');r1dbc($database==='minimarket_r1da_disposable','Base desechable invalida.');$caseId=(int)(getenv('VA_R1DB_CONCURRENCY_CASE')?:1);r1dbc($caseId>=1&&$caseId<=10,'Caso de concurrencia invalido.');global $wpdb;$production=$wpdb;$userId=0;$applicationId=0;
try{
    $wpdb=new wpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$wpdb->set_prefix('wp_');$apps=new StoreOnboardingApplicationRepository();$verifications=new StoreOnboardingEmailVerificationRepository();$t0='2026-10-01 00:00:00';r1dbc((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->users} WHERE user_email=%s",'r1db.concurrent@example.test'))===0,'Residuo previo de concurrencia.');
    $app=$apps->createProvisioning(['public_id'=>'onb_r1db_concurrency','account_email'=>'r1db.concurrent@example.test','owner_rut_normalized'=>'12345678-5','idempotency_key_hash'=>hash('sha256','r1db-concurrency'),'terms_version'=>'R1C-LEGAL-2026-07-30-V1','terms_accepted_at'=>$t0,'created_at'=>$t0,'updated_at'=>$t0]);$applicationId=(int)$app->data['id'];
    $v=$verifications->create($applicationId,StoreOnboardingEmailVerification::PURPOSE,null,str_repeat('e',32),str_repeat("q\0",16),'2026-10-02 00:00:00',$t0);$v=$verifications->markDeliveryAttempt($applicationId,1,$v->updatedAt,'2026-10-01 00:01:00');$verifications->markSent($applicationId,1,$v->updatedAt,'2026-10-01 00:02:00');
    if($caseId===10){$incompatible=wp_insert_user(['user_login'=>'r1db_incompatible_race','user_email'=>'r1db.concurrent@example.test','user_pass'=>'incompatible race password 2026','role'=>'subscriber']);r1dbc(is_int($incompatible),'No creo incompatible concurrente.');}
    $php=PHP_BINARY;$worker=__DIR__.'/minimarket-onboarding-r1d-b-concurrency-worker.php';$commands=[];$processes=[];
    $lostMode=$caseId===9||(string)getenv('VA_R1DB_LOST_CONNECTION')==='1';for($i=0;$i<2;$i++){$mode=$lostMode&&$i===0?'lost':($caseId===4?'fixed':'normal');$command='"'.$php.'" "'.$worker.'" '.$applicationId.' '.$database.' '.$mode;$pipes=[];$process=proc_open($command,[1=>['pipe','w'],2=>['pipe','w']],$pipes,__DIR__);r1dbc(is_resource($process),'Worker no iniciado.');$processes[]=[$process,$pipes];}
    $reports=[];foreach($processes as [$process,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($process);$report=json_decode(trim($out),true);r1dbc(is_array($report)&&$report['result']!=='hostile_throwable'&&$err==='','Worker invalido: exit='.$exit.' stdout='.trim($out).' stderr='.trim($err));$report['process_exit']=$exit;$reports[]=$report;}
    $final=$apps->findByApplicationId($applicationId);if($caseId===10){r1dbc($final!==null&&$final->data['status']==='provisioning'&&$final->data['user_id']===null,'Incompatible fue apropiado.');$userId=(int)$incompatible;}else{r1dbc($final!==null&&$final->data['status']==='account_created','Application no converge.');$userId=(int)$final->data['user_id'];}
    $users=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->users} WHERE user_email=%s",'r1db.concurrent@example.test'));$consumed=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM wp_va_store_onboarding_email_verifications WHERE application_id=%d AND consumed_at IS NOT NULL AND attached_user_id=%d',$applicationId,$userId));
    r1dbc($users===1&&$consumed===($caseId===10?0:1),'Concurrencia creo autoridad multiple.');r1dbc((int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM wp_va_stores WHERE owner_user_id=%d',$userId))===0,'Concurrencia creo Store.');
    echo ($lostMode?'R1DB_LOST_CONNECTION_RECONCILIATION=PASS ':'R1DB_CONCURRENCY_CASE=PASS ').'case='.$caseId.' participants='.json_encode($reports,JSON_UNESCAPED_SLASHES).PHP_EOL;
}finally{require_once ABSPATH.'wp-admin/includes/user.php';$cleanupIds=$wpdb->get_col($wpdb->prepare("SELECT ID FROM {$wpdb->users} WHERE user_email=%s",'r1db.concurrent@example.test'));foreach($cleanupIds as $cleanupId)wp_delete_user((int)$cleanupId);$wpdb->delete('wp_va_store_onboarding_email_verifications',['application_id'=>$applicationId]);$wpdb->delete('wp_va_store_onboarding_applications',['id'=>$applicationId]);$wpdb=$production;}
