<?php

declare(strict_types=1);

require_once dirname(__DIR__,5).'/wp-load.php';
require_once ABSPATH.'wp-admin/includes/user.php';

use VeciAhorra\Modules\Minimarket\Identity\PendingMinimarketRole;
use VeciAhorra\Modules\Minimarket\Onboarding\Owner\OwnerOnboardingRequest;
use VeciAhorra\Modules\Minimarket\Onboarding\Owner\OwnerOnboardingService;
use VeciAhorra\Modules\Stores\Domain\StoreLifecycleContract;
use VeciAhorra\Modules\Stores\Exceptions\StoreLifecycleException;
use VeciAhorra\Modules\ZonalAdmin\Authorization\StoreTerritoryAuthorizer;
use VeciAhorra\Modules\ZonalAdmin\Identity\ZonalAdminRole;
use VeciAhorra\Modules\ZonalAdmin\Repositories\StoreDecisionHistoryRepository;
use VeciAhorra\Modules\ZonalAdmin\Repositories\ZonalStoreRepository;
use VeciAhorra\Modules\ZonalAdmin\Services\StoreDecisionCoordinator;

function decisionAssert(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
global$wpdb;$p=$wpdb->prefix.'va_';$suffix=bin2hex(random_bytes(5));$now=current_time('mysql');$ownerId=$zonalId=$otherZonalId=0;$storeIds=[];$zoneIds=[];
$tables=['stores'=>$p.'stores','applications'=>$p.'store_onboarding_applications','zones'=>$p.'service_zones','store_zones'=>$p.'store_service_zones','assignments'=>$p.'zonal_admin_service_zones','history'=>$p.'store_decision_history','inventory'=>$p.'inventory'];
try{
 foreach(['owner','zonal','other']as$kind){$id=wp_insert_user(['user_login'=>'decision_'.$kind.'_'.$suffix,'user_email'=>'decision_'.$kind.'_'.$suffix.'@example.test','user_pass'=>wp_generate_password(30,true,true),'role'=>$kind==='owner'?PendingMinimarketRole::ROLE:ZonalAdminRole::ROLE]);decisionAssert(is_int($id),"user {$kind}");if($kind==='owner')$ownerId=$id;elseif($kind==='zonal')$zonalId=$id;else$otherZonalId=$id;}
 foreach(['Decision Zone A '.$suffix,'Decision Zone B '.$suffix]as$name){decisionAssert($wpdb->insert($tables['zones'],['commune'=>'Santiago','name'=>$name,'status'=>'active','created_at'=>$now,'updated_at'=>$now])===1,'zone insert');$zoneIds[]=(int)$wpdb->insert_id;}
 foreach(['approve','reject']as$case){decisionAssert($wpdb->insert($tables['stores'],['owner_user_id'=>$case==='approve'?$ownerId:null,'business_name'=>'Decision '.$case.' '.$suffix,'legal_name'=>'Decision Legal','owner_name'=>'Owner Fixture','rut'=>'D-'.$suffix.'-'.substr($case,0,1),'email'=>'owner-'.$suffix.'@example.test','phone'=>'+56900000000','mobile'=>null,'address'=>'Calle Uno 1','commune'=>'Santiago','city'=>'Santiago','region'=>'RM','status'=>'pending','onboarding_status'=>'complete','approved_at'=>null,'created_at'=>$now,'updated_at'=>$now])===1,'store insert');$storeIds[$case]=(int)$wpdb->insert_id;if($case==='approve'){decisionAssert($wpdb->insert($tables['applications'],['public_id'=>'decision-'.$suffix,'user_id'=>$ownerId,'account_email'=>'owner-'.$suffix.'@example.test','owner_rut_normalized'=>'111111111','status'=>'store_materialized','idempotency_key_hash'=>hash('sha256',$suffix),'terms_version'=>'2026-09-01','terms_accepted_at'=>$now,'store_id'=>$storeIds[$case],'failure_code'=>null,'attempt_count'=>1,'last_attempt_at'=>$now,'created_at'=>$now,'updated_at'=>$now,'abandoned_at'=>null])===1,'application insert');}}
 decisionAssert($wpdb->insert($tables['store_zones'],['store_id'=>$storeIds['approve'],'zone_id'=>$zoneIds[0],'assigned_by'=>$zonalId,'assigned_at'=>$now])===1,'store zone approve');decisionAssert($wpdb->insert($tables['store_zones'],['store_id'=>$storeIds['reject'],'zone_id'=>$zoneIds[0],'assigned_by'=>$zonalId,'assigned_at'=>$now])===1,'store zone reject');decisionAssert($wpdb->insert($tables['assignments'],['user_id'=>$zonalId,'service_zone_id'=>$zoneIds[0],'created_at'=>$now,'created_by'=>$zonalId])===1,'zonal assignment');decisionAssert($wpdb->insert($tables['assignments'],['user_id'=>$otherZonalId,'service_zone_id'=>$zoneIds[1],'created_at'=>$now,'created_by'=>$zonalId])===1,'other assignment');
 $zonalStores=new ZonalStoreRepository();$correctList=array_map('intval',array_column($zonalStores->paginate($zonalId,false,1,20,'Decision approve',null),'id'));$wrongList=array_map('intval',array_column($zonalStores->paginate($otherZonalId,false,1,20,'Decision approve',null),'id'));decisionAssert(in_array($storeIds['approve'],$correctList,true)&&!in_array($storeIds['approve'],$wrongList,true)&&is_array($zonalStores->findVisible($zonalId,false,$storeIds['approve']))&&$zonalStores->findVisible($otherZonalId,false,$storeIds['approve'])===null,'territorial list/detail');$decisions=new StoreDecisionCoordinator();$observed=$decisions->decideAuthorized($storeIds['approve'],$zonalId,'observe','Corrige la direccion comercial.',$now);decisionAssert($observed->status==='observed','observe state');$owner=new OwnerOnboardingService();$snapshot=$owner->snapshot($storeIds['approve'],$ownerId);decisionAssert($snapshot['lifecycle_state']==='observed'&&$snapshot['latest_decision']['reason']==='Corrige la direccion comercial.'&&$snapshot['application']['terms_version']==='2026-09-01','owner observation/legal');
 try{$owner->snapshot($storeIds['approve'],$otherZonalId);throw new RuntimeException('ownership bypass');}catch(StoreLifecycleException$e){decisionAssert($e->reason()==='store_not_found','ownership reason');}
 wp_set_current_user(0);$anonymous=new WP_REST_Request('GET','/veciahorra/v1/zonal/stores');decisionAssert(rest_do_request($anonymous)->get_status()===401,'anonymous guard');wp_set_current_user($ownerId);$ownerNonce=wp_create_nonce('wp_rest');$ownerRead=new WP_REST_Request('GET','/veciahorra/v1/minimarket/onboarding');$ownerRead->set_header('X-WP-Nonce',$ownerNonce);decisionAssert(rest_do_request($ownerRead)->get_status()===200,'owner read route');$csrf=new WP_REST_Request('PATCH','/veciahorra/v1/minimarket/onboarding');$csrf->set_header('X-WP-Nonce','invalid-nonce');$csrf->set_header('Content-Type','application/json');$csrf->set_body(wp_json_encode(['address'=>'No debe aplicar','expected_updated_at'=>(string)$observed->updated_at]));decisionAssert(rest_do_request($csrf)->get_status()===403,'csrf guard');$selfDecision=new WP_REST_Request('POST','/veciahorra/v1/zonal/stores/'.$storeIds['approve'].'/transitions');$selfDecision->set_header('X-WP-Nonce',$ownerNonce);$selfDecision->set_header('Content-Type','application/json');$selfDecision->set_body(wp_json_encode(['action'=>'approve','reason'=>null,'expected_updated_at'=>(string)$observed->updated_at]));decisionAssert(rest_do_request($selfDecision)->get_status()===403,'owner decision guard');wp_set_current_user($otherZonalId);$otherNonce=wp_create_nonce('wp_rest');$crossRead=new WP_REST_Request('GET','/veciahorra/v1/zonal/stores/'.$storeIds['approve']);$crossRead->set_header('X-WP-Nonce',$otherNonce);decisionAssert(rest_do_request($crossRead)->get_status()===404,'idor guard');wp_set_current_user($ownerId);
 $validated=(new OwnerOnboardingRequest(['address'=>'Calle Corregida 2','commune'=>'Santiago','expected_updated_at'=>(string)$observed->updated_at]))->correction();$draft=$owner->correct($storeIds['approve'],$ownerId,$validated['fields'],$validated['expected_updated_at']);decisionAssert($draft['lifecycle_state']==='draft'&&$draft['store']['address']==='Calle Corregida 2','correction state');try{$owner->resubmit($storeIds['approve'],$ownerId,(string)$observed->updated_at);throw new RuntimeException('stale accepted');}catch(StoreLifecycleException$e){decisionAssert($e->reason()==='concurrent_modification','stale reason');}
 $review=$owner->resubmit($storeIds['approve'],$ownerId,$draft['store']['updated_at']);decisionAssert($review['lifecycle_state']==='in_review','resubmit state');decisionAssert((new StoreTerritoryAuthorizer())->canReadStore($zonalId,$storeIds['approve'])&&!(new StoreTerritoryAuthorizer())->canReadStore($otherZonalId,$storeIds['approve']),'territory isolation');
 $approved=$decisions->decideAuthorized($storeIds['approve'],$zonalId,'approve',null,$review['store']['updated_at']);$approvedState=(new StoreLifecycleContract())->classify((string)$approved->status,(string)$approved->onboarding_status,$approved->approved_at);decisionAssert($approvedState==='approved_inactive'&&$approved->status==='inactive','approved inactive');try{$decisions->decideAuthorized($storeIds['approve'],$zonalId,'approve',null,$review['store']['updated_at']);throw new RuntimeException('double submit accepted');}catch(StoreLifecycleException$e){decisionAssert(in_array($e->reason(),['concurrent_modification','action_not_allowed'],true),'double submit reason');}decisionAssert((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$tables['inventory']} WHERE minimarket_id=%d AND status='active'",$storeIds['approve']))===0,'approval published offer');
 $rejected=$decisions->decideAuthorized($storeIds['reject'],$zonalId,'reject','Antecedentes no verificables.',$now);decisionAssert($rejected->status==='rejected'&&$rejected->approved_at===null,'reject state');$history=(new StoreDecisionHistoryRepository())->forStore($storeIds['reject']);decisionAssert(($history[0]['reason']??null)==='Antecedentes no verificables.','reject trace');
 try{$decisions->decideAuthorized($storeIds['reject'],$otherZonalId,'approve',null,(string)$rejected->updated_at);throw new RuntimeException('cross territory accepted');}catch(StoreLifecycleException|DomainException){}
 try{(new OwnerOnboardingRequest(['address'=>'x','expected_updated_at'=>'bad']))->correction();throw new RuntimeException('bad cas accepted');}catch(InvalidArgumentException){}try{(new OwnerOnboardingRequest(['expected_updated_at'=>$now,'unexpected'=>'x']))->resubmit();throw new RuntimeException('extra field accepted');}catch(InvalidArgumentException){}
 echo"MINIMARKET_DECISION_FLOW_E2E=PASS observe=PASS correction=PASS resubmit=PASS approve=approved_inactive reject=PASS territory=PASS ownership=PASS cas=PASS csrf=ROUTE_GUARD output_escaping=TEXT_CONTENT no_auto_activation=PASS public_offers=0\n";
}finally{
 if($storeIds!==[]){$ids=implode(',',array_map('intval',array_values($storeIds)));$wpdb->query("DELETE FROM {$tables['history']} WHERE store_id IN ({$ids})");$wpdb->query("DELETE FROM {$tables['applications']} WHERE store_id IN ({$ids})");$wpdb->query("DELETE FROM {$tables['store_zones']} WHERE store_id IN ({$ids})");$wpdb->query("DELETE FROM {$tables['stores']} WHERE id IN ({$ids})");}if($zoneIds!==[]){$ids=implode(',',array_map('intval',$zoneIds));$wpdb->query("DELETE FROM {$tables['assignments']} WHERE service_zone_id IN ({$ids})");$wpdb->query("DELETE FROM {$tables['zones']} WHERE id IN ({$ids})");}foreach([$ownerId,$zonalId,$otherZonalId]as$id)if($id>0)wp_delete_user($id);
}
