<?php
declare(strict_types=1);
require_once dirname(__DIR__,5).'/wp-load.php';
use VeciAhorra\Modules\Minimarket\Identity\PendingMinimarketRole;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\ActivatePendingMinimarketAccount;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\ActivatePendingMinimarketAccountCommand;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\ActivatePendingMinimarketAccountResult;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\MariaDbActivationLockManager;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\OpaqueUsernameGenerator;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\PendingAccountException;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\RandomOpaqueUsernameGenerator;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\SensitivePassword;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\WordPressPendingUserGateway;
use VeciAhorra\Modules\Minimarket\Onboarding\StoreOnboardingApplicationRepository;
use VeciAhorra\Modules\Minimarket\Onboarding\Verification\StoreOnboardingEmailVerification;
use VeciAhorra\Modules\Minimarket\Onboarding\Verification\StoreOnboardingEmailVerificationRepository;
function r1db(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
final class R1dbLockWpdb extends wpdb{
    public array $release=[];public int $releaseCalls=0;public bool $throwRelease=false;public bool $sqlRelease=false;
    public function __construct(){}
    public function prepare($query,...$args){return vsprintf(str_replace(['%s','%f'],["'%s'",'%F'],$query),$args);}
    public function get_var($query=null,$x=0,$y=0){if(str_contains((string)$query,'CONNECTION_ID'))return '101';if(str_contains((string)$query,'GET_LOCK'))return '1';$this->releaseCalls++;if($this->throwRelease&&$this->releaseCalls===1)throw new RuntimeException('hostile');if($this->sqlRelease&&$this->releaseCalls===1)$this->last_error='closed';return $this->release!==[]?array_shift($this->release):'1';}
}
final class R1dbReferenceWpdb extends wpdb{
    public string $active='';public function __construct(){$this->prefix='wp_';$this->comments='wp_comments';$this->posts='wp_posts';}
    public function prepare($query,...$args){$index=0;return preg_replace_callback('/%[sd]/',function($match)use(&$index,$args){$value=$args[$index++]??'';return $match[0]==='%d'?(string)(int)$value:"'".(string)$value."'";},$query);}
    public function get_var($query=null,$x=0,$y=0){$query=(string)$query;if(str_starts_with($query,'SHOW TABLES LIKE '))return trim(substr($query,17)," '");if(str_contains($query,'SELECT COUNT(*)'))return str_contains($query,$this->active)?'1':'0';return null;}
}
$roleSource=file_get_contents(dirname(__DIR__,2).'/app/Modules/Minimarket/Identity/PendingMinimarketRole.php');$serviceSource=file_get_contents(dirname(__DIR__,2).'/app/Modules/Minimarket/Onboarding/Account/ActivatePendingMinimarketAccount.php');
r1db(is_string($roleSource)&&str_contains($roleSource,"'read'=>true")&&str_contains($roleSource,'veciahorra_continue_store_onboarding')&&!str_contains($roleSource,'veciahorra_manage_store'),'Rol pendiente fuera de contrato.');
r1db(is_string($serviceSource)&&!str_contains($serviceSource,'wp_mail')&&!str_contains($serviceSource,'wp_set_auth_cookie')&&!str_contains($serviceSource,'_veciahorra_store_id'),'Servicio invadio superficie.');
foreach(['short','12345678901'."\0",str_repeat('a',129)] as $bad){try{new SensitivePassword($bad);throw new RuntimeException('Password hostil aceptada.');}catch(PendingAccountException $e){r1db($e->reason==='invalid_password','Password mal clasificada.');}}
$password=new SensitivePassword('correct horse batería 2026');r1db((new RandomOpaqueUsernameGenerator())->generate()!=='' ,'Username CSPRNG fallo.');
$passwordCases=[[str_repeat('a',11),false],[str_repeat('a',12),true],[str_repeat('a',128),true],[str_repeat('a',129),false],[str_repeat('ñ',12),true],["\xC3\x28".str_repeat('a',12),false],['  password with spaces  ',true],["password nul\0x",false],["password\x1Fx",false],[str_repeat('ñ',257),false],['',false],['hostile password marker 2026',true]];$passwordPass=0;foreach($passwordCases as [$candidate,$valid]){try{$sensitive=new SensitivePassword($candidate);r1db($valid,'Password invalida aceptada.');r1db(!str_contains(print_r($sensitive,true),'hostile password marker'),'Password expuesta.');}catch(PendingAccountException $exception){r1db(!$valid&&$exception->reason==='invalid_password'&&$exception->getPrevious()===null,'Password mal cerrada.');}$passwordPass++;}try{new SensitivePassword(['not-a-string']);throw new RuntimeException('Tipo password aceptado.');}catch(TypeError){$passwordPass++;}echo 'R1DB_PASSWORD_MATRIX='.$passwordPass."/PASS\n";
$releaseCases=0;$lockDb=new R1dbLockWpdb();$lockDb->release=['0','1','1','1','1'];$commercialCalls=0;$reconcileCalls=0;$lockResult=(new MariaDbActivationLockManager($lockDb,str_repeat('l',32)))->synchronized(['application'=>'1','email'=>'2','rut'=>'3','verification'=>'4'],function()use(&$commercialCalls){$commercialCalls++;return 'durable';},function(string $result)use(&$reconcileCalls){$reconcileCalls++;return $result;});r1db($lockResult==='durable'&&$commercialCalls===1&&$reconcileCalls===0&&$lockDb->releaseCalls===5,'Retry release repitio operacion.');$releaseCases+=4;
foreach([[null,null,'1','1','1'],['0','0','1','1','1']] as $releaseQueue){$lockDb=new R1dbLockWpdb();$lockDb->release=$releaseQueue;$reconciled=0;$result=(new MariaDbActivationLockManager($lockDb,str_repeat('m',32)))->synchronized(['application'=>'1','email'=>'2','rut'=>'3','verification'=>'4'],static fn()=>'durable',function(string $value)use(&$reconciled){$reconciled++;return $value;});r1db($result==='durable'&&$reconciled===1&&$lockDb->releaseCalls===5,'Release persistente no reconcilio.');$releaseCases+=2;}
$lockDb=new R1dbLockWpdb();$lockDb->throwRelease=true;$result=(new MariaDbActivationLockManager($lockDb,str_repeat('o',32)))->synchronized(['application'=>'1','email'=>'2','rut'=>'3','verification'=>'4'],static fn()=>'durable');r1db($result==='durable'&&$lockDb->releaseCalls===5,'Excepcion release no reintento.');$releaseCases+=2;
$lockDb=new R1dbLockWpdb();$lockDb->sqlRelease=true;$result=(new MariaDbActivationLockManager($lockDb,str_repeat('p',32)))->synchronized(['application'=>'1','email'=>'2','rut'=>'3','verification'=>'4'],static fn()=>'durable');r1db($result==='durable'&&$lockDb->releaseCalls===5,'Error SQL release no reintento.');$releaseCases+=2;
$lockDb=new R1dbLockWpdb();$lockDb->release=['0','1','1','1'];try{(new MariaDbActivationLockManager($lockDb,str_repeat('n',32)))->synchronized(['application'=>'1','email'=>'2','rut'=>'3','verification'=>'4'],static function(){throw new RuntimeException('hostile payload');});throw new RuntimeException('Throwable hostil escapo.');}catch(PendingAccountException $exception){r1db($exception->reason==='pending_account_outcome_uncertain'&&$exception->getPrevious()===null&&!str_contains($exception->getMessage(),'hostile'),'Throwable/release mal cerrado.');}
$releaseCases+=4;r1db($releaseCases===16,'Conteo release incompleto.');echo 'R1DB_RELEASE_LOCKS='.$releaseCases."/PASS\n";
$referencePairs=[['wp_comments','user_id'],['wp_posts','post_author'],['wp_va_cart_items','user_id'],['wp_va_checkouts','user_id'],['wp_va_deliveries','courier_id'],['wp_va_deliveries','customer_id'],['wp_va_orders','customer_id'],['wp_va_payments','customer_id'],['wp_va_store_decision_history','actor_user_id'],['wp_va_zonal_admin_service_zones','user_id'],['wp_va_zonal_admin_service_zones','created_by'],['wp_wc_customer_lookup','user_id'],['wp_wc_download_log','user_id'],['wp_wc_orders','customer_id'],['wp_wc_webhooks','user_id'],['wp_woocommerce_api_keys','user_id'],['wp_woocommerce_downloadable_product_permissions','user_id'],['wp_woocommerce_payment_tokens','user_id'],['wp_wpforms_logs','user_id']];$referenceMethod=new ReflectionMethod(WordPressPendingUserGateway::class,'hasCommercialReferences');$referenceMethod->setAccessible(true);$referenceProduction=$GLOBALS['wpdb'];foreach($referencePairs as [$table,$column]){$referenceDb=new R1dbReferenceWpdb();$referenceDb->active="`{$table}` WHERE `{$column}`=";$GLOBALS['wpdb']=$referenceDb;r1db($referenceMethod->invoke(new WordPressPendingUserGateway(),700)===true,'Referencia comercial omitida.');}$GLOBALS['wpdb']=$referenceProduction;echo 'R1DB_COMMERCIAL_REFERENCES='.count($referencePairs)."/PASS\nR1DB_COMMERCIAL_REFERENCES_NOT_APPLICABLE=4\n";
$database=(string)getenv('VA_R1DA_DISPOSABLE_DATABASE');
if($database!==''){
    r1db($database==='minimarket_r1da_disposable','Base desechable invalida.');global $wpdb;$production=$wpdb;$createdUser=0;$matrixUsers=[];
    try{$wpdb=new wpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$wpdb->set_prefix('wp_');wp_roles()->for_site();(new PendingMinimarketRole())->register();$role=get_role(PendingMinimarketRole::ROLE);r1db($role instanceof WP_Role&&array_keys(array_filter($role->capabilities))===['read',PendingMinimarketRole::CAPABILITY],'Rol real incorrecto.');
        $roleCases=[['administrator',[]],['customer',[]],['veciahorra_courier',[]],['veciahorra_service_provider',[]],['veciahorra_zonal_admin',[]],['veciahorra_minimarket',[]],['subscriber',[]],[PendingMinimarketRole::ROLE,['customer']],[PendingMinimarketRole::ROLE,['veciahorra_courier']],[PendingMinimarketRole::ROLE,['veciahorra_service_provider']],[PendingMinimarketRole::ROLE,['veciahorra_zonal_admin']],[PendingMinimarketRole::ROLE,['veciahorra_minimarket']],[PendingMinimarketRole::ROLE,[],true],['subscriber',['customer']],['r1db_corrupt_role',[]],['',[]],[PendingMinimarketRole::ROLE,[]]];$gateway=new WordPressPendingUserGateway();
        $roleCasesPassed=0;foreach($roleCases as $index=>$case){[$primary,$additional]=$case;$id=wp_insert_user(['user_login'=>'r1db_role_'.str_pad((string)$index,2,'0',STR_PAD_LEFT),'user_email'=>'r1db-role-'.$index.'@example.test','user_pass'=>'role matrix password 2026','role'=>$primary]);r1db(is_int($id),'No creo fixture de rol.');$matrixUsers[]=$id;$wpUser=new WP_User($id);foreach($additional as $extra)$wpUser->add_role($extra);if(($case[2]??false)===true)$wpUser->add_cap('r1db_forbidden_capability');if($primary===''){$wpUser->set_role('');}$mapped=$gateway->find($id);r1db($mapped!==null&&$gateway->isCompatible($mapped,2147480000)===($index===16),'Clasificacion de rol incorrecta.');$roleCasesPassed++;}
        echo 'R1DB_ROLE_MATRIX='.$roleCasesPassed."/PASS\n";
        $sessionUser=wp_insert_user(['user_login'=>'r1db_session_single','user_email'=>'r1db-session-single@example.test','user_pass'=>'session matrix password 2026','role'=>PendingMinimarketRole::ROLE]);r1db(is_int($sessionUser),'Fixture sesion fallo.');$matrixUsers[]=$sessionUser;$sessionPending=$gateway->find($sessionUser);r1db($sessionPending!==null&&$gateway->canCompensate($sessionPending,2147480000),'Sin sesion no compensable.');$tokens=WP_Session_Tokens::get_instance($sessionUser);$tokens->create(time()+3600);r1db(!$gateway->canCompensate($sessionPending,2147480000),'Una sesion aceptada.');$tokens->create(time()+7200);r1db(!$gateway->canCompensate($sessionPending,2147480000),'Varias sesiones aceptadas.');
        $failingSessions=new class implements VeciAhorra\Modules\Minimarket\Onboarding\Account\PendingUserSessionInspector{public function hasActiveSessions(int $userId):bool{throw new RuntimeException('hostile session');}};try{(new WordPressPendingUserGateway($failingSessions))->canCompensate($sessionPending,2147480000);throw new RuntimeException('Inspeccion hostil aceptada.');}catch(RuntimeException $exception){r1db($exception->getMessage()==='hostile session','Seam de sesiones no propago al cierre del servicio.');}
        $sessionCases=4;$raceUser=wp_insert_user(['user_login'=>'r1db_session_race','user_email'=>'r1db-session-race@example.test','user_pass'=>'session race password 2026','role'=>PendingMinimarketRole::ROLE]);r1db(is_int($raceUser),'Fixture carrera sesion fallo.');$matrixUsers[]=$raceUser;$racePending=$gateway->find($raceUser);r1db($racePending!==null&&$gateway->canCompensate($racePending,2147480000),'Precondicion carrera sesion fallo.');WP_Session_Tokens::get_instance($raceUser)->create(time()+3600);r1db(!$gateway->canCompensate($racePending,2147480000),'Sesion concurrente aceptada.');$sessionCases++;echo 'R1DB_SESSIONS='.$sessionCases."/PASS\n";
        $beforeHistorical=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->users}");$compAllowedCases=0;$compUser=wp_insert_user(['user_login'=>'r1db_comp_allowed','user_email'=>'r1db-comp-allowed@example.test','user_pass'=>'compensation password 2026','role'=>PendingMinimarketRole::ROLE]);r1db(is_int($compUser),'Fixture compensacion fallo.');$compPending=$gateway->find($compUser);r1db($compPending!==null&&$gateway->canCompensate($compPending,2147480000),'Compensacion exacta rechazada.');$compAllowedCases++;r1db($gateway->compensate($compPending)&&$gateway->find($compUser)===null,'Compensacion exacta fallo.');$compAllowedCases++;r1db($gateway->compensate($compPending)===false,'Replay compensacion elimino otro User.');r1db((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->users}")===$beforeHistorical,'Compensacion altero User historico.');$compAllowedCases++;echo 'R1DB_COMPENSATION_ALLOWED='.$compAllowedCases."/PASS\n";
        $apps=new StoreOnboardingApplicationRepository();$verifications=new StoreOnboardingEmailVerificationRepository();$t0='2026-10-01 00:00:00';$t1='2026-10-01 00:01:00';$t2='2026-10-01 00:02:00';$t3='2026-10-01 00:03:00';$token=str_repeat("z\0",16);$emailHash=str_repeat('e',32);
        $app=$apps->createProvisioning(['public_id'=>'onb_r1db_test','account_email'=>'r1db.pending@example.test','owner_rut_normalized'=>'12345678-5','idempotency_key_hash'=>hash('sha256','r1db-test'),'terms_version'=>'R1C-LEGAL-2026-07-30-V1','terms_accepted_at'=>$t0,'created_at'=>$t0,'updated_at'=>$t0]);$aid=(int)$app->data['id'];
        $v=$verifications->create($aid,StoreOnboardingEmailVerification::PURPOSE,null,$emailHash,$token,'2026-10-02 00:00:00',$t0);$v=$verifications->markDeliveryAttempt($aid,1,$v->updatedAt,$t1);$v=$verifications->markSent($aid,1,$v->updatedAt,$t2);
        $generator=new class implements OpaqueUsernameGenerator{public int $n=0;public function generate():string{return 'va_mm_'.str_pad(dechex(++$this->n),32,'0',STR_PAD_LEFT);}};
        $service=new ActivatePendingMinimarketAccount($apps,$verifications,new WordPressPendingUserGateway(),$generator,new MariaDbActivationLockManager($wpdb,str_repeat('s',32)));
        $result=$service->execute(new ActivatePendingMinimarketAccountCommand($aid,$token,1,$password,$t3));$createdUser=$result->userId;r1db($result->outcome===ActivatePendingMinimarketAccountResult::CREATED&&$result->status==='account_created','Activacion fallo: '.$result->outcome.'/'.$result->status.'.');
        $user=get_user_by('id',$createdUser);r1db($user instanceof WP_User&&preg_match('/\Ava_mm_[a-f0-9]{32}\z/',$user->user_login)===1&&$user->roles===[PendingMinimarketRole::ROLE]&&wp_check_password('correct horse batería 2026',$user->user_pass,$createdUser),'User pendiente invalido.');
        $replay=$service->execute(new ActivatePendingMinimarketAccountCommand($aid,$token,1,new SensitivePassword('different replay password 2026'),$t3));r1db($replay->outcome===ActivatePendingMinimarketAccountResult::REPLAYED&&wp_check_password('correct horse batería 2026',$user->user_pass,$createdUser),'Replay cambio password.');
        r1db((int)$wpdb->get_var("SELECT COUNT(*) FROM wp_va_stores WHERE owner_user_id={$createdUser}")===0&&get_user_meta($createdUser,'_veciahorra_store_id',true)==='','Se creo contexto Store.');
        echo "R1DB_DISPOSABLE=PASS role=PASS create=PASS password=PASS attach=PASS replay=PASS isolation=PASS\n";
    }finally{require_once ABSPATH.'wp-admin/includes/user.php';if($createdUser>0)wp_delete_user($createdUser);foreach($matrixUsers as $matrixUser)wp_delete_user($matrixUser);$wpdb->delete('wp_va_store_onboarding_email_verifications',['application_id'=>$aid??0]);$wpdb->delete('wp_va_store_onboarding_applications',['id'=>$aid??0]);$wpdb=$production;}
}
echo "R1DB_ISOLATED=PASS password=PASS username=PASS privacy=PASS surface=PASS\n";
