<?php
declare(strict_types=1);
define('WP_INSTALLING',true);require_once dirname(__DIR__,5).'/wp-load.php';
function fm(bool$c,string$r):void{if(!$c)throw new RuntimeException($r);}function keyed(array$ids):array{$o=[];foreach($ids as$id)$o[$id]=true;return$o;}
$database=(string)getenv('VA_R1DCA_DATABASE');fm($database==='minimarket_r1dca_restore','database_guard');$secret=bin2hex(random_bytes(32));
$run=static function(string$file)use($secret,$database):array{putenv('VA_R1DCA_DATABASE='.$database);putenv('VA_R1DCA_MANIFEST_SECRET='.$secret);$pipes=[];$p=proc_open([PHP_BINARY,__DIR__.'/'.$file],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,__DIR__);fm(is_resource($p),'runner_start');fclose($pipes[0]);$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($p);echo$out;fm($exit===0&&$err==='','group_exit');$manifests=[];$prefix='R1DCA_MANIFEST=';foreach(preg_split('/\R/',trim($out))as$line)if(str_starts_with($line,$prefix)){$wire=substr($line,strlen($prefix));[$encoded,$mac]=array_pad(explode('.',$wire,2),2,'');$json=base64_decode($encoded,true);fm(is_string($json)&&hash_equals(hash_hmac('sha256',$json,$secret),$mac),'manifest_auth');$m=json_decode($json,true,8,JSON_THROW_ON_ERROR);fm(is_array($m)&&($m['count']??-1)===count($m['ids']??[]),'manifest_shape');$manifests[]=$m;}fm($manifests!==[],'manifest_missing');return['exit'=>$exit,'manifests'=>$manifests];};
$groups=[
'qa1'=>$run('minimarket-onboarding-r1d-c-a-cleanup-qa1-test.php'),
'qa2'=>$run('minimarket-onboarding-r1d-c-a-schema-failure-test.php'),
'qa3'=>$run('minimarket-onboarding-r1d-c-a-concurrency-test.php'),
'qa4'=>$run('minimarket-onboarding-r1d-c-a-anti-false-pass-test.php')];
$expected=[];foreach(['BCL'=>['NOMINAL','INELIGIBLE','ZERO-ROWS','MULTIPLE-ROWS','DELETE-ERROR','ROLLBACK-BEFORE-DELETE','COMMIT-APPLIED-FALSE','COMMIT-NOT-APPLIED-FALSE','ABSENT-AFTER-AMBIGUOUS','PRIOR-SNAPSHOT-PRESENT','ROLLED-OVER-SNAPSHOT','CLEANUP-IDEMPOTENT'],'SCL'=>['NOMINAL','INELIGIBLE','ZERO-ROWS','MULTIPLE-ROWS','DELETE-ERROR','ROLLBACK-BEFORE-DELETE','COMMIT-APPLIED-FALSE','COMMIT-NOT-APPLIED-FALSE','ABSENT-AFTER-AMBIGUOUS','PRIOR-SNAPSHOT-PRESENT','MODIFIED-SNAPSHOT','CLEANUP-IDEMPOTENT'],'RCN'=>['INT-ZERO','STRING-ZERO','INT-ONE','STRING-ONE','NULL','FALSE','EMPTY-STRING','NONCANONICAL-NUMERIC','SQL-ERROR','CONNECTION-LOST','READ-SQL-ERROR','HYDRATION-CORRUPT'],'RLS'=>['RELEASE-ONE','RELEASE-STRING-ONE','RELEASE-ZERO','RELEASE-NULL','RELEASE-FALSE','RELEASE-SQL-ERROR','RELEASE-THROWABLE','MULTIPLE-LOCKS-INVERSE','CLOSE-AFTER-SAFE-CLEANUP','CLOSE-BEFORE-CLEANUP-PROVEN']]as$p=>$names)foreach($names as$i=>$name)$expected['qa1'][]=$p.'-'.str_pad((string)($i+1),2,'0',STR_PAD_LEFT).'-'.$name;
$expected['qa2']=['SCH-F01-SESSION-COLUMN-DRIFT','SCH-F02-SESSION-INDEX-DRIFT','SCH-F03-BUCKET-COLUMN-DRIFT','SCH-F04-BUCKET-INDEX-DRIFT','SCH-F05-ONLY-SESSION-TABLE','SCH-F06-ONLY-BUCKET-TABLE','SCH-F07-BOTH-TABLES-MISSING','SCH-F08-FIRST-DBDELTA-FAILS','SCH-F09-SECOND-DBDELTA-FAILS','SCH-F10-LAST-ERROR-WITH-PARTIAL-SCHEMA','SCH-F11-PREFIXED-INDEX','SCH-F12-EXTRA-COLUMN','SCH-F13-EXTRA-INDEX','SCH-F14-WRONG-COLUMN-ORDER','SCH-F15-WRONG-ENGINE','SCH-F16-WRONG-COLLATION','SCH-F17-VERSION-NOT-ADVANCED','SCH-F18-RECOVERY-FROM-PARTIAL'];
$expected['qa3']=['CONC-01-TWO-FIRST-HITS','CONC-02-LAST-SLOT','CONC-03-CROSSED-MULTIBUCKET','CONC-04-REVERSED-INPUT-ORDER','CONC-05-BUCKET-CLEANUP-VS-ROLLOVER','CONC-06-BUCKET-CLEANUP-VS-CURRENT-HIT','CONC-07-SESSION-CLEANUP-VS-CONSUME','CONC-08-SESSION-CLEANUP-VS-INVALIDATE','CONC-09-COMMIT-APPLIED-FALSE','CONC-10-COMMIT-NOT-APPLIED-FALSE','CONC-11-CONNECTION-LOSS','CONC-12-RELEASE-FAILURE'];
$expected['qa4']=['MUT-01-ABSENCE-AS-ERROR','MUT-02-SQL-ERROR-AS-ABSENCE','MUT-03-MODIFIED-AS-APPLIED','MUT-04-DIRTY-CONNECTION-READS','MUT-05-DELETE-REPEATED','MUT-06-RENEWED-ROW-DELETED','MUT-07-PARTIAL-SCHEMA-ACCEPTED','MUT-08-VERSION-ADVANCED','MUT-09-CONCURRENCY-CASE-OMITTED','MUT-10-REGISTERED-NOT-EXECUTED','MUT-11-LITERAL-TOTAL','MUT-12-RESIDUAL-FIXTURE-IGNORED'];
$extract=static function(array$group):array{$ids=[];foreach($group['manifests']as$m)foreach($m['ids']as$id)$ids[]=$id;return$ids;};$approved=[];foreach($groups as$name=>$group){$ids=$extract($group);fm($ids===$expected[$name],'group_manifest_'.$name);fm(count($ids)===count(array_unique($ids)),'group_duplicate_'.$name);echo'R1DCA_FINAL_MANIFEST_'.strtoupper($name).'='.implode(',',$ids).PHP_EOL;$approved=array_merge($approved,$ids);}fm(count($approved)===88&&count(array_unique($approved))===88,'final_ledger_ids');
$db=new wpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$db->set_prefix('wp_');$clean=static function()use($db):bool{return(int)$db->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_applications')===0&&(int)$db->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_email_verifications')===0&&(int)$db->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_activation_sessions')===0&&(int)$db->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_rate_limit_buckets')===0&&(int)$db->get_var("SELECT COUNT(*) FROM information_schema.PROCESSLIST WHERE DB='minimarket_r1dca_restore' AND STATE LIKE '%lock%'")===0&&(int)$db->get_var('SELECT COUNT(*) FROM information_schema.INNODB_TRX')===0;};fm($clean(),'global_cleanup');echo'R1DCA_FINAL_FIX_MATRIX='.count($approved).'/PASS'.PHP_EOL;
$guards=0;$reject=static function(callable$f,string$r)use(&$guards):void{$e=null;try{$f();}catch(Throwable$x){$e=$x;}fm($e!==null&&get_class($e)===RuntimeException::class&&$e->getMessage()===$r&&$e->getPrevious()===null,'ledger_guard');$guards++;};$validate=static function(array$g,array$wanted,bool$cleanup=true):void{fm(isset($g['qa1'],$g['qa2'],$g['qa3'],$g['qa4']),'ledger_group');$all=[];foreach($g as$n=>$x){fm(($x['exit']??1)===0,'ledger_exit');fm(($x['auth']??false)===true,'ledger_manifest');foreach($x['ids']??[]as$id)$all[]=$id;}fm(count($all)===count(array_unique($all)),'ledger_duplicate');fm(keyed($all)===keyed($wanted),'ledger_ids');fm($cleanup,'ledger_cleanup');};$base=[];foreach($expected as$n=>$ids)$base[$n]=['exit'=>0,'auth'=>true,'ids'=>$ids];$reject(fn()=>$validate(array_diff_key($base,['qa4'=>1]),$approved),'ledger_group');$dup=$base;$dup['qa4']['ids'][]=$expected['qa1'][0];$reject(fn()=>$validate($dup,$approved),'ledger_duplicate');$extra=$base;$extra['qa4']['ids'][]='MUT-X';$reject(fn()=>$validate($extra,$approved),'ledger_ids');$bad=$base;$bad['qa2']['exit']=1;$reject(fn()=>$validate($bad,$approved),'ledger_exit');$bad=$base;$bad['qa3']['auth']=false;$reject(fn()=>$validate($bad,$approved),'ledger_manifest');$reject(fn()=>$validate($base,$approved,false),'ledger_cleanup');$missing=$base;array_pop($missing['qa1']['ids']);$reject(fn()=>$validate($missing,$approved),'ledger_ids');$locked=$base;$reject(fn()=>$validate($locked,$approved,false),'ledger_cleanup');fm($guards===8,'ledger_guard_total');echo'R1DCA_FINAL_LEDGER_GUARDS='.$guards.'/PASS'.PHP_EOL;
