<?php
declare(strict_types=1);
define('WP_INSTALLING',true);require_once dirname(__DIR__,5).'/wp-load.php';require_once dirname(__DIR__,2).'/vendor/autoload.php';
use VeciAhorra\Modules\Minimarket\Onboarding\ActivationSession\ActivationSessionCleanupResult;
use VeciAhorra\Modules\Minimarket\Onboarding\ActivationSession\ActivationSessionException;
use VeciAhorra\Modules\Minimarket\Onboarding\ActivationSession\StoreOnboardingActivationSessionRepository;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimitException;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimiter;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\RateLimitCleanupResult;
function ca(bool$c,string$m):void{if(!$c)throw new RuntimeException($m);}function reject(callable$f,string$r):void{$e=null;try{$f();}catch(Throwable$x){$e=$x;}ca($e!==null&&$e->getMessage()===$r&&$e->getPrevious()===null,'reject_'.$r);}
final class CleanupCases{private array$ids=[];public function run(string$id,callable$f):void{ca(!isset($this->ids[$id]),'duplicate');$f();$this->ids[$id]=true;}public function seal(int$n):void{ca(count($this->ids)===$n,'count');echo'R1DCA_CLEANUP_CASE_IDS='.implode(',',array_keys($this->ids)).PHP_EOL;echo'R1DCA_CLEANUP_RECONCILIATION='.count($this->ids).'/PASS'.PHP_EOL;}}
class FaultWpdb extends wpdb{public string$mode='normal';public string$target='';public int$targetId=0;public bool$commitFault=false;public bool$releaseFault=false;public function query($query){$sql=trim((string)$query);if($this->commitFault&&strcasecmp($sql,'COMMIT')===0){$this->commitFault=false;if($this->mode==='applied')parent::query('COMMIT');else{parent::query('ROLLBACK');if($this->mode==='modified'&&$this->target!==''&&$this->targetId>0){$field=str_contains($this->target,'rate_limit')?'hit_count=2':'updated_at=DATE_ADD(updated_at, INTERVAL 1 SECOND)';parent::query("UPDATE {$this->target} SET {$field} WHERE id=".$this->targetId);}}return false;}return parent::query($query);}public function get_var($query=null,$x=0,$y=0){if($this->releaseFault&&is_string($query)&&str_contains($query,'RELEASE_LOCK')){$this->releaseFault=false;return null;}return parent::get_var($query,$x,$y);}}
class DirtyWpdb extends wpdb{public function get_var($query=null,$x=0,$y=0){if(is_string($query)&&str_contains($query,'@@session.in_transaction'))return '1';return parent::get_var($query,$x,$y);}}
$database=(string)getenv('VA_R1DCA_DATABASE');ca($database==='minimarket_r1dca_restore','database_guard');$make=function(string$class='FaultWpdb')use($database){$db=new$class(DB_USER,DB_PASSWORD,$database,DB_HOST);$db->set_prefix('wp_');return$db;};
$normalFactory=fn()=>new wpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$dirtyFactory=fn()=>new DirtyWpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);
$rateTable='wp_va_store_onboarding_rate_limit_buckets';$sessionTable='wp_va_store_onboarding_activation_sessions';$seedRate=function(FaultWpdb$db,string$suffix):int{$db->insert('wp_va_store_onboarding_rate_limit_buckets',['bucket_hash'=>hash('sha256','cleanup-'.$suffix,true),'domain'=>'get_token','window_started_at'=>'2025-01-01 00:00:00','window_seconds'=>600,'hit_count'=>1,'expires_at'=>'2025-01-01 00:10:00','created_at'=>'2025-01-01 00:00:00','updated_at'=>'2025-01-01 00:00:00']);return(int)$db->insert_id;};
$seedSession=function(FaultWpdb$db,string$suffix):int{$db->insert('wp_va_store_onboarding_activation_sessions',['session_hash'=>hash('sha256','session-'.$suffix,true),'application_id'=>1,'verification_id'=>1,'generation'=>1,'purpose'=>'minimarket_account_activation','state'=>'active','expires_at'=>'2025-01-01 00:15:00','consumed_at'=>null,'invalidated_at'=>null,'failed_attempts'=>0,'last_attempt_at'=>null,'created_at'=>'2025-01-01 00:00:00','updated_at'=>'2025-01-01 00:00:00']);return(int)$db->insert_id;};
$cleanup=function(string$type,string$mode,callable$factory)use($make,$seedRate,$seedSession,$rateTable,$sessionTable):array{$db=$make();$id=$type==='rate'?$seedRate($db,$mode.bin2hex(random_bytes(2))):$seedSession($db,$mode.bin2hex(random_bytes(2)));$db->mode=$mode;$db->target=$type==='rate'?$rateTable:$sessionTable;$db->targetId=$id;$db->commitFault=$mode!=='normal';$service=$type==='rate'?new DurableRateLimiter($db,$factory):new StoreOnboardingActivationSessionRepository($db,$factory);try{$count=$service->cleanup('2025-02-02 00:20:00',10);return[$count,null,$id,$db];}catch(Throwable$e){return[null,$e,$id,$db];}};
$cases=new CleanupCases();
$cases->run('CLEAN-01-RATE-NORMAL',function()use($cleanup,$normalFactory){[$n,$e]=$cleanup('rate','normal',$normalFactory);ca($n===1&&$e===null,'rate_normal');});
$cases->run('CLEAN-02-RATE-APPLIED',function()use($cleanup,$normalFactory){[$n,$e]=$cleanup('rate','applied',$normalFactory);ca($n===1&&$e===null,'rate_applied');});
$cases->run('CLEAN-03-RATE-NOT-APPLIED',function()use($cleanup,$normalFactory,$make,$rateTable){[$n,$e,$id]=$cleanup('rate','not',$normalFactory);ca($n===0&&$e===null,'rate_not');$make()->delete($rateTable,['id'=>$id]);});
$cases->run('CLEAN-04-RATE-MODIFIED',function()use($cleanup,$normalFactory,$make,$rateTable){[$n,$e,$id]=$cleanup('rate','modified',$normalFactory);ca($n===null&&$e instanceof DurableRateLimitException&&$e->reason==='rate_limit_cleanup_outcome_uncertain','rate_modified');$make()->delete($rateTable,['id'=>$id]);});
$cases->run('CLEAN-05-RATE-DIRTY',function()use($cleanup,$dirtyFactory){[$n,$e]=$cleanup('rate','applied',$dirtyFactory);ca($n===null&&$e instanceof DurableRateLimitException&&$e->reason==='rate_limit_cleanup_outcome_uncertain','rate_dirty');});
$cases->run('CLEAN-06-SESSION-NORMAL',function()use($cleanup,$normalFactory){[$n,$e]=$cleanup('session','normal',$normalFactory);ca($n===1&&$e===null,'session_normal');});
$cases->run('CLEAN-07-SESSION-APPLIED',function()use($cleanup,$normalFactory){[$n,$e]=$cleanup('session','applied',$normalFactory);ca($n===1&&$e===null,'session_applied');});
$cases->run('CLEAN-08-SESSION-NOT-APPLIED',function()use($cleanup,$normalFactory,$make,$sessionTable){[$n,$e,$id]=$cleanup('session','not',$normalFactory);ca($n===0&&$e===null,'session_not');$make()->delete($sessionTable,['id'=>$id]);});
$cases->run('CLEAN-09-SESSION-MODIFIED',function()use($cleanup,$normalFactory,$make,$sessionTable){[$n,$e,$id]=$cleanup('session','modified',$normalFactory);ca($n===null&&$e instanceof ActivationSessionException&&$e->reason==='activation_session_cleanup_outcome_uncertain','session_modified');$make()->delete($sessionTable,['id'=>$id]);});
$cases->run('CLEAN-10-SESSION-DIRTY',function()use($cleanup,$dirtyFactory){[$n,$e]=$cleanup('session','applied',$dirtyFactory);ca($n===null&&$e instanceof ActivationSessionException&&$e->reason==='activation_session_cleanup_outcome_uncertain','session_dirty');});
$cases->run('CLEAN-11-RATE-RESULT-APPLIED',fn()=>ca((new RateLimitCleanupResult('rate_limit_cleanup_applied'))->applied(),'rr1'));
$cases->run('CLEAN-12-RATE-RESULT-NOT',fn()=>ca(!(new RateLimitCleanupResult('rate_limit_cleanup_not_applied'))->applied(),'rr2'));
$cases->run('CLEAN-13-RATE-RESULT-INVALID',fn()=>reject(fn()=>new RateLimitCleanupResult('bad'),'rate_limit_cleanup_result_invalid'));
$cases->run('CLEAN-14-SESSION-RESULT-APPLIED',fn()=>ca((new ActivationSessionCleanupResult('activation_session_cleanup_applied'))->applied(),'sr1'));
$cases->run('CLEAN-15-SESSION-RESULT-NOT',fn()=>ca(!(new ActivationSessionCleanupResult('activation_session_cleanup_not_applied'))->applied(),'sr2'));
$cases->run('CLEAN-16-SESSION-RESULT-INVALID',fn()=>reject(fn()=>new ActivationSessionCleanupResult('bad'),'activation_session_cleanup_result_invalid'));
$cases->run('CLEAN-17-PRIVACY',function(){$a=new ActivationSessionException('activation_session_cleanup_outcome_uncertain');$r=new DurableRateLimitException('rate_limit_cleanup_outcome_uncertain');ca($a->getPrevious()===null&&$r->getPrevious()===null&&!str_contains($a->getMessage(),'SELECT'),'privacy');});
$cases->run('CLEAN-18-RESIDUAL',function()use($make,$rateTable,$sessionTable){$db=$make();ca((int)$db->get_var("SELECT COUNT(*) FROM {$rateTable}")===0&&(int)$db->get_var("SELECT COUNT(*) FROM {$sessionTable}")===0,'residual');});
$cases->seal(18);
