<?php
declare(strict_types=1);
define('WP_INSTALLING',true);require_once dirname(__DIR__,5).'/wp-load.php';require_once dirname(__DIR__,2).'/vendor/autoload.php';require_once __DIR__.'/minimarket-onboarding-r1d-c-a-case-registry.php';require_once __DIR__.'/minimarket-onboarding-r1d-c-a-barrier.php';
function cc(bool$c,string$r):void{if(!$c)throw new RuntimeException($r);}function cid(array$names):array{$out=[];foreach($names as$n)$out[$n]=$n;return$out;}
$database=(string)getenv('VA_R1DCA_DATABASE');cc($database==='minimarket_r1dca_restore','database_guard');global$wpdb;$wpdb=new wpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$wpdb->set_prefix('wp_');$rate='wp_va_store_onboarding_rate_limit_buckets';$sessions='wp_va_store_onboarding_activation_sessions';$apps='wp_va_store_onboarding_applications';$vers='wp_va_store_onboarding_email_verifications';
$wipe=static function()use($wpdb,$rate,$sessions,$apps,$vers):void{$wpdb->query("DELETE FROM {$sessions}");$wpdb->query("DELETE FROM {$rate}");$wpdb->query("DELETE FROM {$vers} WHERE application_id=0 OR application_id IN (SELECT id FROM {$apps} WHERE public_id LIKE 'onb_qa3_%')");$wpdb->query("DELETE FROM {$apps} WHERE public_id LIKE 'onb_qa3_%'");};
$hash=static fn(string$tag):string=>hash('sha256','r1dca-qa3-'.$tag,true);$spec=static fn(string$hash,string$domain,int$limit,int$window):array=>['hash'=>base64_encode($hash),'domain'=>$domain,'limit'=>$limit,'window'=>$window];
$seedRate=static function(string$hash,string$domain,string$start,int$count,int$window=600)use($wpdb,$rate):void{$expires=gmdate('Y-m-d H:i:s',strtotime($start.' UTC')+$window);cc($wpdb->insert($rate,['bucket_hash'=>$hash,'domain'=>$domain,'window_started_at'=>$start,'window_seconds'=>$window,'hit_count'=>$count,'expires_at'=>$expires,'created_at'=>$start,'updated_at'=>$start])===1,'seed_rate');};
$seedSession=static function(string$tag)use($wpdb,$apps,$vers,$sessions,$hash):array{
    $created='2026-01-01 00:00:00';
    cc($wpdb->insert($apps,['public_id'=>'onb_qa3_'.$tag,'user_id'=>null,'account_email'=>$tag.'@example.test','owner_rut_normalized'=>'12345678-5','status'=>'provisioning','idempotency_key_hash'=>bin2hex($hash('app-'.$tag)),'terms_version'=>'R1C-LEGAL-2026-07-30-V1','terms_accepted_at'=>$created,'store_id'=>null,'failure_code'=>null,'attempt_count'=>0,'last_attempt_at'=>null,'created_at'=>$created,'updated_at'=>$created,'abandoned_at'=>null])===1,'seed_application');$aid=(int)$wpdb->insert_id;
    cc($wpdb->insert($vers,['application_id'=>$aid,'purpose'=>'minimarket_account_activation','generation'=>1,'candidate_user_id'=>null,'attached_user_id'=>null,'email_binding_hash'=>$hash('email-'.$tag),'token_hash'=>$hash('token-'.$tag),'expires_at'=>'2026-01-02 00:00:00','consumed_at'=>null,'failed_attempts'=>0,'resend_count'=>0,'last_sent_at'=>'2026-01-01 00:00:01','delivery_state'=>'sent','delivery_attempt_count'=>1,'last_error_code'=>null,'created_at'=>$created,'updated_at'=>'2026-01-01 00:00:01'])===1,'seed_verification');$vid=(int)$wpdb->insert_id;
    cc($wpdb->insert($sessions,['session_hash'=>$hash('session-'.$tag),'application_id'=>$aid,'verification_id'=>$vid,'generation'=>1,'purpose'=>'minimarket_account_activation','state'=>'active','expires_at'=>'2026-01-01 00:15:00','consumed_at'=>null,'invalidated_at'=>null,'failed_attempts'=>0,'last_attempt_at'=>null,'created_at'=>$created,'updated_at'=>$created])===1,'seed_session');return['id'=>(int)$wpdb->insert_id,'application_id'=>$aid,'verification_id'=>$vid,'updated'=>$created];
};
$runPair=static function(string$case,array$a,array$b,bool$kill=false)use($database):array{$execution=bin2hex(random_bytes(12));$challenge=bin2hex(random_bytes(32));$directory=sys_get_temp_dir().DIRECTORY_SEPARATOR.'r1dca-'.$execution;cc(mkdir($directory,0700),'barrier_directory');$barrier=new R1dcaBarrier($directory,$execution,$case,$challenge);$configs=[];$processes=[];$pipes=[];$started=[];try{foreach(['A'=>$a,'B'=>$b]as$worker=>$operation){$config=array_merge($operation,['database'=>$database,'worker'=>$worker,'directory'=>$directory,'execution_id'=>$execution,'case_id'=>$case,'challenge'=>$challenge]);$path=$directory.DIRECTORY_SEPARATOR.'config-'.$worker.'.json';cc(file_put_contents($path,json_encode($config,JSON_THROW_ON_ERROR),LOCK_EX)!==false,'config_write');$command=[PHP_BINARY,__DIR__.'/minimarket-onboarding-r1d-c-a-concurrency-worker.php',$path];$descriptor=[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']];$started[$worker]=microtime(true);$processes[$worker]=proc_open($command,$descriptor,$pipes[$worker],__DIR__);cc(is_resource($processes[$worker]),'worker_start');fclose($pipes[$worker][0]);}
        $readyA=$barrier->await('worker_ready','A');$readyB=$barrier->await('worker_ready','B');cc($readyA['pid']!==$readyB['pid'],'worker_pid_collision');cc(($readyA['payload']['connection_id']??0)!==($readyB['payload']['connection_id']??0),'worker_connection_collision');$barrier->publish('start','coordinator');$barrier->await('target_reached','A');$barrier->await('target_reached','B');$barrier->publish('coordinator_release','coordinator');if($kill){$target=$barrier->await('kill_target','A');$killer=new wpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$connection=(int)($target['payload']['connection_id']??0);cc($connection>0&&$killer->query('KILL CONNECTION '.$connection)!==false,'connection_kill');$barrier->publish('kill_release','coordinator');}$finishedA=$barrier->await('operation_finished','A',15);$finishedB=$barrier->await('operation_finished','B',15);$results=[];foreach(['A'=>$finishedA,'B'=>$finishedB]as$worker=>$frame){$stdout=stream_get_contents($pipes[$worker][1]);$stderr=stream_get_contents($pipes[$worker][2]);fclose($pipes[$worker][1]);fclose($pipes[$worker][2]);$exit=proc_close($processes[$worker]);$decoded=json_decode(trim((string)$stdout),true);cc(is_array($decoded)&&$exit===0&&$stderr==='','worker_exit_'.$worker);cc(($decoded['pid']??null)===$frame['pid']&&($decoded['outcome']??null)===($frame['payload']['outcome']??null),'worker_frame_'.$worker);$results[$worker]=['pid'=>$decoded['pid'],'exit'=>$exit,'outcome'=>$decoded['outcome'],'error'=>$decoded['error'],'duration_ms'=>$decoded['duration_ms'],'locks'=>$decoded['locks']??[]];}$locksA=$results['A']['locks']['acquired']??[];$locksB=$results['B']['locks']['acquired']??[];if(count($locksA)>1&&count($locksA)===count($locksB)){$sorted=$locksA;sort($sorted,SORT_STRING);cc($locksA===$sorted&&$locksB===$sorted,'lock_order');cc(($results['A']['locks']['released']??[])===array_reverse($locksA)&&($results['B']['locks']['released']??[])===array_reverse($locksB),'release_order');}return$results;
    }finally{foreach($processes as$worker=>$process)if(is_resource($process)){proc_terminate($process);proc_close($process);}if(is_dir($directory)){foreach(scandir($directory)?:[]as$file)if($file!=='.'&&$file!=='..')unlink($directory.DIRECTORY_SEPARATOR.$file);rmdir($directory);}}};
$cases=['CONC-01-TWO-FIRST-HITS','CONC-02-LAST-SLOT','CONC-03-CROSSED-MULTIBUCKET','CONC-04-REVERSED-INPUT-ORDER','CONC-05-BUCKET-CLEANUP-VS-ROLLOVER','CONC-06-BUCKET-CLEANUP-VS-CURRENT-HIT','CONC-07-SESSION-CLEANUP-VS-CONSUME','CONC-08-SESSION-CLEANUP-VS-INVALIDATE','CONC-09-COMMIT-APPLIED-FALSE','CONC-10-COMMIT-NOT-APPLIED-FALSE','CONC-11-CONNECTION-LOSS','CONC-12-RELEASE-FAILURE'];$registry=new R1dcaCaseRegistry('R1DCA_CONCURRENCY',cid($cases),'R1DCA_CONCURRENCY_CASE_IDS');
$summaries=[];
foreach($cases as$i=>$case){
    $registry->run($case,function()use($i,$wipe,$hash,$spec,$seedRate,$seedSession,$wpdb,$sessions){
        $wipe();$now='2026-01-01 00:05:00';$context=['now'=>$now];
        if($i===0){$h=$hash('c01');$context+=['hashes'=>[$h],'a'=>['operation'=>'rate_consume','now'=>$now,'specs'=>[$spec($h,'get_token',10,600)]],'b'=>['operation'=>'rate_consume','now'=>$now,'specs'=>[$spec($h,'get_token',10,600)]]];}
        elseif($i===1){$h=$hash('c02');$seedRate($h,'get_token','2026-01-01 00:00:00',9);$context+=['hashes'=>[$h],'a'=>['operation'=>'rate_consume','now'=>$now,'specs'=>[$spec($h,'get_token',10,600)]],'b'=>['operation'=>'rate_consume','now'=>$now,'specs'=>[$spec($h,'get_token',10,600)]]];}
        elseif(in_array($i,[2,3],true)){$all=[['h'=>$hash('c'.$i.'a'),'d'=>'post_network','l'=>20,'w'=>900],['h'=>$hash('c'.$i.'b'),'d'=>'post_session','l'=>5,'w'=>900]];if($i===3)$all[]=['h'=>$hash('c'.$i.'c'),'d'=>'get_token','l'=>10,'w'=>600];$ordered=[];foreach($all as$x)$ordered[]=$spec($x['h'],$x['d'],$x['l'],$x['w']);$context+=['hashes'=>array_column($all,'h'),'a'=>['operation'=>'rate_consume','now'=>$now,'specs'=>$ordered],'b'=>['operation'=>'rate_consume','now'=>$now,'specs'=>array_reverse($ordered)]];}
        elseif($i===4){$h=$hash('c05');$seedRate($h,'get_token','2025-12-29 00:00:00',3);$context+=['hashes'=>[$h],'a'=>['operation'=>'rate_cleanup','now'=>$now],'b'=>['operation'=>'rate_consume','now'=>$now,'specs'=>[$spec($h,'get_token',10,600)]]];}
        elseif($i===5){$h=$hash('c06');$seedRate($h,'get_token','2026-01-01 00:00:00',1);$context+=['hashes'=>[$h],'a'=>['operation'=>'rate_cleanup','now'=>$now],'b'=>['operation'=>'rate_consume','now'=>$now,'specs'=>[$spec($h,'get_token',10,600)]]];}
        elseif(in_array($i,[6,7],true)){$s=$seedSession('c0'.($i+1));$context+=['session'=>$s,'a'=>['operation'=>'session_cleanup','now'=>$now],'b'=>['operation'=>$i===6?'session_consume':'session_invalidate','session_id'=>$s['id'],'expected_updated_at'=>$s['updated'],'now'=>$now]];}
        elseif($i===11){$s=$seedSession('c12');cc($wpdb->update($sessions,['expires_at'=>'2025-01-01 00:15:00','created_at'=>'2025-01-01 00:00:00','updated_at'=>'2025-01-01 00:00:00'],['id'=>$s['id']])===1,'c12_fixture_age');$other=$hash('c12b');$context+=['session'=>$s,'a'=>['operation'=>'session_cleanup','now'=>$now,'commit_mode'=>'applied','release_fault'=>true],'b'=>['operation'=>'rate_consume','now'=>$now,'specs'=>[$spec($other,'get_token',10,600)]]];}
        else{$h=$hash('c'.($i+1));$seedRate($h,'get_token','2025-12-29 00:00:00',1);$other=$hash('c'.($i+1).'b');$context+=['hashes'=>[$h,$other],'a'=>['operation'=>'rate_cleanup','now'=>$now,'commit_mode'=>$i===8?'applied':($i===9?'not':'loss')],'b'=>['operation'=>'rate_consume','now'=>$now,'specs'=>[$spec($other,'get_token',10,600)]],'kill'=>$i===10];}
        return$context;
    },fn($c)=>$runPair($cases[$i],$c['a'],$c['b'],$c['kill']??false),function($c,$r,$e)use($i,$cases,$wpdb,$rate,$sessions,$apps,$vers,&$summaries){
        cc($e===null,'concurrency_harness_'.$i);$oa=$r['A']['outcome'];$ob=$r['B']['outcome'];cc($r['A']['pid']!==$r['B']['pid']&&$r['A']['exit']===0&&$r['B']['exit']===0,'process_identity');
        if($i===0){cc($oa==='allowed'&&$ob==='allowed'&&(int)$wpdb->get_var("SELECT hit_count FROM {$rate}")===2,'c01_snapshot');}
        elseif($i===1){$out=[$oa,$ob];sort($out);cc($out===['allowed','blocked']&&(int)$wpdb->get_var("SELECT hit_count FROM {$rate}")===10,'c02_snapshot');}
        elseif(in_array($i,[2,3],true)){cc($oa==='allowed'&&$ob==='allowed'&&(int)$wpdb->get_var("SELECT COUNT(*) FROM {$rate} WHERE hit_count=2")===count($c['hashes']),'multi_snapshot');}
        elseif($i===4){cc($ob==='allowed'&&in_array($oa,['cleanup_0','cleanup_1'],true)&&(int)$wpdb->get_var("SELECT hit_count FROM {$rate}")===1,'c05_renewed');}
        elseif($i===5){cc($oa==='cleanup_0'&&$ob==='allowed'&&(int)$wpdb->get_var("SELECT hit_count FROM {$rate}")===2,'c06_snapshot');}
        elseif($i===6){cc($oa==='cleanup_0'&&$ob==='consumed'&&$wpdb->get_var("SELECT state FROM {$sessions}")==='consumed','c07_snapshot');}
        elseif($i===7){cc($oa==='cleanup_0'&&$ob==='invalidated'&&$wpdb->get_var("SELECT state FROM {$sessions}")==='invalidated','c08_snapshot');}
        elseif($i===8){cc($oa==='cleanup_1'&&$ob==='allowed','c09_outcome');}
        elseif($i===9){cc($oa==='cleanup_0'&&$ob==='allowed'&&(int)$wpdb->get_var("SELECT COUNT(*) FROM {$rate}")===2,'c10_outcome');}
        elseif($i===10){cc($oa==='cleanup_1'&&$ob==='allowed','c11_outcome');}
        else{$locks=$r['A']['locks'];$acquired=$locks['reconciled_acquired']??[];$released=$locks['reconciled_releases']??[];cc(($locks['global_order']??false)===true,'c12_global_order');cc(count($acquired)===2&&$released===array_reverse($acquired),'c12_release_order');cc(($locks['release_results']??[])===[0,1],'c12_release_results');cc($oa==='error'&&$r['A']['error']==='activation_session_cleanup_outcome_uncertain'&&$ob==='allowed','c12_outcome');cc((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$sessions} WHERE id=%d",$c['session']['id']))===0,'c12_session_deleted');cc((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$apps} WHERE id=%d",$c['session']['application_id']))===1,'c12_application_coherent');cc((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$vers} WHERE id=%d AND application_id=%d",$c['session']['verification_id'],$c['session']['application_id']))===1,'c12_verification_coherent');$summaries['c12_attempts']=count($released);$summaries['c12_evidence']=['acquired'=>$acquired,'released'=>$released,'results'=>$locks['release_results'],'outcome'=>$r['A']['error'],'identity'=>$r['A']['pid']!==$r['B']['pid']];}
        $summaries[$i]=$cases[$i].'|PID_A='.$r['A']['pid'].'|PID_B='.$r['B']['pid'].'|MS_A='.$r['A']['duration_ms'].'|MS_B='.$r['B']['duration_ms'].'|EXIT_A=0|EXIT_B=0|OUT_A='.$oa.'|OUT_B='.$ob;
    },function()use($i,$wipe,$wpdb,$rate,$sessions,$apps,$vers,&$summaries){$wipe();cc((int)$wpdb->get_var("SELECT COUNT(*) FROM {$rate}")===0&&(int)$wpdb->get_var("SELECT COUNT(*) FROM {$sessions}")===0&&(int)$wpdb->get_var("SELECT COUNT(*) FROM {$apps}")===0&&(int)$wpdb->get_var("SELECT COUNT(*) FROM {$vers}")===0,'case_cleanup');echo$summaries[$i].'|CLEANUP=PASS'.PHP_EOL;});
}
$total=$registry->seal();cc($total===12,'concurrency_total');echo'R1DCA_CONCURRENCY_CLEANUP=PASS'.PHP_EOL;
cc(($summaries['c12_attempts']??0)===2,'c12_release_attempt_total');echo'R1DCA_CONC12_RELEASE_ATTEMPTS='.$summaries['c12_attempts'].'/PASS'.PHP_EOL;echo'R1DCA_CONC12_RELEASE_ORDER=REVERSE/PASS'.PHP_EOL;echo'R1DCA_CONC12_RELEASE_FAILURE_PRECEDENCE=PASS'.PHP_EOL;
$guards=0;$reject=static function(callable$f)use(&$guards):void{try{$f();}catch(Throwable){$guards++;return;}throw new RuntimeException('concurrency_guard_not_closed');};
$validateC12=static function(array$e):void{cc(count($e['acquired'])>=2,'c12_guard_lock_count');cc(count($e['released'])===count($e['acquired']),'c12_guard_release_count');cc($e['released']===array_reverse($e['acquired']),'c12_guard_reverse');cc(($e['results'][0]??1)!==1,'c12_guard_first_success');cc($e['outcome']==='activation_session_cleanup_outcome_uncertain','c12_guard_outcome');cc($e['identity']===true,'c12_guard_identity');};
$evidence=$summaries['c12_evidence'];
$reject(function()use($validateC12,$evidence){$e=$evidence;$e['acquired']=[$e['acquired'][0]];$validateC12($e);});
$reject(function()use($validateC12,$evidence){$e=$evidence;array_pop($e['released']);$validateC12($e);});
$reject(function()use($validateC12,$evidence){$e=$evidence;$e['released']=$e['acquired'];$validateC12($e);});
$reject(function()use($validateC12,$evidence){$e=$evidence;$e['results'][0]=1;$validateC12($e);});
$reject(function()use($validateC12,$evidence){$e=$evidence;$e['outcome']='activation_session_cleanup_applied';$validateC12($e);});
$reject(function()use($wpdb){$name='r1dca_guard_'.bin2hex(random_bytes(8));cc((int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s,1)',$name))===1,'guard_lock_acquire');try{cc((int)$wpdb->get_var($wpdb->prepare('SELECT IS_FREE_LOCK(%s)',$name))===1,'lock_residual_ignored');}finally{$wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$name));}});
$reject(function()use($wpdb,$rate,$hash,$wipe){try{$wpdb->insert($rate,['bucket_hash'=>$hash('guard-fixture'),'domain'=>'get_token','window_started_at'=>'2026-01-01 00:00:00','window_seconds'=>600,'hit_count'=>1,'expires_at'=>'2026-01-01 00:10:00','created_at'=>'2026-01-01 00:00:00','updated_at'=>'2026-01-01 00:00:00']);cc((int)$wpdb->get_var("SELECT COUNT(*) FROM {$rate}")===0,'fixture_residual_ignored');}finally{$wipe();}});
$reject(function()use($validateC12,$evidence){$e=$evidence;$e['identity']=false;$validateC12($e);});
cc($guards===8,'concurrency_guard_count');echo'R1DCA_CONCURRENCY_GUARDS='.$guards.'/PASS'.PHP_EOL;
