<?php
declare(strict_types=1);
require_once dirname(__DIR__,5).'/wp-load.php';
require_once __DIR__.'/minimarket-onboarding-r1d-b-case-registry.php';
use VeciAhorra\Modules\Minimarket\Onboarding\StoreOnboardingApplicationRepository;
use VeciAhorra\Modules\Minimarket\Onboarding\Verification\StoreOnboardingEmailVerification;
use VeciAhorra\Modules\Minimarket\Onboarding\Verification\StoreOnboardingEmailVerificationRepository;

final class R1dbConsumeWpdb extends wpdb
{
    public string $mode='normal';public int $applicationWrites=0;public int $verificationWrites=0;public array $trace=[];public int $deleteBeforeUserId=0;public int $contradictUserId=0;private bool $commitIntercepted=false;private bool $rereadArmed=false;private bool $afterConsumeArmed=false;
    public function query($query){$sql=(string)$query;if($sql==='START TRANSACTION')$this->trace[]='start';if($sql==='ROLLBACK')$this->trace[]='rollback';if($sql==='COMMIT')$this->trace[]='commit';if($sql==='COMMIT'&&in_array($this->mode,['commit_applied_false','commit_not_applied_false','dirty_connection','reread_failed','snapshot_contradict'],true)&&!$this->commitIntercepted){$this->commitIntercepted=true;if($this->mode==='commit_not_applied_false')parent::query('ROLLBACK');else parent::query('COMMIT');if($this->mode==='reread_failed')$this->rereadArmed=true;if($this->mode==='snapshot_contradict'&&$this->contradictUserId>0){parent::query("UPDATE wp_va_store_onboarding_applications SET user_id=".(int)$this->contradictUserId." WHERE public_id LIKE 'onb_%'");parent::query("UPDATE wp_va_store_onboarding_email_verifications SET attached_user_id=".(int)$this->contradictUserId." WHERE consumed_at IS NOT NULL");}return false;}return parent::query($query);}
    public function update($table,$data,$where,$format=null,$where_format=null){$table=(string)$table;if(str_ends_with($table,'store_onboarding_applications')&&array_key_exists('status',$data)){$this->applicationWrites++;$this->trace[]='application_write';if($this->mode==='fail_before_attach'){$this->last_error='hidden application driver';return false;}}if(str_ends_with($table,'store_onboarding_email_verifications')&&array_key_exists('consumed_at',$data)){$this->verificationWrites++;$this->trace[]='verification_write';if($this->mode==='fail_after_attach'){$this->last_error='hidden verification driver';return false;}$result=parent::update($table,$data,$where,$format,$where_format);if($this->mode==='fail_after_consume')$this->afterConsumeArmed=true;return $result;}return parent::update($table,$data,$where,$format,$where_format);}
    public function get_row($query=null,$output=OBJECT,$y=0){$sql=(string)$query;if(str_contains($sql,'store_onboarding_applications')&&str_contains($sql,'FOR UPDATE'))$this->trace[]='application_lock';if(str_contains($sql,'store_onboarding_email_verifications')&&str_contains($sql,'FOR UPDATE')){$this->trace[]='verification_lock';if($this->afterConsumeArmed){$this->afterConsumeArmed=false;$this->last_error='hidden after consume';return null;}}if($this->rereadArmed&&str_contains($sql,'store_onboarding_email_verifications')&&!str_contains($sql,'FOR UPDATE')){$this->rereadArmed=false;$this->last_error='hidden reread';return null;}return parent::get_row($query,$output,$y);}
    public function get_var($query=null,$x=0,$y=0){$sql=(string)$query;if($sql==='SELECT @@in_transaction'&&$this->mode==='dirty_connection'){$this->last_error='';return '1';}if(str_contains($sql,"{$this->users}")&&str_contains($sql,'FOR UPDATE')){$this->trace[]='user_lock';if($this->deleteBeforeUserId>0){parent::delete($this->usermeta,['user_id'=>$this->deleteBeforeUserId]);parent::delete($this->users,['ID'=>$this->deleteBeforeUserId]);$this->deleteBeforeUserId=0;}}return parent::get_var($query,$x,$y);}
    public function resetEvidence():void{$this->applicationWrites=0;$this->verificationWrites=0;$this->trace=[];$this->commitIntercepted=false;$this->rereadArmed=false;$this->afterConsumeArmed=false;}
}
function r1dbConsumeOutcome(callable $operation):array{try{return ['value'=>$operation(),'reason'=>null];}catch(Throwable $throwable){return ['value'=>null,'reason'=>$throwable->getMessage(),'previous'=>$throwable->getPrevious(),'message'=>$throwable->getMessage()];}}
function r1dbConsumePrivacy(array $outcome,callable $assert):void{if($outcome['reason']===null)return;$assert(($outcome['previous']??null)===null,'consume previous leaked');foreach(['@example','12345678','SELECT ','UPDATE ','driver','hidden','token'] as $secret)$assert(!str_contains((string)$outcome['message'],$secret),'consume privacy leak');}
$database=(string)getenv('VA_R1DA_DISPOSABLE_DATABASE');if($database!=='minimarket_r1da_disposable'||$database===DB_NAME)throw new RuntimeException('consume_database_guard');global $wpdb;$production=$wpdb;$wpdb=new R1dbConsumeWpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$wpdb->set_prefix('wp_');$before=[(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->users}"),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_stores'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_applications'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_email_verifications')];if($before!==[18,348,0,0])throw new RuntimeException('consume_database_not_clean');
$users=array_map('intval',$wpdb->get_col("SELECT ID FROM {$wpdb->users} ORDER BY ID LIMIT 2"));[$userA,$userB]=$users;$runId=bin2hex(random_bytes(8));$apps=new StoreOnboardingApplicationRepository();$verifications=new StoreOnboardingEmailVerificationRepository();$registry=new R1dbCaseRegistry();$t0='2026-09-01 00:00:00';$t1='2026-09-01 00:01:00';$t2='2026-09-01 00:02:00';$t3='2026-09-01 00:03:00';$t4='2026-09-01 00:04:00';$t5='2026-09-01 00:05:00';
$setup=function(string $id)use($apps,$verifications,$runId,$t0,$t1,$t2,$t3,$userA):array{$suffix=strtolower(str_replace('-','_',$id));$app=$apps->createProvisioning(['public_id'=>'onb_'.$runId.'_'.$suffix,'account_email'=>$runId.'.'.$suffix.'@example.test','owner_rut_normalized'=>'12345678-5','idempotency_key_hash'=>hash('sha256',$runId.$id),'terms_version'=>'R1C-LEGAL-2026-07-30-V1','terms_accepted_at'=>$t0,'created_at'=>$t0,'updated_at'=>$t0]);$aid=(int)$app->data['id'];$token=hash('sha256',$runId.$id,true);$v=$verifications->create($aid,StoreOnboardingEmailVerification::PURPOSE,null,hash('sha256','email'.$runId.$id,true),$token,'2026-09-01 01:00:00',$t0);$v=$verifications->markDeliveryAttempt($aid,1,$v->updatedAt,$t1);$v=$verifications->markSent($aid,1,$v->updatedAt,$t2);$v=$verifications->bindCandidateUser($aid,1,$userA,$v->updatedAt,$t3);return ['aid'=>$aid,'token'=>$token,'v'=>$v,'user'=>0];};
$cleanup=function(?array $f)use($wpdb):void{if(!is_array($f))return;$aid=(int)($f['aid']??0);if($aid){$wpdb->delete('wp_va_store_onboarding_email_verifications',['application_id'=>$aid]);$wpdb->delete('wp_va_store_onboarding_applications',['id'=>$aid]);}$uid=(int)($f['user']??0);if($uid){$wpdb->delete($wpdb->usermeta,['user_id'=>$uid]);$wpdb->delete($wpdb->users,['ID'=>$uid]);}$wpdb->mode='normal';$wpdb->deleteBeforeUserId=0;$wpdb->contradictUserId=0;};
$consume=function(array $f,int $user,string $token,int $generation=1,string $appTime='2026-09-01 00:00:00',string $verificationTime='2026-09-01 00:03:00',string $now='2026-09-01 00:04:00')use($verifications){return $verifications->consumeAndAttach($f['aid'],$generation,$token,$user,$appTime,$verificationTime,$now,static fn(int $id,string $email,?int $candidate):bool=>$id>0&&$email!==''&&($candidate===null||$candidate===$id));};
$state=function(int $aid)use($wpdb):array{return ['app'=>$wpdb->get_row($wpdb->prepare('SELECT status,user_id,store_id,failure_code,updated_at FROM wp_va_store_onboarding_applications WHERE id=%d',$aid),ARRAY_A),'v'=>$wpdb->get_row($wpdb->prepare('SELECT candidate_user_id,attached_user_id,consumed_at,updated_at FROM wp_va_store_onboarding_email_verifications WHERE application_id=%d',$aid),ARRAY_A)];};
$add=function(string $id,string $description,callable $prepare,callable $operation,callable $verify)use($registry,$setup,$cleanup,$wpdb):void{$registry->add($id,$description,function(string $caseId)use($setup,$prepare,$wpdb){$fixture=$setup($caseId);$wpdb->resetEvidence();return $prepare($fixture);},$operation,function($fixture,$outcome,$assert,$caseId)use($verify){r1dbConsumePrivacy($outcome,$assert);$verify($fixture,$outcome,$assert,$caseId);},$cleanup);};$same=static fn(array $f):array=>$f;
$initial=function(array $s):bool{return $s['app']['status']==='provisioning'&&$s['app']['user_id']===null&&$s['v']['consumed_at']===null&&$s['v']['attached_user_id']===null;};
$add('CAA-01','nominal',$same,fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),function($f,$o,$a)use($state,$userA,$wpdb){$s=$state($f['aid']);$positions=[];foreach(['application_lock','verification_lock','user_lock','application_write','verification_write','commit'] as $event){$position=array_search($event,$wpdb->trace,true);$positions[]=$position===false?PHP_INT_MAX:$position;}$sorted=$positions;sort($sorted);$a($o['reason']===null&&$s['app']['status']==='account_created'&&(int)$s['app']['user_id']===$userA&&(int)$s['v']['attached_user_id']===$userA&&$s['v']['consumed_at']!==null&&$wpdb->applicationWrites===1&&$wpdb->verificationWrites===1&&$positions===$sorted&&count(array_filter($wpdb->trace,static fn($event)=>$event==='start'))===1&&count(array_filter($wpdb->trace,static fn($event)=>$event==='commit'))===1&&!in_array('rollback',$wpdb->trace,true));});
$add('CAA-02','durable replay',function($f)use($consume,$userA,$wpdb){$consume($f,$userA,$f['token']);$f['snapshot']=$GLOBALS['state']??null;$wpdb->resetEvidence();return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'],1,$t0,$t3,$t5)),function($f,$o,$a)use($state,$wpdb){$s=$state($f['aid']);$a($o['reason']===null&&$s['app']['updated_at']==='2026-09-01 00:04:00'&&$s['v']['updated_at']==='2026-09-01 00:04:00'&&$wpdb->applicationWrites===0&&$wpdb->verificationWrites===0);});
$add('CAA-03','other user',$same,fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userB,$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='verification_user_incompatible'&&$initial($state($f['aid']))&&$wpdb->applicationWrites===0&&$wpdb->verificationWrites===0));
$add('CAA-04','invalid token',$same,fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,str_repeat('x',32))),fn($f,$o,$a)=>$a($o['reason']==='verification_consumption_forbidden'&&$initial($state($f['aid']))&&$wpdb->applicationWrites===0));
$add('CAA-05','expired',function($f)use($wpdb){$wpdb->update('wp_va_store_onboarding_email_verifications',['expires_at'=>'2026-09-01 00:04:00'],['application_id'=>$f['aid']]);$wpdb->resetEvidence();return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='verification_consumption_forbidden'&&$initial($state($f['aid']))&&$wpdb->applicationWrites===0));
$add('CAA-06','attempts exhausted',function($f)use($wpdb){$wpdb->update('wp_va_store_onboarding_email_verifications',['failed_attempts'=>5],['application_id'=>$f['aid']]);$wpdb->resetEvidence();return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='verification_consumption_forbidden'&&$initial($state($f['aid']))&&$wpdb->applicationWrites===0));
$add('CAA-07','generation mismatch',$same,fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'],2)),fn($f,$o,$a)=>$a($o['reason']==='verification_consumption_forbidden'&&$initial($state($f['aid']))&&$wpdb->applicationWrites===0));
$add('CAA-08','application already attached incompatible',function($f)use($wpdb,$userB,$t4){$wpdb->update('wp_va_store_onboarding_applications',['status'=>'account_created','user_id'=>$userB,'updated_at'=>$t4],['id'=>$f['aid']]);$wpdb->resetEvidence();return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a(in_array($o['reason'],['onboarding_user_conflict','verification_outcome_uncertain','verification_persistence_failed'],true)&&$wpdb->applicationWrites===0&&$wpdb->verificationWrites===0));
$add('CAA-09','unexpected store',function($f)use($wpdb){$store=(int)$wpdb->get_var('SELECT id FROM wp_va_stores ORDER BY id LIMIT 1');$wpdb->update('wp_va_store_onboarding_applications',['store_id'=>$store],['id'=>$f['aid']]);$wpdb->resetEvidence();return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='verification_consumption_forbidden'&&$wpdb->applicationWrites===0&&$wpdb->verificationWrites===0));
$add('CAA-10','unexpected failure code',function($f)use($wpdb){$wpdb->update('wp_va_store_onboarding_applications',['status'=>'provisioning_failed','failure_code'=>'account_provisioning_failed'],['id'=>$f['aid']]);$wpdb->resetEvidence();return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='onboarding_state_incompatible'&&$wpdb->applicationWrites===0&&$wpdb->verificationWrites===0));
$add('CAA-11','consumed incoherent application',function($f)use($wpdb,$userA,$t4){$wpdb->update('wp_va_store_onboarding_email_verifications',['attached_user_id'=>$userA,'consumed_at'=>$t4,'updated_at'=>$t4],['application_id'=>$f['aid']]);$wpdb->resetEvidence();return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='verification_reference_invalid'&&$wpdb->applicationWrites===0&&$wpdb->verificationWrites===0));
$add('CAA-12','attached different user',function($f)use($wpdb,$userB,$t4){$wpdb->update('wp_va_store_onboarding_applications',['status'=>'account_created','user_id'=>$userB,'updated_at'=>$t4],['id'=>$f['aid']]);$wpdb->update('wp_va_store_onboarding_email_verifications',['attached_user_id'=>$userB,'consumed_at'=>$t4,'updated_at'=>$t4],['application_id'=>$f['aid']]);$wpdb->resetEvidence();return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='verification_conflict'&&$wpdb->applicationWrites===0&&$wpdb->verificationWrites===0));
$add('CAA-13','user deleted at locked revalidation',function($f)use($wpdb){$uid=wp_insert_user(['user_login'=>'r1dbcaa_'.bin2hex(random_bytes(8)),'user_email'=>bin2hex(random_bytes(8)).'@example.test','user_pass'=>'consume password 2026','role'=>'subscriber']);if(!is_int($uid))throw new RuntimeException('consume_fixture_user');$f['user']=$uid;$wpdb->update('wp_va_store_onboarding_email_verifications',['candidate_user_id'=>$uid],['application_id'=>$f['aid']]);$wpdb->deleteBeforeUserId=$uid;$wpdb->resetEvidence();return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$f['user'],$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='verification_user_incompatible'&&$initial($state($f['aid']))&&$wpdb->applicationWrites===0));
foreach([['CAA-14','failure before attach','fail_before_attach'],['CAA-15','failure after attach','fail_after_attach'],['CAA-16','failure after consume','fail_after_consume']] as [$id,$description,$mode])$add($id,$description,function($f)use($wpdb,$mode){$wpdb->resetEvidence();$wpdb->mode=$mode;return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),function($f,$o,$a)use($state,$initial,$wpdb,$id){$s=$state($f['aid']);$expected=$id==='CAA-14'?[1,0]:($id==='CAA-15'?[1,1]:[1,1]);$a($o['reason']!==null&&$initial($s)&&[$wpdb->applicationWrites,$wpdb->verificationWrites]===$expected,$id.' rollback');});
$add('CAA-17','commit applied false',function($f)use($wpdb){$wpdb->resetEvidence();$wpdb->mode='commit_applied_false';return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),function($f,$o,$a)use($state,$userA,$wpdb){$s=$state($f['aid']);$a($o['reason']===null&&(int)$s['app']['user_id']===$userA&&(int)$s['v']['attached_user_id']===$userA&&$wpdb->applicationWrites===1&&$wpdb->verificationWrites===1);});
$add('CAA-18','commit not applied false',function($f)use($wpdb){$wpdb->resetEvidence();$wpdb->mode='commit_not_applied_false';return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='verification_persistence_failed'&&$initial($state($f['aid']))&&$wpdb->applicationWrites===1&&$wpdb->verificationWrites===1));
$add('CAA-19','connection not clean',function($f)use($wpdb){$wpdb->resetEvidence();$wpdb->mode='dirty_connection';return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='verification_outcome_uncertain'&&$wpdb->applicationWrites===1&&$wpdb->verificationWrites===1));
$add('CAA-20','reconciliation reread failed',function($f)use($wpdb){$wpdb->resetEvidence();$wpdb->mode='reread_failed';return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a($o['reason']==='verification_outcome_uncertain'&&$wpdb->applicationWrites===1&&$wpdb->verificationWrites===1));
$add('CAA-21','contradictory durable snapshot',function($f)use($wpdb,$userB){$wpdb->resetEvidence();$wpdb->mode='snapshot_contradict';$wpdb->contradictUserId=$userB;return $f;},fn($f)=>r1dbConsumeOutcome(fn()=>$consume($f,$userA,$f['token'])),fn($f,$o,$a)=>$a(in_array($o['reason'],['verification_persistence_failed','verification_conflict','verification_outcome_uncertain'],true)&&$wpdb->applicationWrites===1&&$wpdb->verificationWrites===1));
try{$results=$registry->runAll(21);$ids=$results->passedIds();if($results->failedIds()!==[]||count($ids)!==21)throw new RuntimeException('consume_failed='.json_encode($results->failureDetails(),JSON_UNESCAPED_SLASHES));}finally{$wpdb->mode='normal';$wpdb->query('ROLLBACK');$after=[(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->users}"),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_stores'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_applications'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_email_verifications')];$wpdb=$production;if($after!==$before)throw new RuntimeException('consume_cleanup_failed');}
$mutation=new R1dbCaseRegistry();$mutation->add('CAA-03-MUTATION','forced wrong expectation',static fn()=>['owner'=>'other'],static fn($f)=>$f['owner'],static function($f,$o,$assert):void{$assert($o==='expected');},static fn()=>null);if($mutation->runAll(1)->failedIds()!==['CAA-03-MUTATION'])throw new RuntimeException('consume_anti_false_pass_failed');echo 'R1DB_CONSUME_ATTACH_CASE_IDS='.implode(',',$ids).PHP_EOL;echo 'R1DB_CONSUME_ATTACH_MATRIX='.count($ids).'/PASS'.PHP_EOL;
