<?php
declare(strict_types=1);
final readonly class R1dbHistoricalSnapshot{public function __construct(public int $count,public string $fingerprint){}}
final class R1dbHistoricalFingerprint
{
    public static function capture(wpdb $database,string $table,string $where='1=1'):R1dbHistoricalSnapshot{if(!preg_match('/\A[a-zA-Z0-9_]+\z/',$table)||!in_array($where,["meta_key='session_tokens'",'1=1',"public_id LIKE 'chk\\_%'"],true))throw new RuntimeException('r1db_fingerprint_surface_invalid');[$schema,$primary]=self::describe($database,$table);$order=implode(',',array_map(static fn(string $name):string=>"`{$name}`",$primary));$rows=$database->get_results("SELECT * FROM `{$table}` WHERE {$where} ORDER BY {$order}",ARRAY_A);if(!is_array($rows)||$database->last_error!=='')throw new RuntimeException('r1db_fingerprint_read_failed');return self::fromRows($rows,$schema,$primary,$table.'|'.$where);}
    /** @param list<array<string,mixed>> $rows */ public static function fromDatabaseRows(wpdb $database,string $table,array $rows,string $surface):R1dbHistoricalSnapshot{if(!preg_match('/\A[a-zA-Z0-9_]+\z/',$table)||$surface==='')throw new RuntimeException('r1db_fingerprint_surface_invalid');[$schema,$primary]=self::describe($database,$table);return self::fromRows($rows,$schema,$primary,$surface);}
    /** @param list<array<string,mixed>> $rows @param list<array<string,mixed>> $schema @param list<string> $primary */ public static function fromRows(array $rows,array $schema,array $primary,string $surface='fixture'):R1dbHistoricalSnapshot
    {if($surface===''||$schema===[]||$primary===[])throw new RuntimeException('r1db_fingerprint_definition_invalid');$byName=[];foreach($schema as $column){$name=(string)($column['name']??'');if($name===''||isset($byName[$name]))throw new RuntimeException('r1db_fingerprint_schema_invalid');$byName[$name]=$column;}foreach($primary as $name)if(!isset($byName[$name]))throw new RuntimeException('r1db_fingerprint_primary_key_missing');usort($schema,static fn(array $left,array $right):int=>(int)$left['ordinal']<=>(int)$right['ordinal']);$normalized=[];foreach($rows as $row){if(array_diff(array_keys($row),array_keys($byName))!==[]||array_diff(array_keys($byName),array_keys($row))!==[])throw new RuntimeException('r1db_fingerprint_row_shape_changed');$cells=[];foreach($schema as $column){$name=(string)$column['name'];$cells[]=['name'=>$name,'declared_sql_type'=>(string)$column['declared_sql_type'],'semantic_kind'=>(string)$column['semantic_kind'],'canonical_value'=>self::value($row[$name],$column)];}$normalized[]=$cells;}$positions=[];foreach($primary as $name)foreach($schema as $position=>$column)if($column['name']===$name){$positions[]=$position;break;}usort($normalized,static function(array $left,array $right)use($positions):int{foreach($positions as $position){$comparison=json_encode($left[$position],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES)<=>json_encode($right[$position],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);if($comparison!==0)return $comparison;}return json_encode($left,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES)<=>json_encode($right,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);});$authority=['surface'=>$surface,'schema'=>$schema,'primary_key'=>$primary,'rows'=>$normalized];$canonical=json_encode($authority,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);return new R1dbHistoricalSnapshot(count($rows),hash('sha256',$canonical));}
    /** @return array{list<array<string,mixed>>,list<string>} */ private static function describe(wpdb $database,string $table):array{$columns=$database->get_results("SHOW FULL COLUMNS FROM `{$table}`",ARRAY_A);if(!is_array($columns)||$columns===[]||$database->last_error!=='')throw new RuntimeException('r1db_fingerprint_schema_failed');$schema=[];foreach($columns as $offset=>$column){$declared=strtolower(trim((string)$column['Type']));preg_match('/\A([a-z]+)(?:\(([^)]*)\))?/',$declared,$match);$base=$match[1]??'';$size=$match[2]??null;$kind=self::kind($base);$schema[]=['ordinal'=>$offset+1,'name'=>(string)$column['Field'],'declared_sql_type'=>$declared,'base_type'=>$base,'length_precision'=>$size,'unsigned'=>str_contains($declared,' unsigned'),'binary'=>$kind==='binary','semantic_kind'=>$kind,'collation'=>$column['Collation']===null?null:(string)$column['Collation'],'nullable'=>(string)$column['Null']==='YES','key'=>(string)$column['Key'],'default'=>$column['Default']===null?['type'=>'null']:['type'=>'string','value'=>(string)$column['Default']],'extra'=>strtolower(trim((string)$column['Extra']))];}$indexes=$database->get_results("SHOW INDEX FROM `{$table}`",ARRAY_A);if(!is_array($indexes)||$database->last_error!=='')throw new RuntimeException('r1db_fingerprint_primary_key_missing');$primaryRows=array_values(array_filter($indexes,static fn(array $index):bool=>(string)($index['Key_name']??'')==='PRIMARY'));usort($primaryRows,static fn(array $left,array $right):int=>(int)$left['Seq_in_index']<=>(int)$right['Seq_in_index']);$primary=array_map(static fn(array $index):string=>(string)$index['Column_name'],$primaryRows);if($primary===[])throw new RuntimeException('r1db_fingerprint_primary_key_missing');return [$schema,$primary];}
    private static function kind(string $base):string{if($base==='bit')return 'boolean/bit';if(in_array($base,['tinyint','smallint','mediumint','int','integer','bigint','year'],true))return 'integer';if(in_array($base,['decimal','numeric'],true))return 'decimal';if(in_array($base,['float','double','real'],true))return 'float';if(in_array($base,['datetime','timestamp'],true))return 'datetime';if($base==='date')return 'date';if($base==='time')return 'time';if(str_contains($base,'blob')||str_contains($base,'binary'))return 'binary';if(str_contains($base,'text'))return 'text';return 'string';}
    private static function value(mixed $value,array $column):array{$type=(string)$column['declared_sql_type'];$kind=(string)$column['semantic_kind'];if($value===null)return ['declared_sql_type'=>$type,'semantic_kind'=>$kind,'value_type'=>'null'];$raw=(string)$value;if($kind==='binary'||$kind==='boolean/bit')$canonical=base64_encode($raw);elseif($kind==='integer'){$negative=str_starts_with($raw,'-');$digits=ltrim($raw,'+-0');$canonical=($negative&&$digits!==''?'-':'').($digits===''?'0':$digits);}elseif($kind==='float')$canonical=strtolower(str_replace('e+','e',$raw));else $canonical=$raw;return ['declared_sql_type'=>$type,'semantic_kind'=>$kind,'value_type'=>'value','value'=>$canonical];}
}
final class R1dbHistoricalBaseline{/** @param array<string,R1dbHistoricalSnapshot> $surfaces */public function __construct(private array $surfaces){}public function assertAll(array $current):void{if(array_keys($current)!==array_keys($this->surfaces))throw new RuntimeException('r1db_historical_surface_mismatch');foreach($this->surfaces as $name=>$expected){$actual=$current[$name];if($actual->count!==$expected->count||!hash_equals($expected->fingerprint,$actual->fingerprint))throw new RuntimeException('r1db_historical_fingerprint_changed_'.$name);}}}
final class R1dbComparisonLedger{private array $expected=[];private array $completed=[];public function __construct(array $expected){foreach($expected as $key){if($key===''||isset($this->expected[$key]))throw new RuntimeException('r1db_comparison_ledger_invalid');$this->expected[$key]=true;}}public function record(string $key):void{if(!isset($this->expected[$key])||isset($this->completed[$key]))throw new RuntimeException('r1db_comparison_ledger_unexpected_'.$key);$this->completed[$key]=true;}public function seal():int{if(array_keys($this->completed)!==array_keys($this->expected))throw new RuntimeException('r1db_comparison_ledger_incomplete');return count($this->completed);}}
