<?php
declare(strict_types=1);
define('WP_INSTALLING',true);
require_once dirname(__DIR__,5).'/wp-load.php';
require_once dirname(__DIR__,2).'/vendor/autoload.php';
use VeciAhorra\Database\Migrations\CreateStoreOnboardingActivationSessionFoundation;
use VeciAhorra\Database\Migrations\CreateStoreOnboardingRateLimitFoundation;
use VeciAhorra\Modules\Minimarket\Onboarding\ActivationSession\ActivationSessionException;
use VeciAhorra\Modules\Minimarket\Onboarding\ActivationSession\StoreOnboardingActivationSession;
use VeciAhorra\Modules\Minimarket\Onboarding\ActivationSession\StoreOnboardingActivationSessionRepository;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimitBucket;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimitDecision;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimitException;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimiter;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimitRequest;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimitSpecification;
function r1dca(bool$c,string$m):void{if(!$c)throw new RuntimeException($m);}
function r1dcaReject(callable$f,string$reason):void{$caught=null;try{$f();}catch(Throwable$e){$caught=$e;}r1dca($caught!==null&&$caught->getMessage()===$reason&&$caught->getPrevious()===null,'reject_'.$reason);}
final class R1dcaRegistry{private array$done=[];public function run(string$id,callable$f):void{r1dca(!isset($this->done[$id]),'duplicate_'.$id);$f();$this->done[$id]=true;}public function seal(int$n,string$label):void{r1dca(count($this->done)===$n,'count_'.$label);echo $label.'_IDS='.implode(',',array_keys($this->done)).PHP_EOL;echo $label.'='.count($this->done).'/PASS'.PHP_EOL;}}
$database=(string)getenv('VA_R1DCA_DATABASE');r1dca($database==='minimarket_r1dca_restore','database_guard');
global$wpdb;$wpdb=new wpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$wpdb->set_prefix('wp_');
$schema=new R1dcaRegistry();
$schema->run('SCH-01-SESSION-INSTALL',fn()=>(new CreateStoreOnboardingActivationSessionFoundation())->up());
$schema->run('SCH-02-RATE-INSTALL',fn()=>(new CreateStoreOnboardingRateLimitFoundation())->up());
$schema->run('SCH-03-SESSION-IDEMPOTENT',fn()=>(new CreateStoreOnboardingActivationSessionFoundation())->up());
$schema->run('SCH-04-RATE-IDEMPOTENT',fn()=>(new CreateStoreOnboardingRateLimitFoundation())->up());
$schema->run('SCH-05-SESSION-GUARD',fn()=>(new CreateStoreOnboardingActivationSessionFoundation())->assertStructure());
$schema->run('SCH-06-RATE-GUARD',fn()=>(new CreateStoreOnboardingRateLimitFoundation())->assertStructure());
foreach(['SCH-07-SESSION-COLUMNS'=>'SHOW COLUMNS FROM wp_va_store_onboarding_activation_sessions','SCH-08-RATE-COLUMNS'=>'SHOW COLUMNS FROM wp_va_store_onboarding_rate_limit_buckets','SCH-09-SESSION-INDEXES'=>'SHOW INDEX FROM wp_va_store_onboarding_activation_sessions','SCH-10-RATE-INDEXES'=>'SHOW INDEX FROM wp_va_store_onboarding_rate_limit_buckets']as$id=>$sql)$schema->run($id,fn()=>r1dca(is_array($wpdb->get_results($sql,ARRAY_A))&&$wpdb->last_error==='',$id));
$schema->run('SCH-11-ENGINE',fn()=>r1dca((int)$wpdb->get_var("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('wp_va_store_onboarding_activation_sessions','wp_va_store_onboarding_rate_limit_buckets') AND ENGINE='InnoDB'")===2,'engine'));
$schema->run('SCH-12-COLLATION',fn()=>r1dca((int)$wpdb->get_var("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('wp_va_store_onboarding_activation_sessions','wp_va_store_onboarding_rate_limit_buckets') AND TABLE_COLLATION='utf8mb4_unicode_520_ci'")===2,'collation'));
$schema->run('SCH-13-EMPTY-SESSIONS',fn()=>r1dca((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_activation_sessions')===0,'session_not_empty'));
$schema->run('SCH-14-EMPTY-RATE',fn()=>r1dca((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_rate_limit_buckets')===0,'rate_not_empty'));
$schema->run('SCH-15-NO-FK',fn()=>r1dca((int)$wpdb->get_var("SELECT COUNT(*) FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME LIKE 'wp_va_store_onboarding_%'")===0,'foreign_keys'));
$schema->run('SCH-16-NO-PREFIXED-INDEX',fn()=>r1dca((int)$wpdb->get_var("SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('wp_va_store_onboarding_activation_sessions','wp_va_store_onboarding_rate_limit_buckets') AND SUB_PART IS NOT NULL")===0,'prefixed_index'));
$schema->run('SCH-17-APPLICATIONS-PRESERVED',fn()=>r1dca((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_applications')===0,'apps'));
$schema->run('SCH-18-VERIFICATIONS-PRESERVED',fn()=>r1dca((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_email_verifications')===0,'vers'));
$schema->seal(18,'R1DCA_SCHEMA');
$base=['id'=>'1','session_hash'=>str_repeat("a\0",16),'application_id'=>'1','verification_id'=>'1','generation'=>'1','purpose'=>StoreOnboardingActivationSession::PURPOSE,'state'=>'active','expires_at'=>'2026-01-01 00:15:00','consumed_at'=>null,'invalidated_at'=>null,'failed_attempts'=>'0','last_attempt_at'=>null,'created_at'=>'2026-01-01 00:00:00','updated_at'=>'2026-01-01 00:00:00'];
$entity=new R1dcaRegistry();$entity->run('ENT-01-VALID',fn()=>r1dca(StoreOnboardingActivationSession::fromRow($base)->sessionHash===$base['session_hash'],'valid'));
$mutations=['ENT-02-ID'=>[['id'=>'0'],'activation_session_invalid_row'],'ENT-03-HASH'=>[['session_hash'=>'x'],'activation_session_invalid_row'],'ENT-04-APPLICATION'=>[['application_id'=>'0'],'activation_session_invalid_row'],'ENT-05-VERIFICATION'=>[['verification_id'=>'0'],'activation_session_invalid_row'],'ENT-06-GENERATION'=>[['generation'=>'0'],'activation_session_invalid_row'],'ENT-07-PURPOSE'=>[['purpose'=>'other'],'activation_session_invalid_purpose'],'ENT-08-STATE'=>[['state'=>'expired'],'activation_session_invalid_state'],'ENT-09-EXPIRY'=>[['expires_at'=>'2026-01-01 00:14:59'],'activation_session_invalid_timestamps'],'ENT-10-ATTEMPTS'=>[['failed_attempts'=>'6'],'activation_session_invalid_row'],'ENT-11-LAST-ATTEMPT'=>[['failed_attempts'=>'1'],'activation_session_invalid_attempts'],'ENT-12-CONSUMED'=>[['state'=>'consumed'],'activation_session_incoherent_state'],'ENT-13-INVALIDATED'=>[['state'=>'invalidated'],'activation_session_incoherent_state'],'ENT-14-TIMESTAMP'=>[['created_at'=>'bad'],'activation_session_invalid_timestamp'],'ENT-15-BOOL'=>[['id'=>true],'activation_session_invalid_row']];
foreach($mutations as$id=>[$change,$reason])$entity->run($id,function()use($base,$change,$reason){r1dcaReject(fn()=>StoreOnboardingActivationSession::fromRow(array_replace($base,$change)),$reason);});
$entity->run('ENT-16-EXTRA',function()use($base){$x=$base;$x['extra']=1;r1dcaReject(fn()=>StoreOnboardingActivationSession::fromRow($x),'activation_session_invalid_shape');});$entity->seal(16,'R1DCA_SESSION_ENTITY');
// Real reference fixture, removed before exit.
$now='2026-01-01 00:00:00';$wpdb->insert('wp_va_store_onboarding_applications',['public_id'=>'onb_r1dca_fixture','user_id'=>null,'account_email'=>'fixture@example.test','owner_rut_normalized'=>'12345678-5','status'=>'provisioning','idempotency_key_hash'=>hash('sha256','r1dca'),'terms_version'=>'R1C-LEGAL-2026-07-30-V1','terms_accepted_at'=>$now,'store_id'=>null,'failure_code'=>null,'attempt_count'=>0,'last_attempt_at'=>null,'created_at'=>$now,'updated_at'=>$now,'abandoned_at'=>null]);$aid=(int)$wpdb->insert_id;$wpdb->insert('wp_va_store_onboarding_email_verifications',['application_id'=>$aid,'purpose'=>'minimarket_account_activation','generation'=>1,'candidate_user_id'=>null,'attached_user_id'=>null,'email_binding_hash'=>str_repeat('e',32),'token_hash'=>str_repeat('t',32),'expires_at'=>'2026-01-02 00:00:00','consumed_at'=>null,'failed_attempts'=>0,'resend_count'=>0,'last_sent_at'=>'2026-01-01 00:00:01','delivery_state'=>'sent','delivery_attempt_count'=>1,'last_error_code'=>null,'created_at'=>$now,'updated_at'=>'2026-01-01 00:00:01']);$vid=(int)$wpdb->insert_id;
$repo=new StoreOnboardingActivationSessionRepository($wpdb);$sessions=new R1dcaRegistry();$hash1=str_repeat("s\0",16);$hash2=str_repeat("q\0",16);$s1=null;$s2=null;
$sessions->run('SES-01-CREATE',function()use($repo,$hash1,$aid,$vid,&$s1){$s1=$repo->create($hash1,$aid,$vid,1,'2026-01-01 00:01:00');r1dca($s1->expiresAt==='2026-01-01 00:16:00','ttl');});
$sessions->run('SES-02-FIND-ID',fn()=>r1dca($repo->findById($s1->id)?->id===$s1->id,'find_id'));
$sessions->run('SES-03-FIND-HASH',fn()=>r1dca($repo->findByHash($hash1)?->id===$s1->id,'find_hash'));
$sessions->run('SES-04-REPLAY',fn()=>r1dca($repo->create($hash1,$aid,$vid,1,'2026-01-01 00:01:00')->id===$s1->id,'replay'));
$sessions->run('SES-05-SECOND',function()use($repo,$hash2,$aid,$vid,&$s2){$s2=$repo->create($hash2,$aid,$vid,1,'2026-01-01 00:02:00');});
$sessions->run('SES-06-ATTEMPT-1',function()use($repo,&$s1){$s1=$repo->recordFailedAttempt($s1->id,$s1->updatedAt,'2026-01-01 00:03:00');r1dca($s1->failedAttempts===1,'attempt1');});
foreach(range(2,5)as$n)$sessions->run('SES-'.str_pad((string)(5+$n),2,'0',STR_PAD_LEFT).'-ATTEMPT-'.$n,function()use($repo,&$s1,$n){$s1=$repo->recordFailedAttempt($s1->id,$s1->updatedAt,'2026-01-01 00:0'.($n+2).':00');r1dca($s1->failedAttempts===$n,'attempt');});
$sessions->run('SES-11-SIXTH-REJECT',fn()=>r1dcaReject(fn()=>$repo->recordFailedAttempt($s1->id,$s1->updatedAt,'2026-01-01 00:08:00'),'activation_session_attempt_forbidden'));
$sessions->run('SES-12-CONSUME',function()use($repo,&$s2){$s2=$repo->consume($s2->id,$s2->updatedAt,'2026-01-01 00:09:00',true);r1dca($s2->state==='consumed','consume');});
$sessions->run('SES-13-OTHER-INVALIDATED',fn()=>r1dca($repo->findById($s1->id)?->state==='invalidated','other'));
$sessions->run('SES-14-CONSUME-REPLAY',fn()=>r1dca($repo->consume($s2->id,$s2->updatedAt,'2026-01-01 00:10:00',true)->state==='consumed','consume_replay'));
$sessions->run('SES-15-NO-CONFIRMATION',fn()=>r1dcaReject(fn()=>$repo->consume($s2->id,$s2->updatedAt,'2026-01-01 00:10:00',false),'activation_session_confirmation_required'));
$sessions->run('SES-16-HASH-CONFLICT',fn()=>r1dcaReject(fn()=>$repo->create($hash1,$aid,$vid,1,'2026-01-01 00:02:00'),'activation_session_conflict'));
$sessions->run('SES-17-NOT-FOUND',fn()=>r1dca($repo->findById(PHP_INT_MAX)===null,'missing'));
$sessions->run('SES-18-BAD-HASH',fn()=>r1dcaReject(fn()=>$repo->findByHash('x'),'activation_session_invalid_hash'));
$sessions->run('SES-19-EXPIRED-DERIVED',fn()=>r1dca($repo->findById($s2->id)?->isExpired('2026-01-02 00:00:00')===true,'expired'));
$sessions->run('SES-20-TERMINAL-ATTEMPT',fn()=>r1dcaReject(fn()=>$repo->recordFailedAttempt($s2->id,$s2->updatedAt,'2026-01-01 00:11:00'),'activation_session_attempt_forbidden'));
$sessions->run('SES-21-BAD-ID',fn()=>r1dcaReject(fn()=>$repo->findById(0),'activation_session_invalid_id'));
$sessions->run('SES-22-CLEANUP-LIMIT',fn()=>r1dcaReject(fn()=>$repo->cleanup('2026-02-01 00:00:00',0),'activation_session_cleanup_invalid'));
$sessions->run('SES-23-CLEANUP',fn()=>r1dca($repo->cleanup('2026-02-01 00:11:00',100)===2,'cleanup'));
$sessions->run('SES-24-EMPTY',fn()=>r1dca((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_activation_sessions')===0,'session_residual'));
$sessions->seal(24,'R1DCA_SESSION_REPOSITORY');
$rate=new DurableRateLimiter($wpdb);$rates=new R1dcaRegistry();$spec=fn(string$d,string$c)=>new DurableRateLimitSpecification(hash('sha256',$d.'|'.$c,true),$d,...DurableRateLimitSpecification::POLICIES[$d]);$get=$spec('get_token','a');
$rates->run('RATE-01-FIRST',fn()=>r1dca($rate->consume(new DurableRateLimitRequest([$get],'2026-01-01 00:00:00'))->allowed,'first'));
foreach(range(2,10)as$i)$rates->run('RATE-'.str_pad((string)$i,2,'0',STR_PAD_LEFT).'-HIT',fn()=>r1dca($rate->consume(new DurableRateLimitRequest([$get],'2026-01-01 00:00:0'.min($i,9)))->allowed,'hit'));
$rates->run('RATE-11-BLOCK',function()use($rate,$get){$d=$rate->consume(new DurableRateLimitRequest([$get],'2026-01-01 00:00:10'));r1dca(!$d->allowed&&$d->retryAfter===590,'blocked');});
$rates->run('RATE-12-NO-INCREMENT',fn()=>r1dca((int)$wpdb->get_var("SELECT hit_count FROM wp_va_store_onboarding_rate_limit_buckets WHERE domain='get_token'")===10,'no_increment'));
$rates->run('RATE-13-BEFORE-EXPIRY',fn()=>r1dca(!$rate->consume(new DurableRateLimitRequest([$get],'2026-01-01 00:09:59'))->allowed,'before'));
$rates->run('RATE-14-ROLLOVER-EXACT',fn()=>r1dca($rate->consume(new DurableRateLimitRequest([$get],'2026-01-01 00:10:00'))->allowed,'rollover'));
$rates->run('RATE-15-AFTER',fn()=>r1dca($rate->consume(new DurableRateLimitRequest([$get],'2026-01-01 00:10:01'))->allowed,'after'));
$multiA=$spec('post_network','n');$multiB=$spec('post_session','s');
$rates->run('RATE-16-MULTI',fn()=>r1dca($rate->consume(new DurableRateLimitRequest([$multiB,$multiA],'2026-01-01 01:00:00'))->allowed,'multi'));
$rates->run('RATE-17-DUP-DOMAIN',fn()=>r1dcaReject(fn()=>new DurableRateLimitRequest([$multiA,$spec('post_network','other')],'2026-01-01 01:00:00'),'rate_limit_request_duplicate'));
$rates->run('RATE-18-DUP-HASH',fn()=>r1dcaReject(fn()=>new DurableRateLimitRequest([$multiA,new DurableRateLimitSpecification($multiA->bucketHash,'post_session',5,900)],'2026-01-01 01:00:00'),'rate_limit_request_duplicate'));
$rates->run('RATE-19-BAD-DOMAIN',fn()=>r1dcaReject(fn()=>new DurableRateLimitSpecification(str_repeat('a',32),'bad',1,600),'rate_limit_specification_invalid'));
$rates->run('RATE-20-BAD-WINDOW',fn()=>r1dcaReject(fn()=>new DurableRateLimitSpecification(str_repeat('a',32),'get_token',10,601),'rate_limit_specification_invalid'));
$rates->run('RATE-21-BAD-HASH',fn()=>r1dcaReject(fn()=>new DurableRateLimitSpecification('x','get_token',10,600),'rate_limit_specification_invalid'));
$bucket=['id'=>'1','bucket_hash'=>str_repeat('b',32),'domain'=>'get_token','window_started_at'=>'2026-01-01 00:00:00','window_seconds'=>'600','hit_count'=>'1','expires_at'=>'2026-01-01 00:10:00','created_at'=>'2026-01-01 00:00:00','updated_at'=>'2026-01-01 00:00:00'];
$rates->run('RATE-22-BUCKET-VALID',fn()=>r1dca(DurableRateLimitBucket::fromRow($bucket)->hitCount===1,'bucket'));
foreach(['RATE-23-ZERO'=>[['hit_count'=>'0'],'rate_limit_bucket_corrupt'],'RATE-24-OVER'=>[['hit_count'=>'11'],'rate_limit_bucket_corrupt'],'RATE-25-DOMAIN'=>[['domain'=>'bad'],'rate_limit_bucket_invalid'],'RATE-26-WINDOW'=>[['window_seconds'=>'900'],'rate_limit_bucket_corrupt'],'RATE-27-EXPIRY'=>[['expires_at'=>'2026-01-01 00:09:59'],'rate_limit_bucket_corrupt'],'RATE-28-START'=>[['window_started_at'=>'2026-01-01 00:10:00'],'rate_limit_bucket_corrupt'],'RATE-29-UPDATED'=>[['updated_at'=>'2025-01-01 00:00:00'],'rate_limit_bucket_corrupt'],'RATE-30-ID'=>[['id'=>'0'],'rate_limit_bucket_corrupt'],'RATE-31-HASH'=>[['bucket_hash'=>'x'],'rate_limit_bucket_corrupt']]as$id=>[$change,$reason])$rates->run($id,fn()=>r1dcaReject(fn()=>DurableRateLimitBucket::fromRow(array_replace($bucket,$change)),$reason));
$rates->run('RATE-32-EXTRA',function()use($bucket){$x=$bucket;$x['x']=1;r1dcaReject(fn()=>DurableRateLimitBucket::fromRow($x),'rate_limit_bucket_corrupt');});
$cool=$spec('resend_cooldown_application','app');$rates->run('RATE-33-COOLDOWN-FIRST',fn()=>r1dca($rate->consume(new DurableRateLimitRequest([$cool],'2026-01-01 02:00:00'))->allowed,'cool'));
$rates->run('RATE-34-COOLDOWN-BLOCK',fn()=>r1dca(!$rate->consume(new DurableRateLimitRequest([$cool],'2026-01-01 02:00:01'))->allowed,'coolblock'));
$rates->run('RATE-35-RETRY-MIN',function()use($rate,$cool){$d=$rate->consume(new DurableRateLimitRequest([$cool],'2026-01-01 02:09:59'));r1dca($d->retryAfter===1,'retrymin');});
$rates->run('RATE-36-ROLLOVER',fn()=>r1dca($rate->consume(new DurableRateLimitRequest([$cool],'2026-01-01 02:10:00'))->allowed,'coolroll'));
$rates->run('RATE-37-DECISION-UNCERTAIN',fn()=>r1dca(DurableRateLimitDecision::uncertain()->outcome==='uncertain','uncertain'));
$rates->run('RATE-38-CLEANUP-LIMIT',fn()=>r1dcaReject(fn()=>$rate->cleanup('2026-01-03 00:00:00',0),'rate_limit_cleanup_invalid'));
$rates->run('RATE-39-CLEANUP-BEFORE',fn()=>r1dca($rate->cleanup('2026-01-01 02:20:00',100)===0,'cleanup_before'));
$rates->run('RATE-40-CLEANUP-AFTER',fn()=>r1dca($rate->cleanup('2026-01-03 00:00:00',100)>0,'cleanup_after'));
$rates->run('RATE-41-PRIVACY',fn()=>r1dca(!str_contains(print_r(DurableRateLimitDecision::blocked(1),true),'@'),'privacy'));
$rates->run('RATE-42-RESIDUAL-CLEANUP',function()use($wpdb){$wpdb->query('DELETE FROM wp_va_store_onboarding_rate_limit_buckets');r1dca((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_rate_limit_buckets')===0,'rate_residual');});
$rates->seal(42,'R1DCA_RATE_LIMIT');
$wpdb->delete('wp_va_store_onboarding_email_verifications',['id'=>$vid]);$wpdb->delete('wp_va_store_onboarding_applications',['id'=>$aid]);
r1dca((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_applications')===0&&(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_email_verifications')===0,'fixture_residual');
$wpdb->set_prefix('r1x_');(new CreateStoreOnboardingActivationSessionFoundation())->up();(new CreateStoreOnboardingRateLimitFoundation())->up();
r1dca($wpdb->get_var("SHOW TABLES LIKE 'r1x_va_store_onboarding_activation_sessions'")==='r1x_va_store_onboarding_activation_sessions','alternate_prefix_session');
r1dca($wpdb->get_var("SHOW TABLES LIKE 'r1x_va_store_onboarding_rate_limit_buckets'")==='r1x_va_store_onboarding_rate_limit_buckets','alternate_prefix_rate');
$wpdb->query('DROP TABLE r1x_va_store_onboarding_activation_sessions');$wpdb->query('DROP TABLE r1x_va_store_onboarding_rate_limit_buckets');$wpdb->set_prefix('wp_');
echo "R1DCA_ALTERNATE_PREFIX=2/PASS\n";
r1dca((int)$wpdb->get_var("SELECT COUNT(*) FROM information_schema.PROCESSLIST WHERE DB='{$database}' AND COMMAND<>'Sleep'")<=1,'locks_residual');
echo "R1DCA_FIXTURES_RESIDUAL=0/PASS\nR1DCA_FOUNDATION=100/PASS\n";
