<?php
declare(strict_types=1);
define('WP_INSTALLING',true);require_once dirname(__DIR__,5).'/wp-load.php';require_once dirname(__DIR__,2).'/vendor/autoload.php';require_once __DIR__.'/minimarket-onboarding-r1d-c-a-barrier.php';
use VeciAhorra\Modules\Minimarket\Onboarding\ActivationSession\StoreOnboardingActivationSessionRepository;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimiter;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimitRequest;
use VeciAhorra\Modules\Minimarket\Onboarding\RateLimit\DurableRateLimitSpecification;
final class ConcurrencyFaultWpdb extends wpdb{public string$commitMode='';public ?R1dcaBarrier$barrier=null;public string$worker='';public array$acquired=[],$released=[];public function query($query){if(strcasecmp(trim((string)$query),'COMMIT')===0&&$this->commitMode!==''){$mode=$this->commitMode;if($mode==='not'){parent::query('ROLLBACK');return false;}parent::query('COMMIT');if($mode==='loss'){cw($this->barrier instanceof R1dcaBarrier,'loss_barrier');$id=(int)parent::get_var('SELECT CONNECTION_ID()');$this->barrier->publish('kill_target',$this->worker,['connection_id'=>$id]);$this->barrier->await('kill_release','coordinator');}return false;}return parent::query($query);}public function get_var($query=null,$x=0,$y=0){$sql=(string)$query;if(str_contains($sql,'GET_LOCK(')&&preg_match("/GET_LOCK\\('([^']+)'/",$sql,$m))$this->acquired[]=$m[1];if(str_contains($sql,'RELEASE_LOCK(')&&preg_match("/RELEASE_LOCK\\('([^']+)'/",$sql,$m))$this->released[]=$m[1];return parent::get_var($query,$x,$y);}}
final class ReleaseFaultWpdb extends wpdb{public array$acquireOrder=[],$releaseOrder=[],$releaseResults=[];public function get_var($query=null,$x=0,$y=0){$sql=(string)$query;if(str_contains($sql,'GET_LOCK(')&&preg_match("/GET_LOCK\\('([^']+)'/",$sql,$m))$this->acquireOrder[]=$m[1];if(str_contains($sql,'RELEASE_LOCK(')){$this->releaseOrder[]=$sql;$result=count($this->releaseOrder)===1?0:1;$this->releaseResults[]=$result;return$result;}return parent::get_var($query,$x,$y);}}
function cw(bool$c,string$r):void{if(!$c)throw new RuntimeException($r);}function closedWorker(Throwable$e):string{return$e->getPrevious()===null?$e->getMessage():'worker_previous_exposed';}
$configPath=$argv[1]??'';$raw=is_file($configPath)?file_get_contents($configPath):false;cw(is_string($raw)&&strlen($raw)<=16384,'worker_config');$c=json_decode($raw,true,32,JSON_THROW_ON_ERROR);cw(($c['database']??'')==='minimarket_r1dca_restore','database_guard');$worker=(string)$c['worker'];$barrier=new R1dcaBarrier((string)$c['directory'],(string)$c['execution_id'],(string)$c['case_id'],(string)$c['challenge']);$db=new ConcurrencyFaultWpdb(DB_USER,DB_PASSWORD,(string)$c['database'],DB_HOST);$db->set_prefix('wp_');global$wpdb;$wpdb=$db;$reconciler=null;$started=microtime(true);$barrier->publish('worker_ready',$worker,['connection_id'=>(int)$db->get_var('SELECT CONNECTION_ID()')]);$barrier->await('start','coordinator');$barrier->publish('target_reached',$worker);$barrier->await('coordinator_release','coordinator');$outcome='';$error=null;
try{$operation=(string)$c['operation'];if(str_starts_with($operation,'rate_consume')){$specs=[];foreach($c['specs']as$s)$specs[]=new DurableRateLimitSpecification(base64_decode($s['hash'],true),(string)$s['domain'],(int)$s['limit'],(int)$s['window']);$decision=(new DurableRateLimiter($db))->consume(new DurableRateLimitRequest($specs,(string)$c['now']));$outcome=$decision->outcome;}
elseif($operation==='rate_cleanup'){$db->commitMode=(string)($c['commit_mode']??'');$db->barrier=$barrier;$db->worker=$worker;$factory=null;if(($c['release_fault']??false)===true)$factory=function($database)use(&$reconciler){$reconciler=new ReleaseFaultWpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$reconciler->set_prefix('wp_');return$reconciler;};$outcome='cleanup_'.(new DurableRateLimiter($db,$factory))->cleanup((string)$c['now'],100);}
elseif(in_array($operation,['session_consume','session_invalidate','session_cleanup'],true)){$factory=null;if($operation==='session_cleanup'){$db->commitMode=(string)($c['commit_mode']??'');$db->barrier=$barrier;$db->worker=$worker;if(($c['release_fault']??false)===true)$factory=function($database)use(&$reconciler){$reconciler=new ReleaseFaultWpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$reconciler->set_prefix('wp_');return$reconciler;};}$repo=new StoreOnboardingActivationSessionRepository($db,$factory);if($operation==='session_consume')$outcome=$repo->consume((int)$c['session_id'],(string)$c['expected_updated_at'],(string)$c['now'],true)->state;elseif($operation==='session_invalidate')$outcome=$repo->invalidate((int)$c['session_id'],(string)$c['expected_updated_at'],(string)$c['now'])->state;else$outcome='cleanup_'.$repo->cleanup((string)$c['now'],100);}
else throw new RuntimeException('worker_operation_invalid');}catch(Throwable$e){$error=closedWorker($e);$outcome='error';}
$duration=(int)round((microtime(true)-$started)*1000);$reconciledAcquired=[];$reconciledReleased=[];$globalOrder=true;if($reconciler instanceof ReleaseFaultWpdb){$sorted=$reconciler->acquireOrder;sort($sorted,SORT_STRING);$globalOrder=$sorted===$reconciler->acquireOrder;foreach(array_keys($reconciler->acquireOrder)as$index)$reconciledAcquired[]='lock_'.($index+1);foreach($reconciler->releaseOrder as$sql){preg_match("/RELEASE_LOCK\\('([^']+)'/",$sql,$match);$index=array_search($match[1]??null,$reconciler->acquireOrder,true);$reconciledReleased[]=$index===false?'lock_unknown':'lock_'.($index+1);}}$locks=['acquired'=>$db->acquired,'released'=>$db->released,'reconciled_acquired'=>$reconciledAcquired,'reconciled_releases'=>$reconciledReleased,'release_results'=>$reconciler instanceof ReleaseFaultWpdb?$reconciler->releaseResults:[],'global_order'=>$globalOrder];$barrier->publish('operation_finished',$worker,['outcome'=>$outcome,'error'=>$error,'duration_ms'=>$duration]);echo json_encode(['worker'=>$worker,'pid'=>getmypid(),'outcome'=>$outcome,'error'=>$error,'duration_ms'=>$duration,'locks'=>$locks],JSON_THROW_ON_ERROR),PHP_EOL;
