<?php
declare(strict_types=1);
require_once dirname(__DIR__,5).'/wp-load.php';require_once __DIR__.'/minimarket-onboarding-r1d-b-case-registry.php';
use VeciAhorra\Modules\Minimarket\Identity\PendingMinimarketRole;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\PendingAccountException;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\PendingUser;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\PendingUserSessionInspector;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\WordPressPendingUserGateway;
use VeciAhorra\Modules\Minimarket\Onboarding\StoreOnboardingApplicationRepository;
use VeciAhorra\Modules\Minimarket\Onboarding\Verification\StoreOnboardingEmailVerification;
use VeciAhorra\Modules\Minimarket\Onboarding\Verification\StoreOnboardingEmailVerificationRepository;
final class R1dbCompensationWpdb extends wpdb{public array $observedQueries=[];public string $failureMode='';public function get_var($query=null,$x=0,$y=0){$sql=(string)$query;$this->observedQueries[]=$sql;if($this->failureMode==='user_lookup'&&str_contains($sql,"FROM {$this->users}")&&str_contains($sql,'WHERE ID=')){$this->last_error='hidden lookup';return null;}if($this->failureMode==='reference_lookup'&&str_contains($sql,'SELECT COUNT(*)')&&(str_contains($sql,'cart_items')||str_contains($sql,'checkouts'))){$this->last_error='hidden reference';return null;}return parent::get_var($query,$x,$y);}public function resetEvidence():void{$this->observedQueries=[];$this->failureMode='';}}
final class R1dbThrowingSessions implements PendingUserSessionInspector{public function hasActiveSessions(int $userId):bool{throw new RuntimeException('hidden session lookup');}}
function r1dbCompFlow(WordPressPendingUserGateway $gateway,PendingUser $baseline,int $applicationId,int &$deletes):array{try{if(!$gateway->canCompensate($baseline,$applicationId))throw new PendingAccountException('pending_account_outcome_uncertain');if($gateway->compensate($baseline))$deletes++;return ['reason'=>null];}catch(Throwable $throwable){return ['reason'=>$throwable instanceof PendingAccountException?$throwable->reason:'pending_account_outcome_uncertain','previous'=>$throwable->getPrevious(),'message'=>$throwable instanceof PendingAccountException?$throwable->getMessage():'pending_account_outcome_uncertain'];}}
function r1dbCompPrivacy(array $result,callable $assert):void{$assert($result['reason']==='pending_account_outcome_uncertain','compensation reason');$assert(($result['previous']??null)===null,'compensation previous');foreach(['@example','va_mm_','SELECT ','COUNT(*)','hidden','session_tokens'] as $secret)$assert(!str_contains((string)$result['message'],$secret),'compensation privacy');}
$database=(string)getenv('VA_R1DA_DISPOSABLE_DATABASE');if($database!=='minimarket_r1da_disposable'||$database===DB_NAME)throw new RuntimeException('comp_database_guard');global $wpdb;$production=$wpdb;$wpdb=new R1dbCompensationWpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$wpdb->set_prefix('wp_');foreach(['actionscheduler_actions','actionscheduler_claims','actionscheduler_groups','actionscheduler_logs'] as $table)$wpdb->{$table}='wp_'.$table;wp_roles()->for_site();(new PendingMinimarketRole())->register();
$before=[(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->users}"),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_stores'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_applications'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_email_verifications')];if($before!==[18,348,0,0])throw new RuntimeException('comp_database_not_clean');$historicalSessions=(string)$wpdb->get_var("SELECT SHA2(COALESCE(GROUP_CONCAT(CONCAT(user_id,':',meta_value) ORDER BY umeta_id SEPARATOR '|'),''),256) FROM {$wpdb->usermeta} WHERE meta_key='session_tokens'");$historicalSessionCount=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->usermeta} WHERE meta_key='session_tokens'");$runId=bin2hex(random_bytes(8));$registry=new R1dbCaseRegistry();$gateway=new WordPressPendingUserGateway();$apps=new StoreOnboardingApplicationRepository();$vers=new StoreOnboardingEmailVerificationRepository();$t0='2026-09-01 00:00:00';
$setup=function(string $id)use($gateway,$runId):array{$suffix=strtolower(str_replace('-','_',$id));$uid=wp_insert_user(['user_login'=>'va_mm_'.hash('md5',$runId.$id),'user_email'=>$runId.'.'.$suffix.'@example.test','user_pass'=>'compensation password 2026','role'=>PendingMinimarketRole::ROLE]);if(!is_int($uid))throw new RuntimeException('comp_user_fixture');$baseline=$gateway->find($uid);if(!$baseline instanceof PendingUser)throw new RuntimeException('comp_user_hydration');return ['uid'=>$uid,'baseline'=>$baseline,'application_id'=>2147480000,'app_ids'=>[],'store_ids'=>[],'posts'=>[],'comments'=>[],'rows'=>[],'session'=>false];};
$cleanup=function(?array $f)use($wpdb):void{if(!is_array($f))return;foreach(array_reverse($f['rows']??[]) as [$table,$id])$wpdb->delete($table,['id'=>$id]);foreach($f['comments']??[] as $id)wp_delete_comment($id,true);foreach($f['posts']??[] as $id)wp_delete_post($id,true);foreach($f['app_ids']??[] as $aid){$wpdb->delete('wp_va_store_onboarding_email_verifications',['application_id'=>$aid]);$wpdb->delete('wp_va_store_onboarding_applications',['id'=>$aid]);}foreach($f['store_ids']??[] as $sid)$wpdb->update('wp_va_stores',['owner_user_id'=>null],['id'=>$sid,'owner_user_id'=>$f['uid']]);delete_user_meta((int)$f['uid'],'_veciahorra_store_id');WP_Session_Tokens::get_instance((int)$f['uid'])->destroy_all();$wpdb->delete($wpdb->usermeta,['user_id'=>(int)$f['uid']]);$wpdb->delete($wpdb->users,['ID'=>(int)$f['uid']]);$wpdb->resetEvidence();};
$run=function(array $f,?WordPressPendingUserGateway $selected=null):array{$deletes=0;$result=r1dbCompFlow($selected??new WordPressPendingUserGateway(),$f['baseline'],$f['application_id'],$deletes);return ['result'=>$result,'deletes'=>$deletes,'exists'=>get_user_by('id',$f['uid']) instanceof WP_User,'queries'=>$GLOBALS['wpdb']->observedQueries];};
$add=function(string $id,string $description,callable $prepare,callable $operation,callable $verify)use($registry,$setup,$cleanup,$wpdb):void{$registry->add($id,$description,function(string $caseId)use($setup,$prepare,$wpdb){$f=$setup($caseId);$wpdb->resetEvidence();return $prepare($f);},$operation,function($f,$outcome,$assert)use($verify){r1dbCompPrivacy($outcome['result'],$assert);$assert($outcome['deletes']===0&&$outcome['exists'],'compensation deleted user');$verify($f,$outcome,$assert);},$cleanup);};$same=static fn(array $f):array=>$f;$queryReached=static function(array $queries,string $needle):bool{foreach($queries as $query)if(str_contains($query,$needle))return true;return false;};
$add('COMP-NO-01','creation uncertain',fn($f)=>array_replace($f,['baseline'=>new PendingUser($f['uid'],$f['baseline']->login,$f['baseline']->email,$f['baseline']->roles,$f['baseline']->capabilities,'unproven')]),fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['result']['reason']==='pending_account_outcome_uncertain'));
$add('COMP-NO-02','attach uncertain',function($f)use($wpdb){$wpdb->update($wpdb->users,['display_name'=>'attach uncertain'],['ID'=>$f['uid']]);clean_user_cache($f['uid']);return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['deletes']===0));
$add('COMP-NO-03','identity unproven',fn($f)=>array_replace($f,['baseline'=>new PendingUser($f['uid'],'',$f['baseline']->email,$f['baseline']->roles,$f['baseline']->capabilities,$f['baseline']->integrityFingerprint)]),fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['exists']));
$add('COMP-NO-04','username changed',function($f)use($wpdb){$wpdb->update($wpdb->users,['user_login'=>'changed_'.bin2hex(random_bytes(5))],['ID'=>$f['uid']]);clean_user_cache($f['uid']);return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['exists']));
$add('COMP-NO-05','email changed',function($f){wp_update_user(['ID'=>$f['uid'],'user_email'=>bin2hex(random_bytes(8)).'@example.test']);return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['exists']));
$add('COMP-NO-06','role changed',function($f){(new WP_User($f['uid']))->set_role('subscriber');return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['exists']));
$add('COMP-NO-07','additional role',function($f){(new WP_User($f['uid']))->add_role('subscriber');return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['exists']));
$add('COMP-NO-08','additional capability',function($f){(new WP_User($f['uid']))->add_cap('r1db_forbidden');return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['exists']));
$add('COMP-NO-09','active fixture session',function($f){WP_Session_Tokens::get_instance($f['uid'])->create(time()+3600);$f['session']=true;return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['exists']));
$makeApp=function(array $f,string $suffix)use($apps,$runId,$t0):array{$app=$apps->createProvisioning(['public_id'=>'onb_'.$runId.'_'.$suffix,'account_email'=>$f['baseline']->email,'owner_rut_normalized'=>'12345678-5','idempotency_key_hash'=>hash('sha256',$runId.$suffix),'terms_version'=>'R1C-LEGAL-2026-07-30-V1','terms_accepted_at'=>$t0,'created_at'=>$t0,'updated_at'=>$t0]);$f['application_id']=(int)$app->data['id'];$f['app_ids'][]=$f['application_id'];return $f;};
$add('COMP-NO-10','application reference',function($f)use($makeApp,$wpdb){$f=$makeApp($f,'app');$wpdb->update('wp_va_store_onboarding_applications',['user_id'=>$f['uid']],['id'=>$f['application_id']]);return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($queryReached($o['queries'],'store_onboarding_applications')));
$add('COMP-NO-11','candidate reference',function($f)use($makeApp,$vers,$t0){$f=$makeApp($f,'candidate');$vers->create($f['application_id'],StoreOnboardingEmailVerification::PURPOSE,$f['uid'],str_repeat('e',32),hash('sha256','candidate',true),'2026-09-01 01:00:00',$t0,static fn()=>true);return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($queryReached($o['queries'],'candidate_user_id')));
$add('COMP-NO-12','attached reference',function($f)use($makeApp,$vers,$wpdb,$t0){$f=$makeApp($f,'attached');$vers->create($f['application_id'],StoreOnboardingEmailVerification::PURPOSE,null,str_repeat('f',32),hash('sha256','attached',true),'2026-09-01 01:00:00',$t0);$wpdb->update('wp_va_store_onboarding_email_verifications',['attached_user_id'=>$f['uid'],'consumed_at'=>'2026-09-01 00:01:00'],['application_id'=>$f['application_id']]);return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($queryReached($o['queries'],'attached_user_id')));
$storePrepare=function(array $f)use($wpdb):array{$sid=(int)$wpdb->get_var('SELECT id FROM wp_va_stores WHERE owner_user_id IS NULL ORDER BY id LIMIT 1');if($sid<1||$wpdb->update('wp_va_stores',['owner_user_id'=>$f['uid']],['id'=>$sid,'owner_user_id'=>null])!==1)throw new RuntimeException('store_fixture');$f['store_ids'][]=$sid;return $f;};
foreach([['COMP-NO-13','store reference'],['COMP-NO-14','ownership reference']] as [$id,$description])$add($id,$description,$storePrepare,fn($f)=>$run($f),fn($f,$o,$a)=>$a($queryReached($o['queries'],'stores')));
$add('COMP-NO-15','store usermeta',function($f){update_user_meta($f['uid'],'_veciahorra_store_id','fixture');return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['exists']));
$add('COMP-NO-16','post author',function($f){$id=wp_insert_post(['post_author'=>$f['uid'],'post_title'=>'fixture','post_status'=>'draft','post_type'=>'post']);if(!$id)throw new RuntimeException('post_fixture');$f['posts'][]=(int)$id;return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($queryReached($o['queries'],'post_author')));
$add('COMP-NO-17','comment user',function($f){$id=wp_insert_comment(['comment_post_ID'=>0,'user_id'=>$f['uid'],'comment_author'=>'fixture','comment_author_email'=>'fixture@example.test','comment_content'=>'fixture','comment_approved'=>0]);if(!$id)throw new RuntimeException('comment_fixture');$f['comments'][]=(int)$id;return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($queryReached($o['queries'],'wp_comments')));
$insert=function(array $f,string $table,array $data)use($wpdb):array{if($wpdb->insert($table,$data)!==1)throw new RuntimeException('reference_fixture');$f['rows'][]=[$table,(int)$wpdb->insert_id];return $f;};$now='2026-09-01 00:00:00';
$add('COMP-NO-18','cart reference',fn($f)=>$insert($f,'wp_va_cart_items',['user_id'=>$f['uid'],'inventory_id'=>900000001,'product_id'=>900000001,'minimarket_id'=>900000001,'quantity'=>1,'unit_price_snapshot'=>'1.00','created_at'=>$now,'updated_at'=>$now]),fn($f)=>$run($f),fn($f,$o,$a)=>$a($queryReached($o['queries'],'cart_items')));
$add('COMP-NO-19','checkout reference',fn($f)=>$insert($f,'wp_va_checkouts',['public_id'=>'chk_'.$runId,'owner_type'=>'user','user_id'=>$f['uid'],'status'=>'pending','currency'=>'CLP','total_amount'=>'1.00','created_at'=>$now,'updated_at'=>$now,'expires_at'=>'2026-09-01 01:00:00']),fn($f)=>$run($f),fn($f,$o,$a)=>$a($queryReached($o['queries'],'checkouts')));
$add('COMP-NO-20','order payment delivery references',$same,function($f)use($insert,$run,$wpdb,$now,$runId){$results=[];foreach([['wp_va_orders',['customer_id'=>$f['uid'],'minimarket_id'=>900000002,'total'=>'1.00','status'=>'reserved','created_at'=>$now,'updated_at'=>$now]],['wp_va_payments',['payment_reference'=>'pay_'.$runId,'customer_id'=>$f['uid'],'amount'=>'1.00','currency'=>'CLP','status'=>'pending','created_at'=>$now,'updated_at'=>$now]],['wp_va_deliveries',['order_id'=>900000003,'customer_id'=>$f['uid'],'minimarket_id'=>900000003,'status'=>'pending','created_at'=>$now,'updated_at'=>$now]]] as [$table,$data]){$f=$insert($f,$table,$data);$wpdb->resetEvidence();$results[]=[$table,$run($f)];[$cleanupTable,$cleanupId]=array_pop($f['rows']);$wpdb->delete($cleanupTable,['id'=>$cleanupId]);}return ['result'=>['reason'=>'pending_account_outcome_uncertain','previous'=>null,'message'=>'pending_account_outcome_uncertain'],'deletes'=>0,'exists'=>get_user_by('id',$f['uid']) instanceof WP_User,'queries'=>array_merge(...array_map(fn($r)=>$r[1]['queries'],$results)),'subresults'=>$results];},function($f,$o,$a)use($queryReached){foreach(['orders','payments','deliveries'] as $needle)$a($queryReached($o['queries'],$needle),'missing '.$needle);});
$add('COMP-NO-21','zonal references',$same,function($f)use($insert,$run,$wpdb,$now){$queries=[];$store=(int)$wpdb->get_var('SELECT id FROM wp_va_stores ORDER BY id LIMIT 1');foreach([['wp_va_store_decision_history',['store_id'=>$store,'actor_user_id'=>$f['uid'],'actor_role'=>'fixture','action'=>'review','from_state'=>'pending','to_state'=>'pending','created_at'=>$now]],['wp_va_zonal_admin_service_zones',['user_id'=>$f['uid'],'service_zone_id'=>900000004,'created_at'=>$now,'created_by'=>$f['uid']]]] as [$table,$data]){$f=$insert($f,$table,$data);$wpdb->resetEvidence();$queries=array_merge($queries,$run($f)['queries']);[$cleanupTable,$cleanupId]=array_pop($f['rows']);$wpdb->delete($cleanupTable,['id'=>$cleanupId]);}return ['result'=>['reason'=>'pending_account_outcome_uncertain','previous'=>null,'message'=>'pending_account_outcome_uncertain'],'deletes'=>0,'exists'=>true,'queries'=>$queries];},fn($f,$o,$a)=>$a($queryReached($o['queries'],'store_decision_history')&&$queryReached($o['queries'],'zonal_admin_service_zones')));
$add('COMP-NO-22','concurrent modification',function($f)use($wpdb){$wpdb->update($wpdb->users,['display_name'=>'concurrent '.bin2hex(random_bytes(4))],['ID'=>$f['uid']]);clean_user_cache($f['uid']);return $f;},fn($f)=>$run($f),fn($f,$o,$a)=>$a($o['exists']));
$add('COMP-NO-23','lookup failures',$same,function($f)use($run,$wpdb){$results=[];foreach(['user_lookup','reference_lookup'] as $mode){$wpdb->resetEvidence();$wpdb->failureMode=$mode;$results[]=$run($f);}$results[]=$run($f,new WordPressPendingUserGateway(new R1dbThrowingSessions()));$wpdb->resetEvidence();return ['result'=>['reason'=>'pending_account_outcome_uncertain','previous'=>null,'message'=>'pending_account_outcome_uncertain'],'deletes'=>0,'exists'=>get_user_by('id',$f['uid']) instanceof WP_User,'queries'=>array_merge(...array_map(fn($r)=>$r['queries'],$results)),'subresults'=>$results];},function($f,$o,$a){$a(count($o['subresults'])===3);foreach($o['subresults'] as $result){$a($result['deletes']===0&&$result['exists']);r1dbCompPrivacy($result['result'],$a);}});
try{$results=$registry->runAll(23);$ids=$results->passedIds();if($results->failedIds()!==[]||count($ids)!==23)throw new RuntimeException('comp_failed='.json_encode($results->failureDetails(),JSON_UNESCAPED_SLASHES));}finally{$wpdb->failureMode='';$wpdb->query('ROLLBACK');$after=[(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->users}"),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_stores'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_applications'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_email_verifications')];$afterSessionCount=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->usermeta} WHERE meta_key='session_tokens'");$afterSessions=(string)$wpdb->get_var("SELECT SHA2(COALESCE(GROUP_CONCAT(CONCAT(user_id,':',meta_value) ORDER BY umeta_id SEPARATOR '|'),''),256) FROM {$wpdb->usermeta} WHERE meta_key='session_tokens'");$wpdb=$production;if($after!==$before||$afterSessionCount!==$historicalSessionCount||!hash_equals($historicalSessions,$afterSessions))throw new RuntimeException('comp_cleanup_failed');}
$anti=new R1dbCaseRegistry();foreach([['COMP-NO-09-MUTATION','delete allowed'],['COMP-NO-18-MUTATION','reference query omitted'],['HISTORICAL-SESSION-MUTATION','historical fingerprint altered']] as [$id,$description])$anti->add($id,$description,static fn()=>true,static fn()=>false,static function($fixture,$outcome,$assert):void{$assert($outcome===true);},static fn()=>null);$antiResult=$anti->runAll(3);if($antiResult->failedIds()!==['COMP-NO-09-MUTATION','COMP-NO-18-MUTATION','HISTORICAL-SESSION-MUTATION'])throw new RuntimeException('comp_anti_false_pass_failed');echo 'R1DB_COMPENSATION_DENIED_CASE_IDS='.implode(',',$ids).PHP_EOL;echo 'R1DB_COMPENSATION_DENIED='.count($ids).'/PASS'.PHP_EOL;echo "R1DB_HISTORICAL_SESSIONS_PRESERVED=PASS\n";
