<?php
declare(strict_types=1);
require_once dirname(__DIR__,5).'/wp-load.php';
require_once __DIR__.'/minimarket-onboarding-r1d-b-case-registry.php';

use VeciAhorra\Modules\Minimarket\Onboarding\Account\ActivatePendingMinimarketAccount;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\ActivatePendingMinimarketAccountCommand;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\ActivationLockManager;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\PendingAccountException;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\RandomOpaqueUsernameGenerator;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\SensitivePassword;
use VeciAhorra\Modules\Minimarket\Onboarding\Account\WordPressPendingUserGateway;
use VeciAhorra\Modules\Minimarket\Onboarding\StoreOnboardingApplicationRepository;
use VeciAhorra\Modules\Minimarket\Onboarding\Verification\StoreOnboardingEmailVerification;
use VeciAhorra\Modules\Minimarket\Onboarding\Verification\StoreOnboardingEmailVerificationRepository;

final class R1dbCandidateWpdb extends wpdb
{
    public string $mode='normal';public int $candidateWrites=0;public array $trace=[];public int $deleteBeforeUserId=0;private bool $commitIntercepted=false;private bool $rereadArmed=false;
    public function query($query){$sql=(string)$query;if($sql==='COMMIT'&&in_array($this->mode,['commit_applied_false','commit_not_applied_false','reread_failed'],true)&&!$this->commitIntercepted){$this->commitIntercepted=true;if($this->mode==='commit_not_applied_false')parent::query('ROLLBACK');else parent::query('COMMIT');$this->rereadArmed=$this->mode==='reread_failed';return false;}return parent::query($query);}
    public function update($table,$data,$where,$format=null,$where_format=null){if(str_ends_with((string)$table,'store_onboarding_email_verifications')&&array_key_exists('candidate_user_id',$data)){$this->candidateWrites++;$this->trace[]='write';if($this->mode==='sql_error'){$this->last_error='driver detail hidden';return false;}}return parent::update($table,$data,$where,$format,$where_format);}
    public function get_row($query=null,$output=OBJECT,$y=0){$sql=(string)$query;if(str_contains($sql,'store_onboarding_applications')&&str_contains($sql,'FOR UPDATE'))$this->trace[]='application';if(str_contains($sql,'store_onboarding_email_verifications')&&str_contains($sql,'FOR UPDATE'))$this->trace[]='verification';if($this->rereadArmed&&str_contains($sql,'store_onboarding_email_verifications')&&!str_contains($sql,'FOR UPDATE')){$this->rereadArmed=false;$this->last_error='hostile reread SQL';return null;}return parent::get_row($query,$output,$y);}
    public function get_var($query=null,$x=0,$y=0){$sql=(string)$query;if(str_contains($sql,"{$this->users}")&&str_contains($sql,'FOR UPDATE')){$this->trace[]='user';if($this->deleteBeforeUserId>0){parent::delete($this->usermeta,['user_id'=>$this->deleteBeforeUserId]);parent::delete($this->users,['ID'=>$this->deleteBeforeUserId]);$this->deleteBeforeUserId=0;}}return parent::get_var($query,$x,$y);}
    public function resetEvidence():void{$this->candidateWrites=0;$this->trace=[];$this->commitIntercepted=false;$this->rereadArmed=false;}
}
final class R1dbCandidateInlineLocks implements ActivationLockManager{public function synchronized(array $identities,callable $criticalSection,?callable $reconcileAfterReleaseFailure=null):mixed{return $criticalSection();}}

function r1dbCandidateReason(callable $operation):array{try{return ['value'=>$operation(),'reason'=>null];}catch(Throwable $throwable){$reason=$throwable instanceof PendingAccountException?$throwable->reason:$throwable->getMessage();return ['value'=>null,'reason'=>$reason,'previous'=>$throwable->getPrevious(),'message'=>$throwable->getMessage()];}}
function r1dbCandidatePrivate(array $outcome,callable $assert):void{if($outcome['reason']!==null){$message=(string)($outcome['message']??'');$assert(($outcome['previous']??null)===null,'candidate previous leaked');foreach(['@example','12345678','SELECT ','UPDATE ','driver detail','hostile reread'] as $secret)$assert(!str_contains($message,$secret),'candidate privacy leak');}}

$database=(string)getenv('VA_R1DA_DISPOSABLE_DATABASE');if($database!=='minimarket_r1da_disposable'||$database===DB_NAME)throw new RuntimeException('candidate_database_guard');
global $wpdb;$production=$wpdb;$wpdb=new R1dbCandidateWpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);$wpdb->set_prefix('wp_');foreach(['actionscheduler_actions','actionscheduler_claims','actionscheduler_groups','actionscheduler_logs'] as $table)$wpdb->{$table}='wp_'.$table;
$before=[(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->users}"),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_stores'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_applications'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_email_verifications')];if($before!==[18,348,0,0])throw new RuntimeException('candidate_database_not_clean');
$runId=bin2hex(random_bytes(8));$historicalUsers=array_map('intval',$wpdb->get_col("SELECT ID FROM {$wpdb->users} ORDER BY ID LIMIT 2"));if(count($historicalUsers)!==2)throw new RuntimeException('candidate_users_missing');[$userA,$userB]=$historicalUsers;
$apps=new StoreOnboardingApplicationRepository();$verifications=new StoreOnboardingEmailVerificationRepository();$registry=new R1dbCaseRegistry();$t0='2026-09-01 00:00:00';$t1='2026-09-01 00:01:00';$t2='2026-09-01 00:02:00';
$setup=function(string $id)use($apps,$verifications,$runId,$t0):array{$suffix=strtolower(str_replace('-','_',$id));$app=$apps->createProvisioning(['public_id'=>'onb_'.$runId.'_'.$suffix,'account_email'=>$runId.'.'.$suffix.'@example.test','owner_rut_normalized'=>'12345678-5','idempotency_key_hash'=>hash('sha256',$runId.$id),'terms_version'=>'R1C-LEGAL-2026-07-30-V1','terms_accepted_at'=>$t0,'created_at'=>$t0,'updated_at'=>$t0]);$aid=(int)$app->data['id'];$token=hash('sha256',$runId.$id,true);$verification=$verifications->create($aid,StoreOnboardingEmailVerification::PURPOSE,null,hash('sha256','email'.$runId.$id,true),$token,'2026-09-01 01:00:00',$t0);return ['aid'=>$aid,'token'=>$token,'verification'=>$verification,'user'=>0];};
$cleanup=function(?array $fixture)use($wpdb):void{if(!is_array($fixture))return;$aid=(int)($fixture['aid']??0);if($aid>0){$wpdb->delete('wp_va_store_onboarding_email_verifications',['application_id'=>$aid]);$wpdb->delete('wp_va_store_onboarding_applications',['id'=>$aid]);}$uid=(int)($fixture['user']??0);if($uid>0){$wpdb->delete($wpdb->usermeta,['user_id'=>$uid]);$wpdb->delete($wpdb->users,['ID'=>$uid]);}$wpdb->mode='normal';$wpdb->deleteBeforeUserId=0;};
$bind=function(array $f,int $user,string $expected,string $now,int $generation=1)use($verifications){return $verifications->bindCandidateUser($f['aid'],$generation,$user,$expected,$now);};
$snapshot=function(int $aid)use($verifications){return $verifications->findByApplicationId($aid);};
$add=function(string $id,string $description,callable $prepare,callable $operation,callable $verify)use($registry,$setup,$cleanup):void{$registry->add($id,$description,function(string $caseId)use($setup,$prepare){$fixture=$setup($caseId);return $prepare($fixture);},$operation,function($fixture,$outcome,$assert,$caseId)use($verify){r1dbCandidatePrivate($outcome,$assert);$verify($fixture,$outcome,$assert,$caseId);},$cleanup);};

$identity=static fn(array $f):array=>$f;
$add('CAND-01','candidate null',$identity,fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t1)),function($f,$o,$a)use($snapshot,$userA,$wpdb){$v=$snapshot($f['aid']);$a($o['reason']===null&&$v?->candidateUserId===$userA&&$v->generation===1&&$v->consumedAt===null&&$v->attachedUserId===null&&$v->updatedAt==='2026-09-01 00:01:00'&&$wpdb->candidateWrites===1);});
$add('CAND-02','same user replay',function($f)use($bind,$userA,$t0,$t1,$wpdb){$bind($f,$userA,$t0,$t1);$f['before_updated_at']=$t1;$wpdb->resetEvidence();return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t2)),function($f,$o,$a)use($snapshot,$userA,$wpdb){$v=$snapshot($f['aid']);$a($o['reason']===null&&$v?->candidateUserId===$userA&&$v->updatedAt===$f['before_updated_at']&&$wpdb->candidateWrites===0);});
$add('CAND-03','other user conflict',function($f)use($bind,$userA,$t0,$t1,$wpdb){$bind($f,$userA,$t0,$t1);$wpdb->resetEvidence();return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userB,$t1,$t2)),function($f,$o,$a)use($snapshot,$userA,$wpdb){$v=$snapshot($f['aid']);$a($o['reason']==='verification_conflict'&&$v?->candidateUserId===$userA&&$wpdb->candidateWrites===0);});
$add('CAND-04','user missing',$identity,fn($f)=>r1dbCandidateReason(fn()=>$bind($f,PHP_INT_MAX,$t0,$t1)),function($f,$o,$a)use($snapshot,$wpdb){$a($o['reason']==='verification_reference_invalid'&&$snapshot($f['aid'])?->candidateUserId===null&&$wpdb->candidateWrites===0);});
$add('CAND-05','user deleted before locked revalidation',function($f)use($wpdb){$uid=wp_insert_user(['user_login'=>'r1dbc_'.bin2hex(random_bytes(8)),'user_email'=>bin2hex(random_bytes(8)).'@example.test','user_pass'=>'candidate password 2026','role'=>'subscriber']);if(!is_int($uid))throw new RuntimeException('candidate_fixture_user');$f['user']=$uid;$wpdb->deleteBeforeUserId=$uid;return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$f['user'],$t0,$t1)),function($f,$o,$a)use($snapshot,$wpdb){$a($o['reason']==='verification_reference_invalid'&&$snapshot($f['aid'])?->candidateUserId===null&&$wpdb->candidateWrites===0);});
$add('CAND-06','application missing',function($f)use($wpdb){$wpdb->delete('wp_va_store_onboarding_email_verifications',['application_id'=>$f['aid']]);$wpdb->delete('wp_va_store_onboarding_applications',['id'=>$f['aid']]);return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t1)),fn($f,$o,$a)=>$a($o['reason']==='verification_application_ineligible'&&$wpdb->candidateWrites===0));
$add('CAND-07','verification missing',function($f)use($wpdb){$wpdb->delete('wp_va_store_onboarding_email_verifications',['application_id'=>$f['aid']]);return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t1)),fn($f,$o,$a)=>$a($o['reason']==='verification_not_found'&&$wpdb->candidateWrites===0));
$add('CAND-08','generation mismatch',$identity,fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t1,2)),function($f,$o,$a)use($snapshot,$wpdb){$a($o['reason']==='verification_concurrent_modification'&&$snapshot($f['aid'])?->generation===1&&$wpdb->candidateWrites===0);});
$add('CAND-09','purpose mismatch',function($f)use($wpdb){$wpdb->update('wp_va_store_onboarding_email_verifications',['purpose'=>'other'],['application_id'=>$f['aid']]);$wpdb->resetEvidence();return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t1)),fn($f,$o,$a)=>$a($o['reason']==='verification_read_failed'&&$wpdb->candidateWrites===0));
$add('CAND-10','consumed verification',function($f)use($wpdb,$userA,$t1){$wpdb->update('wp_va_store_onboarding_applications',['status'=>'account_created','user_id'=>$userA,'updated_at'=>$t1],['id'=>$f['aid']]);$wpdb->update('wp_va_store_onboarding_email_verifications',['candidate_user_id'=>$userA,'attached_user_id'=>$userA,'consumed_at'=>$t1,'updated_at'=>$t1],['application_id'=>$f['aid']]);$wpdb->resetEvidence();return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t1,$t2)),fn($f,$o,$a)=>$a($o['reason']==='verification_application_ineligible'&&$wpdb->candidateWrites===0));
$serviceOutcome=function(array $f,string $kind)use($apps,$verifications,$wpdb,$t0,$t1,$userA){$v=$verifications->markDeliveryAttempt($f['aid'],1,$f['verification']->updatedAt,$t1);$v=$verifications->markSent($f['aid'],1,$v->updatedAt,'2026-09-01 00:02:00');if($kind==='expired')$wpdb->update('wp_va_store_onboarding_email_verifications',['expires_at'=>'2026-09-01 00:02:00'],['application_id'=>$f['aid']]);if($kind==='attempts')$wpdb->update('wp_va_store_onboarding_email_verifications',['failed_attempts'=>5],['application_id'=>$f['aid']]);$token=$kind==='token'?str_repeat('x',32):$f['token'];$service=new ActivatePendingMinimarketAccount($apps,$verifications,new WordPressPendingUserGateway(),new RandomOpaqueUsernameGenerator(),new R1dbCandidateInlineLocks());$wpdb->resetEvidence();return r1dbCandidateReason(fn()=>$service->execute(new ActivatePendingMinimarketAccountCommand($f['aid'],$token,1,new SensitivePassword('candidate password 2026'),'2026-09-01 00:03:00')));};
$add('CAND-11','expired before binding',$identity,fn($f)=>$serviceOutcome($f,'expired'),fn($f,$o,$a)=>$a($o['reason']==='verification_expired'&&$wpdb->candidateWrites===0));
$add('CAND-12','attempts exhausted',$identity,fn($f)=>$serviceOutcome($f,'attempts'),fn($f,$o,$a)=>$a($o['reason']==='verification_attempts_exhausted'&&$wpdb->candidateWrites===0));
$add('CAND-13','binary token mismatch',$identity,fn($f)=>$serviceOutcome($f,'token'),fn($f,$o,$a)=>$a($o['reason']==='verification_unavailable'&&$wpdb->candidateWrites===0));
$add('CAND-14','commit applied false',function($f)use($wpdb){$wpdb->resetEvidence();$wpdb->mode='commit_applied_false';return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t1)),function($f,$o,$a)use($snapshot,$userA,$wpdb){$a($o['reason']===null&&$snapshot($f['aid'])?->candidateUserId===$userA&&$wpdb->candidateWrites===1);});
$add('CAND-15','commit not applied false',function($f)use($wpdb){$wpdb->resetEvidence();$wpdb->mode='commit_not_applied_false';return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t1)),function($f,$o,$a)use($snapshot,$wpdb){$candidate=$snapshot($f['aid'])?->candidateUserId;$a($o['reason']==='verification_conflict'&&$candidate===null&&$wpdb->candidateWrites===1,'cand15 '.json_encode([$o['reason'],$candidate,$wpdb->candidateWrites]));});
$add('CAND-16','reconciliation reread failed',function($f)use($wpdb){$wpdb->resetEvidence();$wpdb->mode='reread_failed';return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t1)),function($f,$o,$a)use($wpdb){$a($o['reason']==='verification_outcome_uncertain'&&$wpdb->candidateWrites===1,'cand16 '.json_encode([$o['reason'],$wpdb->candidateWrites]));});
$add('CAND-17','sql update error',function($f)use($wpdb){$wpdb->resetEvidence();$wpdb->mode='sql_error';return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t1)),function($f,$o,$a)use($snapshot,$wpdb){$candidate=$snapshot($f['aid'])?->candidateUserId;$a($o['reason']==='verification_conflict'&&$candidate===null&&$wpdb->candidateWrites===1,'cand17 '.json_encode([$o['reason'],$candidate,$wpdb->candidateWrites]));});
$add('CAND-18','retry after ambiguous durable result',function($f)use($wpdb,$bind,$userA,$t0,$t1){$wpdb->mode='commit_applied_false';$bind($f,$userA,$t0,$t1);$wpdb->mode='normal';$wpdb->resetEvidence();return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t2)),function($f,$o,$a)use($snapshot,$userA,$wpdb){$a($o['reason']===null&&$snapshot($f['aid'])?->candidateUserId===$userA&&$snapshot($f['aid'])?->updatedAt==='2026-09-01 00:01:00'&&$wpdb->candidateWrites===0);});
$add('CAND-19','application verification user lock order',function($f)use($wpdb){$wpdb->resetEvidence();return $f;},fn($f)=>r1dbCandidateReason(fn()=>$bind($f,$userA,$t0,$t1)),function($f,$o,$a)use($wpdb){$first=[];foreach($wpdb->trace as $event)if(!isset($first[$event]))$first[$event]=count($first);$a($o['reason']===null&&isset($first['application'],$first['verification'],$first['user'],$first['write'])&&$first['application']<$first['verification']&&$first['verification']<$first['user']&&$first['user']<$first['write']&&!in_array('store',$wpdb->trace,true)&&$wpdb->candidateWrites===1);});

try{$results=$registry->runAll(19);$ids=$results->passedIds();if($results->failedIds()!==[]||count($ids)!==19)throw new RuntimeException('candidate_failed='.json_encode($results->failureDetails(),JSON_UNESCAPED_SLASHES));}
finally{$wpdb->mode='normal';$wpdb->query('ROLLBACK');$after=[(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->users}"),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_stores'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_applications'),(int)$wpdb->get_var('SELECT COUNT(*) FROM wp_va_store_onboarding_email_verifications')];$wpdb=$production;if($after!==$before)throw new RuntimeException('candidate_cleanup_failed');}
$mutationRegistry=new R1dbCaseRegistry();$mutationRegistry->add('CAND-03-MUTATION','forced wrong expectation',static fn()=>['durable_user'=>'other'],static fn($fixture)=>$fixture['durable_user'],static function($fixture,$outcome,$assert):void{$assert($outcome==='expected','candidate mutation escaped');},static fn()=>null);$mutationResult=$mutationRegistry->runAll(1);if($mutationResult->failedIds()!==['CAND-03-MUTATION'])throw new RuntimeException('candidate_anti_false_pass_failed');
echo 'R1DB_CANDIDATE_CASE_IDS='.implode(',',$ids).PHP_EOL;echo 'R1DB_CANDIDATE_MATRIX='.count($ids).'/PASS'.PHP_EOL;
