<?php
declare(strict_types=1);
use VeciAhorra\Core\Config;
use VeciAhorra\Modules\Products\Import\ProductBulkImportService;
use VeciAhorra\Modules\Products\Import\ProductImageZipParser;
require_once dirname(__DIR__,5).'/wp-load.php';
function pbr(bool $ok,string $m):void{if(!$ok)throw new RuntimeException($m);}
global $wpdb;$prefix=$wpdb->prefix.Config::TABLE_PREFIX;$nonce=substr(hash('sha256',(string)microtime(true)),0,12);$createdProducts=[];$createdTerms=[];$createdAttachments=[];$files=[];
$inventoryBefore=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}inventory");
try{
    $admin=get_users(['role'=>'administrator','number'=>1]);pbr($admin!==[],'Falta administrador.');wp_set_current_user((int)$admin[0]->ID);pbr(current_user_can('manage_options'),'Administrador sin permiso.');foreach(['veciahorra_minimarket','veciahorra_courier','veciahorra_service_provider','veciahorra_zonal_admin','subscriber']as$role){$u=get_users(['role'=>$role,'number'=>1]);if($u!==[]){wp_set_current_user((int)$u[0]->ID);pbr(!current_user_can('manage_options'),'Rol no administrador obtuvo manage_options: '.$role);}}wp_set_current_user((int)$admin[0]->ID);
    $cat=wp_insert_term('P0 Categoría '.$nonce,'product_cat');pbr(!is_wp_error($cat),'No creó categoría fixture.');$createdTerms[]=['product_cat',(int)$cat['term_id']];
    $sub=wp_insert_term('P0 Subcategoría '.$nonce,'product_cat',['parent'=>(int)$cat['term_id']]);pbr(!is_wp_error($sub),'No creó subcategoría fixture.');$createdTerms[]=['product_cat',(int)$sub['term_id']];
    $other=wp_insert_term('P0 Otra '.$nonce,'product_cat');pbr(!is_wp_error($other),'No creó categoría alterna.');$createdTerms[]=['product_cat',(int)$other['term_id']];
    $brand=wp_insert_term('P0 Marca '.$nonce,'product_brand');pbr(!is_wp_error($brand),'No creó marca fixture.');$createdTerms[]=['product_brand',(int)$brand['term_id']];
    $unit=wp_insert_term('P0 Unidad '.$nonce,'pa_unidad');pbr(!is_wp_error($unit),'No creó unidad fixture.');$createdTerms[]=['pa_unidad',(int)$unit['term_id']];
    $row=static fn(int $i,array $x=[]):array=>array_merge(['line'=>$i+1,'sku'=>'P0-'.$nonce.'-'.$i,'name'=>'Producto P0 '.$i,'category'=>'P0 Categoría '.$nonce,'subcategory'=>'P0 Subcategoría '.$nonce,'brand'=>'P0 Marca '.$nonce,'unit'=>'P0 Unidad '.$nonce,'description'=>'Descripción controlada','status'=>'draft','image'=>''],$x);
    $rows=[];for($i=1;$i<=100;$i++)$rows[]=$row($i);$service=new ProductBulkImportService();
    $before=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$prefix}products WHERE sku LIKE %s",'P0-'.$nonce.'-%'));$preview=$service->preview($rows,[]);pbr($before===0&&$preview['created']===100&&$preview['errors']===[],'Preview de 100 no fue read-only/válida.');
    $mixed=$service->preview([$row(201)], [['line'=>3,'sku'=>'BAD','message'=>'Error inducido.']]);try{$service->import($mixed);throw new RuntimeException('Importó CSV mixto.');}catch(InvalidArgumentException){}pbr((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$prefix}products WHERE sku=%s",'P0-'.$nonce.'-201'))===0,'CSV mixto escribió.');
    $result=$service->import($preview);pbr($result['created']===100,'No creó 100 productos.');$createdProducts=$wpdb->get_col($wpdb->prepare("SELECT id FROM {$prefix}products WHERE sku LIKE %s",'P0-'.$nonce.'-%'));
    pbr((int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}inventory")===$inventoryBefore,'Creó Inventory.');
    $again=$service->preview($rows,[]);pbr($again['unchanged']===100,'Re-preview no fue idempotente.');$againResult=$service->import($again);pbr($againResult['unchanged']===100,'Reimportación no fue idempotente.');
    $updatedRows=$rows;$updatedRows[0]['name']='Producto actualizado';$up=$service->preview($updatedRows,[]);pbr($up['updated']===1,'No clasificó actualización.');$service->import($up);pbr((string)$wpdb->get_var($wpdb->prepare("SELECT name FROM {$prefix}products WHERE sku=%s",$rows[0]['sku']))==='Producto actualizado','No actualizó por SKU.');
    $stale=$service->preview([$updatedRows[0]],[]);$wpdb->update($prefix.'products',['updated_at'=>'2099-01-01 00:00:00'],['sku'=>$rows[0]['sku']]);try{$service->import($stale);throw new RuntimeException('Aceptó preview obsoleta.');}catch(RuntimeException $e){pbr(str_contains($e->getMessage(),'cancelada'),'Error obsoleto inseguro.');}
    $badSub=$service->preview([$row(301,['subcategory'=>'P0 Otra '.$nonce])],[]);pbr(count($badSub['errors'])===1,'Aceptó subcategoría fuera de jerarquía.');
    $png=file_get_contents(WP_CONTENT_DIR.'/uploads/2026/06/Agua-mineral.png');pbr(is_string($png)&&strlen($png)>0,'PNG fixture válido no disponible.');$imageName=$rows[1]['sku'].'.png';$imageRow=$updatedRows[1];$imageRow['image']=$imageName;$ip=$service->preview([$imageRow],[],[$imageName=>$png]);pbr($ip['updated']===1&&$ip['errors']===[],'Preview imagen inválida.');$ir=$service->import($ip);pbr($ir['updated']===1,'No incorporó imagen.');$attachment=(int)$wpdb->get_var($wpdb->prepare("SELECT image_id FROM {$prefix}products WHERE sku=%s",$rows[1]['sku']));pbr($attachment>0&&get_post_type($attachment)==='attachment','Attachment no vinculado.');$createdAttachments[]=$attachment;
    $sameImage=$service->preview([$imageRow],[],[$imageName=>$png]);pbr($sameImage['unchanged']===1,'Imagen idéntica no fue idempotente.');
    $missing=$service->preview([$row(302,['image'=>'P0-'.$nonce.'-302.png'])],[],[]);pbr(count($missing['errors'])===1,'Aceptó imagen declarada ausente.');$orphan=$service->preview([],[],['ORPHAN.png'=>$png]);pbr(count($orphan['errors'])===1,'Aceptó imagen sin SKU.');
    $replacement=file_get_contents(WP_CONTENT_DIR.'/uploads/2026/06/Ariel.png');pbr(is_string($replacement)&&hash('sha256',$replacement)!==hash('sha256',$png),'Imagen de rollback no disponible.');$guardRow=$updatedRows[98];$rollbackPreview=$service->preview([$imageRow,$guardRow],[],[$imageName=>$replacement]);$wpdb->update($prefix.'products',['updated_at'=>'2099-02-01 00:00:00'],['sku'=>$guardRow['sku']]);$attachmentsBefore=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->posts} WHERE post_type='attachment'");$upload=wp_upload_dir();$filesBefore=count(glob($upload['path'].'/*')?:[]);try{$service->import($rollbackPreview);throw new RuntimeException('No indujo rollback posterior al attachment.');}catch(RuntimeException $e){pbr(str_contains($e->getMessage(),'cancelada'),'Rollback no fue seguro.');}pbr((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->posts} WHERE post_type='attachment'")===$attachmentsBefore,'Attachment huérfano tras rollback.');pbr(count(glob($upload['path'].'/*')?:[])===$filesBefore,'Archivo huérfano tras rollback.');pbr((int)$wpdb->get_var($wpdb->prepare("SELECT image_id FROM {$prefix}products WHERE sku=%s",$rows[1]['sku']))===$attachment,'Rollback alteró la imagen anterior.');
    $zipPath=wp_tempnam('p0-valid.zip');$files[]=$zipPath;$zip=new ZipArchive();pbr($zip->open($zipPath,ZipArchive::OVERWRITE)===true,'No creó ZIP.');$zip->addFromString($imageName,$png);$zip->close();$parsed=(new ProductImageZipParser())->parse($zipPath,filesize($zipPath));pbr(isset($parsed[$imageName]),'ZIP válido rechazado.');
    $hostile=wp_tempnam('p0-hostile.zip');$files[]=$hostile;$zip=new ZipArchive();$zip->open($hostile,ZipArchive::OVERWRITE);$zip->addFromString('../evil.png',$png);$zip->close();try{(new ProductImageZipParser())->parse($hostile,filesize($hostile));throw new RuntimeException('Aceptó traversal.');}catch(InvalidArgumentException){}
    $mime=wp_tempnam('p0-mime.zip');$files[]=$mime;$zip=new ZipArchive();$zip->open($mime,ZipArchive::OVERWRITE);$zip->addFromString('FAKE.png','not an image');$zip->close();try{(new ProductImageZipParser())->parse($mime,filesize($mime));throw new RuntimeException('Aceptó MIME falso.');}catch(InvalidArgumentException){}
    $duplicate=wp_tempnam('p0-duplicate.zip');$files[]=$duplicate;$zip=new ZipArchive();$zip->open($duplicate,ZipArchive::OVERWRITE);$zip->addFromString('DUP.png',$png);$zip->addFromString('dup.PNG',$png);$zip->close();try{(new ProductImageZipParser())->parse($duplicate,filesize($duplicate));throw new RuntimeException('Aceptó nombre duplicado.');}catch(InvalidArgumentException){}
    echo "product-bulk-runtime-test: PASS products=100 inventory_delta=0 image=PASS hostile_zip=PASS\n";
}finally{foreach($createdProducts as$id)$wpdb->delete($prefix.'products',['id'=>(int)$id]);foreach($createdAttachments as$id)wp_delete_attachment((int)$id,true);foreach(array_reverse($createdTerms)as[$tax,$id])wp_delete_term($id,$tax);foreach($files as$f)if(is_string($f)&&is_file($f))@unlink($f);wp_set_current_user(0);pbr((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$prefix}products WHERE sku LIKE %s",'P0-'.$nonce.'-%'))===0,'Residuos Product.');pbr((int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}inventory")===$inventoryBefore,'Residuo Inventory.');}
