<?php
declare(strict_types=1);
require dirname(__DIR__,5).'/wp-load.php';
require_once ABSPATH.'wp-admin/includes/user.php';
global $wpdb;
const VA_META='_veciahorra_service_zone_id';const VA_PREFIX='va_sector_contract_';
function ok(bool $v,string $c,array $d=[]):void{if(!$v){$s=[];foreach(['status','rest_code']as$k)if(isset($d[$k]))$s[]=$k.'='.preg_replace('/[^a-zA-Z0-9_.-]/','_',(string)$d[$k]);throw new RuntimeException($c.($s?' '.implode(' ',$s):''));}}
function optionsSnap():array{global $wpdb;$rows=$wpdb->get_results('SELECT option_name,option_value FROM '.$wpdb->options.' ORDER BY option_name',ARRAY_A);$m=[];foreach($rows as$r)$m[(string)$r['option_name']]=hash('sha256',get_debug_type($r['option_value'])."\0".(string)$r['option_value']);return$m;}
function tablesSnap():array{global $wpdb;$n=$wpdb->get_col('SELECT table_name FROM information_schema.tables WHERE table_schema=DATABASE() ORDER BY table_name');return['count'=>count($n),'hash'=>hash('sha256',implode("\n",$n))];}
function safeNames(array$n):string{return$n?implode(',',array_map(static fn(string$x):string=>preg_match('/key|secret|token|password|auth|nonce|credential/i',$x)?'redacted_sensitive_name':$x,$n)):'none';}
function req(string$m,string$u,array$c=[],string$n=''):array{$h=['Accept'=>'application/json'];if($c){$p=[];foreach($c as$k=>$v)$p[]=$k.'='.$v;$h['Cookie']=implode('; ',$p);}if($n!=='')$h['X-WP-Nonce']=$n;$r=wp_remote_request($u,['method'=>$m,'headers'=>$h,'sslverify'=>false,'timeout'=>20]);if(is_wp_error($r))return['status'=>0,'body'=>['code'=>'transport_error'],'cookies'=>$c];foreach(wp_remote_retrieve_cookies($r)as$x)if($x instanceof WP_Http_Cookie&&$x->name!=='')$c[$x->name]=$x->value;$b=json_decode((string)wp_remote_retrieve_body($r),true);return['status'=>(int)wp_remote_retrieve_response_code($r),'body'=>is_array($b)?$b:[],'cookies'=>$c];}
function auth(int$id):array{wp_set_current_user($id);$a=wp_generate_auth_cookie($id,time()+HOUR_IN_SECONDS,'logged_in');$_COOKIE[LOGGED_IN_COOKIE]=$a;$n=wp_create_nonce('wp_rest');unset($_COOKIE[LOGGED_IN_COOKIE]);wp_set_current_user(0);return['cookies'=>[LOGGED_IN_COOKIE=>$a],'nonce'=>$n];}
function code(array$b):string{return sanitize_key((string)($b['error']['code']??$b['code']??'none'))?:'none';}
function dataId(array$b):int{$r=is_array($b['data']??null)?($b['data']['id']??null):null;return is_int($r)?$r:(is_string($r)&&preg_match('/^[1-9]\d*$/D',$r)?(int)$r:0);}
function authResponse(array$r,int$uid,string$l):void{$c=code($r['body']);$m=get_user_meta($uid,VA_META,true);$mid=preg_match('/^[1-9]\d*$/D',(string)$m)?(int)$m:0;$d=['status'=>$r['status'],'rest_code'=>$c];ok($r['status']===200,$l.'_HTTP_STATUS',$d);ok($c==='none',$l.'_REST_CODE',$d);ok(($r['body']['success']??null)===true,$l.'_SUCCESS',$d);ok(is_array($r['body']['data']??null),$l.'_DATA_SHAPE',$d);ok(dataId($r['body'])===1,$l.'_DATA_ID',$d);ok($mid===1,$l.'_USER_META',$d);}
function destroySession(array$c):void{$name=session_name();$id=$c[$name]??'';if($id===''||session_status()!==PHP_SESSION_NONE)return;session_id($id);if(@session_start()){$_SESSION=[];session_destroy();}session_id('');}
$before=optionsSnap();$tb=tablesSnap();$users=[];$sessions=[];$iterations=0;$noNonce=$anon=$isolation=$idem='not_run';$base=rest_url('veciahorra/v1/sector/current');
try{
ok((int)$wpdb->get_var('SELECT 1')===1,'DB_SELECT_FAILED');ok((int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.$wpdb->users.' WHERE user_login LIKE %s',VA_PREFIX.'%'))===0,'FIXTURE_USERS_PREEXIST');
for($i=1;$i<=3;$i++){$login=VA_PREFIX.bin2hex(random_bytes(6));$uid=wp_create_user($login,wp_generate_password(32,true,true),$login.'@example.invalid');ok(!is_wp_error($uid),'FIXTURE_USER_CREATE_FAILED');$uid=(int)$uid;$users[]=$uid;(new WP_User($uid))->set_role('customer');$a=auth($uid);$g=req('GET',$base,$a['cookies'],$a['nonce']);ok($g['status']===200&&($g['body']['success']??null)===true&&array_key_exists('data',$g['body'])&&$g['body']['data']===null,'AUTH_GET_INITIAL_FAILED',['status'=>$g['status'],'rest_code'=>code($g['body'])]);$p=req('POST',$base.'/1',$a['cookies'],$a['nonce']);authResponse($p,$uid,'AUTH_POST');$g2=req('GET',$base,$a['cookies'],$a['nonce']);ok($g2['status']===200&&($g2['body']['success']??null)===true&&dataId($g2['body'])===1,'AUTH_GET_READBACK_FAILED',['status'=>$g2['status'],'rest_code'=>code($g2['body'])]);ok((int)get_user_meta($uid,VA_META,true)===1,'AUTH_META_READBACK_FAILED');$p2=req('POST',$base.'/1',$a['cookies'],$a['nonce']);authResponse($p2,$uid,'AUTH_POST_IDEMPOTENT');$idem='pass';$iterations++;delete_user_meta($uid,VA_META);wp_delete_user($uid);array_pop($users);}
$login=VA_PREFIX.bin2hex(random_bytes(6));$uid=wp_create_user($login,wp_generate_password(32,true,true),$login.'@example.invalid');ok(!is_wp_error($uid),'NO_NONCE_USER_CREATE_FAILED');$uid=(int)$uid;$users[]=$uid;(new WP_User($uid))->set_role('customer');$a=auth($uid);$invalidNonce=req('POST',$base.'/1',$a['cookies'],'invalid');ok($invalidNonce['status']===403&&code($invalidNonce['body'])==='rest_cookie_invalid_nonce','INVALID_NONCE_NOT_REJECTED',['status'=>$invalidNonce['status'],'rest_code'=>code($invalidNonce['body'])]);ok(get_user_meta($uid,VA_META,true)==='','INVALID_NONCE_WROTE_USER_META');$nn=req('POST',$base.'/1',$a['cookies']);$sessions[]=$nn['cookies'];ok(get_user_meta($uid,VA_META,true)==='','NO_NONCE_WROTE_USER_META');ok(!(code($nn['body'])==='none'&&($nn['body']['success']??null)===true&&dataId($nn['body'])===1&&get_user_meta($uid,VA_META,true)==='1'),'NO_NONCE_SATISFIED_AUTH_CONTRACT');$noNonce='pass_invalid_rejected_and_missing_anonymous';wp_delete_user($uid);array_pop($users);
$a0=req('GET',$base);$sessions[]=$a0['cookies'];ok($a0['status']===200&&array_key_exists('data',$a0['body'])&&$a0['body']['data']===null,'ANON_A_INITIAL_FAILED');$ap=req('POST',$base.'/1',$a0['cookies']);$sessions[]=$ap['cookies'];ok($ap['status']===200&&dataId($ap['body'])===1,'ANON_A_POST_FAILED',['status'=>$ap['status'],'rest_code'=>code($ap['body'])]);$ag=req('GET',$base,$ap['cookies']);$sessions[]=$ag['cookies'];ok($ag['status']===200&&dataId($ag['body'])===1,'ANON_A_READBACK_FAILED');$anon='pass';$b0=req('GET',$base);$sessions[]=$b0['cookies'];ok($b0['status']===200&&array_key_exists('data',$b0['body'])&&$b0['body']['data']===null,'ANON_B_ISOLATION_FAILED');$isolation='pass';$bad=req('POST',$base.'/999999999',$b0['cookies']);ok($bad['status']===422&&code($bad['body'])==='invalid_sector'&&($bad['body']['success']??null)===false,'INVALID_SECTOR_CONTRACT_FAILED',['status'=>$bad['status'],'rest_code'=>code($bad['body'])]);
}finally{foreach($users as$uid){delete_user_meta($uid,VA_META);wp_delete_user($uid);}foreach($sessions as$c)destroySession($c);wp_set_current_user(0);}
$after=optionsSnap();$ta=tablesSnap();$added=array_values(array_diff(array_keys($after),array_keys($before)));$removed=array_values(array_diff(array_keys($before),array_keys($after)));$changed=[];foreach(array_intersect(array_keys($before),array_keys($after))as$n)if($before[$n]!==$after[$n])$changed[]=$n;sort($added);sort($removed);sort($changed);$remaining=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.$wpdb->users.' WHERE user_login LIKE %s',VA_PREFIX.'%'));$nondeterministic=array_values(array_filter(array_merge($added,$removed,$changed),static fn(string$n):bool=>preg_match('/^(?:cron|_transient_|_site_transient_)/',$n)!==1));ok($remaining===0,'FIXTURE_USERS_REMAIN');ok($nondeterministic===[],'OPTIONS_UNAUTHORIZED_DELTA');ok($tb===$ta,'TABLE_BASELINE_CHANGED');
echo'SECTOR_CURRENT_REST_PERSISTENCE=PASS'.PHP_EOL.'AUTH_POST_EXPECTATION=HTTP_200+NO_REST_ERROR+SUCCESS_TRUE+DATA_SHAPE+DATA_ID_1+REST_USER+CURRENT_USER+META_1+READBACK_1'.PHP_EOL.'AUTHENTICATED_ITERATIONS='.$iterations.PHP_EOL.'NO_NONCE_NEGATIVE_CONTROL='.$noNonce.PHP_EOL.'ANONYMOUS_PERSISTENCE='.$anon.PHP_EOL.'SESSION_ISOLATION='.$isolation.PHP_EOL.'IDEMPOTENCE='.$idem.PHP_EOL.'FIXTURE_USERS='.$remaining.PHP_EOL.'OPTIONS_COUNT_BEFORE='.count($before).PHP_EOL.'OPTIONS_COUNT_AFTER='.count($after).PHP_EOL.'OPTIONS_ADDED_COUNT='.count($added).PHP_EOL.'OPTIONS_REMOVED_COUNT='.count($removed).PHP_EOL.'OPTIONS_CHANGED_COUNT='.count($changed).PHP_EOL.'OPTIONS_DELTA_NAMES='.safeNames($changed).PHP_EOL.'TABLE_COUNT='.$ta['count'].PHP_EOL.'TABLE_BASELINE=restored'.PHP_EOL;
