<?php
declare(strict_types=1);
use VeciAhorra\Core\Config;use VeciAhorra\Database\Installer;use VeciAhorra\Modules\CustomerAccess\CustomerAccessModule;use VeciAhorra\Modules\ServiceProviders\Domain\ServiceCatalog;use VeciAhorra\Modules\ServiceProviders\Identity\ServiceProviderRole;use VeciAhorra\Modules\ServiceProviders\Service\ServiceProviderService;use VeciAhorra\Modules\ServiceProviders\ServiceProviderModule;
require_once dirname(__DIR__,5).'/wp-load.php';require_once ABSPATH.'wp-admin/includes/user.php';
function sAssert(bool$c,string$m):void{if(!$c)throw new RuntimeException($m);}function sReq(string$m,string$p,array$b=[]):WP_REST_Response{$parts=wp_parse_url($p);$r=new WP_REST_Request($m,'/veciahorra/v1/'.ltrim((string)($parts['path']??''),'/'));if(isset($parts['query'])){parse_str((string)$parts['query'],$q);$r->set_query_params($q);}if($b!==[]){$r->set_header('Content-Type','application/json');$r->set_body((string)wp_json_encode($b));}return rest_do_request($r);}
global$wpdb;Installer::install();ServiceProviderRole::register();do_action('rest_api_init');$table=$wpdb->prefix.Config::TABLE_PREFIX.'service_providers';$users=[];$providerIds=[];$n=bin2hex(random_bytes(5));
$payload=static fn(string$name,string$plan='local',string$category='veciarregla',string$subcategory='gasfiteria'):array=>['full_name'=>$name,'rut'=>'12.345.678-9','email'=>strtolower(str_replace(' ','',$name)).'@example.test','phone'=>'+56912345678','plan'=>$plan,'terms_accepted'=>true,'photo_id'=>0,'business_name'=>'Servicio '.$name,'category_key'=>$category,'subcategory_key'=>$subcategory,'description'=>'Servicio profesional para vecinos.','commune'=>'San Miguel','coverage'=>['La Cisterna'],'specialties'=>['Urgencias','Instalación'],'experience_years'=>8,'schedule'=>'Lunes a viernes','emergency_service'=>true,'whatsapp'=>'+56912345678','contact_email'=>'contacto'.substr(md5($name),0,6).'@example.test'];
try{
 sAssert(version_compare(Config::SCHEMA_VERSION,'0.26.0','>=')&&$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))===$table,'S01 schema/modelo');
 wp_set_current_user(0);$customerAccess=new CustomerAccessModule();$anonymousLanding=(new ServiceProviderModule($customerAccess))->services();sAssert(str_contains($anonymousLanding,'Tu talento merece ser conocido')&&!str_contains($anonymousLanding,'data-va-services'),'S01 landing anónima sin directorio');$anonymousList=sReq('GET','services');$anonymousExisting=sReq('GET','services/1');$anonymousMissing=sReq('GET','services/'.PHP_INT_MAX);sAssert($anonymousList->get_status()===200&&$anonymousMissing->get_status()===404&&in_array($anonymousExisting->get_status(),[200,404],true),'S01 REST anónimo público y no encontrado uniforme');$anonymousJson=wp_json_encode([$anonymousList->get_data(),$anonymousExisting->get_data()]);sAssert(!str_contains($anonymousJson,'admin_observation')&&!str_contains($anonymousJson,'12.345.678-9'),'S01 REST anónimo sin datos privados');sAssert(str_contains($anonymousLanding,'Plan Local')&&str_contains($anonymousLanding,'1.000')&&str_contains($anonymousLanding,'Plan Destacado')&&str_contains($anonymousLanding,'2.000')&&str_contains($anonymousLanding,'Plan Comunal')&&str_contains($anonymousLanding,'3.000')&&str_contains($anonymousLanding,'Visibilidad en toda la comuna'),'S01 tres planes');sAssert(!str_contains($anonymousLanding,'data-va-provider-form')&&!str_contains($anonymousLanding,'José Martínez')&&!str_contains($anonymousLanding,'4,9')&&!str_contains($anonymousLanding,'wp-login.php')&&!str_contains($anonymousLanding,'action=register'),'S01 sin formulario, identidad ficticia ni registro nativo');$servicesUrl=home_url('/servicios/');$registrationUrl=$customerAccess->registrationUrl($servicesUrl);sAssert(str_starts_with($registrationUrl,home_url('/registro-cliente/'))&&str_contains($registrationUrl,'redirect_to=')&&substr_count($anonymousLanding,'redirect_to=')>=5,'S01 CTA registro personalizado');
 foreach(['a','b','plain']as$x){$u=wp_create_user("sp_{$x}_{$n}",wp_generate_password(20),"sp_{$x}_{$n}@example.test");sAssert(is_int($u),'fixture user');$users[]=$u;}[$a,$b,$plain]=$users;
 wp_set_current_user($a);sAssert(sReq('POST','service-provider/enroll')->get_status()===200,'S02 registro');wp_set_current_user(0);wp_set_current_user($a);sAssert(current_user_can(ServiceProviderRole::CAPABILITY),'S02 capability');
 $created=sReq('POST','service-provider/profile',$payload('Jose Martinez','featured'));sAssert($created->get_status()===200,'S03 perfil: '.wp_json_encode($created->get_data()));$pa=(int)$created->get_data()['data']['id'];$providerIds[]=$pa;sAssert((int)get_user_meta($a,ServiceProviderRole::META_KEY,true)===$pa,'ownership meta');
 sAssert(count(ServiceCatalog::CATEGORIES)===10&&ServiceCatalog::valid('veciarregla','gasfiteria'),'S04 catálogo');sAssert($created->get_data()['data']['plan']==='featured','S06 destacado');sAssert($created->get_data()['data']['rut']==='12.345.678-9','S07 privados');sAssert($created->get_data()['data']['commune']==='San Miguel'&&count($created->get_data()['data']['coverage'])===1,'S08 cobertura');sAssert(count($created->get_data()['data']['specialties'])===2,'S09 descripción/especialidades');
 $submitted=sReq('POST','service-provider/submit');sAssert($submitted->get_status()===200&&$submitted->get_data()['data']['status']==='in_review','S11/S12 envío');
 sAssert(sReq('POST','service-provider/profile',$payload('Intruso'))->get_status()===409,'in_review editable');sAssert(sReq('GET','services/'.$pa)->get_status()===404,'no publicado visible');
 $service=new ServiceProviderService();$observed=$service->adminTransition($pa,'observed','Corrige tu descripción.');sAssert($observed['admin_observation']!=='','S10 observación');
 $fix=$payload('Jose Martinez','featured');$fix['provider_id']=$pa;$fix['description']='Descripción corregida y completa.';sAssert(sReq('POST','service-provider/profile',$fix)->get_status()===200,'observed editable');sReq('POST','service-provider/submit');$approved=$service->adminTransition($pa,'approved');sAssert($approved['status']==='approved'&&$approved['approved_at']!==null,'S13 aprobación');$published=$service->adminTransition($pa,'published');sAssert($published['status']==='published','S14 publicación');
 wp_set_current_user($b);sReq('POST','service-provider/enroll');wp_set_current_user(0);wp_set_current_user($b);$local=sReq('POST','service-provider/profile',$payload('Carolina Rojas','local','vecilimpia','aseo-domiciliario'));sAssert($local->get_status()===200&&$local->get_data()['data']['plan']==='local','S05 Local');$pb=(int)$local->get_data()['data']['id'];$providerIds[]=$pb;sReq('POST','service-provider/submit');$service->adminTransition($pb,'approved');$service->adminTransition($pb,'published');
 wp_set_current_user($plain);$catalog=sReq('GET','services?commune=San%20Miguel')->get_data()['data'];$fixtureCatalog=array_values(array_filter($catalog,static fn(array$row):bool=>in_array((int)$row['id'],[$pa,$pb],true)));sAssert(count($fixtureCatalog)===2&&(int)$fixtureCatalog[0]['id']===$pa&&$fixtureCatalog[0]['featured']===true,'S15 prioridad autenticada');$public=sReq('GET','services/'.$pa);$json=wp_json_encode($public->get_data());sAssert($public->get_status()===200&&str_contains($json,'contact_email'),'S16/S17 perfil/contacto');sAssert(!str_contains($json,'12.345.678-9')&&!str_contains($json,'admin_observation')&&!str_contains($json,'Corrige'),'privacidad autenticada');
 wp_set_current_user($a);$spoof=$payload('Spoof');$spoof['provider_id']=$pb;sAssert(sReq('POST','service-provider/profile',$spoof)->get_status()===409,'spoof provider_id');
 wp_set_current_user($b);$bad=$payload('Bad');$bad['category_key']='inventada';sAssert(sReq('POST','service-provider/profile',$bad)->get_status()===409||sReq('POST','service-provider/profile',$bad)->get_status()===422,'categoría arbitraria');$bad=$payload('Bad');$bad['subcategory_key']='electricidad';sAssert(sReq('POST','service-provider/profile',$bad)->get_status()!==200,'subcategoría cruzada');$bad=$payload('Bad');$bad['specialties']=['1','2','3','4','5','6'];sAssert(sReq('POST','service-provider/profile',$bad)->get_status()!==200,'más de 5');$bad=$payload('Bad');$bad['plan']='premium';sAssert(sReq('POST','service-provider/profile',$bad)->get_status()!==200,'plan inválido');$bad=$payload('Bad');$bad['photo_id']=PHP_INT_MAX;sAssert(sReq('POST','service-provider/profile',$bad)->get_status()!==200,'attachment inválido');
 wp_set_current_user($plain);sAssert(sReq('GET','service-provider/me')->get_status()===403,'anónimo actor');
 wp_set_current_user($a);sAssert(shortcode_exists(ServiceProviderModule::REGISTRATION)&&shortcode_exists(ServiceProviderModule::PANEL)&&shortcode_exists(ServiceProviderModule::SERVICES),'shortcodes');sAssert(str_contains(do_shortcode('['.ServiceProviderModule::REGISTRATION.']'),'Tu talento merece ser conocido'),'landing');
 $service->adminTransition($pa,'inactive');wp_set_current_user($plain);$afterDeactivate=sReq('GET','services')->get_data()['data'];$afterIds=array_map(static fn(array$row):int=>(int)$row['id'],$afterDeactivate);sAssert(sReq('GET','services/'.$pa)->get_status()===404&&!in_array($pa,$afterIds,true)&&in_array($pb,$afterIds,true),'S18 desactivación');
 echo"S01-S18 PASS\nREADINESS=18/18 (100%)\nPRIVACY=PASS ADVERSARIAL=PASS\n";
}finally{wp_set_current_user(0);foreach($providerIds as$id)$wpdb->delete($table,['id'=>$id]);foreach(array_reverse($users)as$u)wp_delete_user($u);}
