<?php

declare(strict_types=1);

require_once dirname(__DIR__, 5) . '/wp-load.php';
require_once ABSPATH . 'wp-admin/includes/user.php';

use VeciAhorra\Modules\ZonalAdmin\Identity\ZonalAdminRole;
use VeciAhorra\Modules\ZonalAdmin\Repositories\ZonalSalesRepository;

function zsAssert(bool $ok, string $message): void { if (! $ok) throw new RuntimeException($message); }
global $wpdb;
zsAssert(wp_timezone_string()==='America/Santiago','La autoridad temporal de WordPress no es America/Santiago.');
$p=$wpdb->prefix.'va_';$tables=['zones'=>$p.'service_zones','stores'=>$p.'stores','store_zones'=>$p.'store_service_zones','assignments'=>$p.'zonal_admin_service_zones','orders'=>$p.'orders','items'=>$p.'order_items','payments'=>$p.'payments','payment_orders'=>$p.'payment_orders'];
$run='zs_'.bin2hex(random_bytes(5));$now=current_time('mysql');$recent=(new DateTimeImmutable($now))->modify('-2 days')->format('Y-m-d H:i:s');$old=(new DateTimeImmutable($now))->modify('-40 days')->format('Y-m-d H:i:s');
$admin=(int)$wpdb->get_var("SELECT user_id FROM {$wpdb->usermeta} WHERE meta_key='{$wpdb->prefix}capabilities' AND meta_value LIKE '%administrator%' ORDER BY user_id LIMIT 1");zsAssert($admin>0,'Administrador fixture ausente.');
$users=[];$zones=[];$stores=[];$orders=[];$payments=[];
try {
 foreach(['a','b'] as $key){$id=wp_create_user($run.'_'.$key,wp_generate_password(30),$run.'_'.$key.'@example.test');zsAssert(!is_wp_error($id),'No se creó zonal.');$users[$key]=(int)$id;(new WP_User((int)$id))->set_role(ZonalAdminRole::ROLE);}
 foreach(['Norte','Centro','Sur'] as $name){zsAssert($wpdb->insert($tables['zones'],['commune'=>$run,'name'=>$run.' '.$name,'status'=>'active','created_at'=>$now,'updated_at'=>$now])===1,'No se creó sector.');$zones[]=(int)$wpdb->insert_id;}
 foreach([[$users['a'],$zones[0]],[$users['a'],$zones[1]],[$users['b'],$zones[2]]] as [$user,$zone])zsAssert($wpdb->insert($tables['assignments'],['user_id'=>$user,'service_zone_id'=>$zone,'created_at'=>$now,'created_by'=>$admin])===1,'No se asignó sector.');
 foreach([['A1','active',$zones[0]],['A2','inactive',$zones[0]],['AB','active',$zones[1]],['B','active',$zones[2]]] as [$key,$status,$zone]){$wpdb->insert($tables['stores'],['business_name'=>$run.' '.$key,'legal_name'=>$run.' '.$key,'owner_name'=>'Fixture','rut'=>$run.'-'.$key,'email'=>$run.'-'.$key.'@example.test','phone'=>'0','status'=>$status,'onboarding_status'=>'complete','approved_at'=>$now,'created_at'=>$now,'updated_at'=>$now]);$stores[$key]=(int)$wpdb->insert_id;$wpdb->insert($tables['store_zones'],['store_id'=>$stores[$key],'zone_id'=>$zone,'assigned_by'=>$admin,'assigned_at'=>$now]);}
 $makeOrder=static function(string $key,int $store,string $status,string $paymentStatus,string $paidAt,array $subtotals)use(&$orders,&$payments,$tables,$wpdb,$users,$now,$run):void{$orderTotal=array_sum($subtotals)+($key==='paid-a1'?600:0);$wpdb->insert($tables['orders'],['customer_id'=>$users['a'],'minimarket_id'=>$store,'total'=>(string)$orderTotal,'status'=>$status,'store_fulfillment_status'=>'awaiting_confirmation','created_at'=>$now,'updated_at'=>$now]);$order=(int)$wpdb->insert_id;$orders[$key]=$order;foreach($subtotals as $i=>$subtotal)$wpdb->insert($tables['items'],['order_id'=>$order,'product_id'=>900000+$order+$i,'inventory_id'=>800000+$order+$i,'quantity'=>1,'unit_price'=>(string)$subtotal,'subtotal'=>(string)$subtotal,'created_at'=>$now,'updated_at'=>$now]);$wpdb->insert($tables['payments'],['payment_reference'=>$run.'-'.$key,'customer_id'=>$users['a'],'amount'=>(string)$orderTotal,'currency'=>'CLP','status'=>$paymentStatus,'paid_at'=>$paymentStatus==='paid'?$paidAt:null,'created_at'=>$now,'updated_at'=>$now]);$payment=(int)$wpdb->insert_id;$payments[]=$payment;$wpdb->insert($tables['payment_orders'],['payment_id'=>$payment,'order_id'=>$order,'created_at'=>$now]);};
 $makeOrder('paid-a1',$stores['A1'],'paid','paid',$recent,[1000,500]);$makeOrder('paid-a1-2',$stores['A1'],'paid','paid',$recent,[2500]);$makeOrder('pending-a1',$stores['A1'],'reserved','pending',$recent,[9000]);$makeOrder('old-a2',$stores['A2'],'paid','paid',$old,[7000]);$makeOrder('paid-ab',$stores['AB'],'paid','paid',$recent,[3000]);$makeOrder('paid-b',$stores['B'],'paid','paid',$recent,[9900]);
 $repo=new ZonalSalesRepository();$from=(new DateTimeImmutable($now))->modify('-29 days')->setTime(0,0)->format('Y-m-d H:i:s');$to=(new DateTimeImmutable($now))->modify('+1 day')->setTime(0,0)->format('Y-m-d H:i:s');
 $writes=0;$guard=static function(string $sql)use(&$writes):string{if(preg_match('/^\s*(INSERT|UPDATE|DELETE|REPLACE|ALTER|CREATE|DROP|TRUNCATE)\b/i',$sql))$writes++;return $sql;};add_filter('query',$guard);try{$a=$repo->report($users['a'],false,$from,$to,'sales','desc',1,20);$b=$repo->report($users['b'],false,$from,$to,'sales','desc',1,20);$empty=$repo->report($users['a'],false,'2000-01-01 00:00:00','2000-01-02 00:00:00','name','asc',1,20);}finally{remove_filter('query',$guard);}
 zsAssert($writes===0,'El reporte ejecutó escrituras.');zsAssert($a['summary']===['active_stores'=>2,'paid_orders'=>3,'product_sales'=>'7000.00','average_ticket'=>'2333.33'],'Resumen zonal A incorrecto: '.wp_json_encode($a['summary']));zsAssert($b['summary']===['active_stores'=>1,'paid_orders'=>1,'product_sales'=>'9900.00','average_ticket'=>'9900.00'],'Aislamiento zonal B incorrecto.');
 $names=array_column($a['items'],'minimarket');zsAssert(!in_array($run.' B',$names,true)&&$names[0]===$run.' A1','Orden/territorio incorrecto.');zsAssert($empty['summary']['paid_orders']===0&&$empty['summary']['average_ticket']==='0.00','Periodo vacío incorrecto.');
 $json=wp_json_encode($a);foreach(['email','phone','rut','address','customer','buy_order','session_id','inventory_id','courier'] as $private)zsAssert(!str_contains(strtolower((string)$json),$private),'Dato privado expuesto: '.$private);
 do_action('rest_api_init');wp_set_current_user($users['a']);$call=static function(array $query,bool $nonce=true):WP_REST_Response{$request=new WP_REST_Request('GET','/veciahorra/v1/zonal/sales');if($nonce)$request->set_header('X-WP-Nonce',wp_create_nonce('wp_rest'));$request->set_query_params($query);return rest_do_request($request);};
 zsAssert($call(['period'=>'7'])->get_status()===200,'Periodo 7 días rechazado.');zsAssert($call(['period'=>'custom','from'=>(new DateTimeImmutable($now))->modify('-50 days')->format('Y-m-d'),'to'=>(new DateTimeImmutable($now))->format('Y-m-d')])->get_status()===200,'Rango personalizado rechazado.');zsAssert($call(['period'=>'custom','from'=>'2024-01-01','to'=>'2025-01-01'])->get_status()===422,'Rango mayor a 366 días aceptado.');
 foreach(['sector_id'=>(string)$zones[1],'store_id'=>(string)$stores['A1'],'user_id'=>(string)$users['b'],'zonal_user_id'=>(string)$users['b']] as $key=>$value)zsAssert($call(['period'=>'30',$key=>$value])->get_status()===422,'Manipulación aceptada: '.$key);zsAssert($call(['period'=>'30'],false)->get_status()===403,'Nonce ausente aceptado.');
 echo "ZONAL_SALES_RUNTIME=PASS one_zone=PASS multi_zone=PASS separate_zonals=PASS active_count=PASS paid_only=PASS product_sales=PASS delivery_excluded=PASS periods=PASS average=PASS last_sale=PASS sorting=PASS privacy=PASS writes=0\n";
} finally {
 wp_set_current_user(0);if($payments){$ids=implode(',',array_map('intval',$payments));$wpdb->query("DELETE FROM {$tables['payment_orders']} WHERE payment_id IN ({$ids})");$wpdb->query("DELETE FROM {$tables['payments']} WHERE id IN ({$ids})");}if($orders){$ids=implode(',',array_map('intval',$orders));$wpdb->query("DELETE FROM {$tables['items']} WHERE order_id IN ({$ids})");$wpdb->query("DELETE FROM {$tables['orders']} WHERE id IN ({$ids})");}if($stores){$ids=implode(',',array_map('intval',$stores));$wpdb->query("DELETE FROM {$tables['store_zones']} WHERE store_id IN ({$ids})");$wpdb->query("DELETE FROM {$tables['stores']} WHERE id IN ({$ids})");}if($users){$ids=implode(',',array_map('intval',$users));$wpdb->query("DELETE FROM {$tables['assignments']} WHERE user_id IN ({$ids})");foreach($users as $id)wp_delete_user($id);}if($zones){$ids=implode(',',array_map('intval',$zones));$wpdb->query("DELETE FROM {$tables['zones']} WHERE id IN ({$ids})");}
}
