<?php
declare(strict_types=1);
require_once dirname(__DIR__,5).'/wp-load.php';
require_once ABSPATH.WPINC.'/class-wp-admin-bar.php';
use VeciAhorra\Modules\CustomerAccess\CustomerAccessModule;
use VeciAhorra\Modules\ZonalAdmin\Identity\ZonalAdminRole;
function z5Assert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
global $wpdb;$module=new CustomerAccessModule();$zonal=get_user_by('login','capacitacion_zonal');z5Assert($zonal instanceof WP_User,'Usuario zonal ausente.');$destination=admin_url('admin.php?page=veciahorra-zonal-stores');
z5Assert($module->destinationFor($zonal)===$destination,'Destino zonal incorrecto.');z5Assert($module->loginRedirect('https://evil.example/','https://evil.example/',$zonal)===$destination,'Redirect externo aceptado.');z5Assert($module->loginRedirect(admin_url('users.php'),admin_url('users.php'),$zonal)===$destination,'Superficie global aceptada.');wp_set_current_user($zonal->ID);z5Assert($module->allowZonalAdminAccess(true)===false,'WooCommerce bloquea panel zonal.');
$args=(object)['theme_location'=>'primary'];$customer=(object)['url'=>home_url('/mis-compras/'),'title'=>'Mis compras'];$public=(object)['url'=>home_url('/'),'title'=>'Inicio'];wp_set_current_user($zonal->ID);$filtered=$module->filterRoleMenuItems([$public,$customer],$args);z5Assert(count(array_filter($filtered,static fn(object $i):bool=>str_contains((string)$i->url,'mis-compras')))===0,'Mis compras visible al zonal.');$html=$module->appendAccessLinks('',$args);z5Assert(substr_count($html,'Mi panel')===1&&str_contains($html,esc_url($destination))&&!str_contains($html,'mis-compras'),'Header zonal incorrecto.');z5Assert(!current_user_can('manage_options')&&!current_user_can('edit_users')&&!current_user_can('activate_plugins'),'Privilegios globales filtrados.');
$find=static function(string $role)use($wpdb):WP_User{$id=(int)$wpdb->get_var($wpdb->prepare("SELECT user_id FROM {$wpdb->usermeta} WHERE meta_key=%s AND meta_value LIKE %s ORDER BY user_id LIMIT 1",$wpdb->prefix.'capabilities','%'.$wpdb->esc_like($role).'%'));$u=get_userdata($id);z5Assert($u instanceof WP_User,"Rol {$role} ausente.");return $u;};
$admin=$find('administrator');$minimarket=$find('veciahorra_minimarket');$courier=$find('veciahorra_courier');$provider=$find('veciahorra_service_provider');$client=$find('customer');z5Assert($module->destinationFor($admin)===admin_url('admin.php?page=veciahorra'),'Admin alterado.');z5Assert(str_contains($module->destinationFor($minimarket),'panel-minimarket'),'Minimarket alterado.');z5Assert(str_contains($module->destinationFor($courier),'panel-repartidor'),'Courier alterado.');z5Assert(str_contains($module->destinationFor($provider),'panel-prestador'),'Prestador alterado.');z5Assert(str_contains($module->destinationFor($client),'mis-compras'),'Cliente alterado.');
$bar=static function():WP_Admin_Bar{$instance=new WP_Admin_Bar();foreach(['wp-logo','site-name','command-palette','my-account','user-info','logout'] as $id)$instance->add_node(['id'=>$id,'title'=>$id]);return $instance;};wp_set_current_user($zonal->ID);$zonalBar=$bar();$module->simplifyZonalAdminBar($zonalBar);foreach(['wp-logo','site-name','command-palette'] as $id)z5Assert($zonalBar->get_node($id)===null,"Nodo {$id} visible al zonal.");foreach(['my-account','user-info','logout'] as $id)z5Assert($zonalBar->get_node($id)!==null,"Nodo {$id} perdido al zonal.");wp_set_current_user($admin->ID);$adminBar=$bar();$module->simplifyZonalAdminBar($adminBar);foreach(['wp-logo','site-name','command-palette','my-account','user-info','logout'] as $id)z5Assert($adminBar->get_node($id)!==null,"Admin alterado: {$id}.");
$source=(string)file_get_contents(dirname(__DIR__,2).'/app/Modules/CustomerAccess/CustomerAccessModule.php');z5Assert(str_contains($source,"admin_url('admin.php?page=veciahorra-zonal-stores')")&&!str_contains($source,'capacitacion_zonal')&&!str_contains($source,'456'),'Autoridad zonal no dinamica.');z5Assert(str_contains($source,"\$pagenow === 'profile.php'")&&str_contains($source,'wp_doing_ajax()'),'Excepciones admin incompletas.');$guards=["remove_node('wp-logo')","remove_node('site-name')","remove_node('command-palette')","remove_action('admin_enqueue_scripts', 'wp_enqueue_command_palette_assets')","&& ! current_user_can('manage_options')"];$mutations=0;foreach($guards as $guard){$before=substr_count($source,$guard);z5Assert($before>0,"Guard Z6 ausente: {$guard}.");$mutated=preg_replace('/'.preg_quote($guard,'/').'/', '',$source,1);z5Assert(is_string($mutated)&&substr_count($mutated,$guard)===$before-1,"Mutacion Z6 inerte: {$guard}.");$mutations++;}z5Assert(!str_contains($source,'show_admin_bar(false)')&&!str_contains($source,'display: none'),'Ocultamiento global detectado.');wp_set_current_user(0);echo "ZONAL_ADMIN_Z5_ROUTING=PASS destination=PASS precedence=admin,zonal,commercial,customer external=BLOCKED global=BLOCKED customer_nav=HIDDEN other_roles=PASS loops=0 z6=PASS admin_bar=SIMPLIFIED account=PASS profile=PASS logout=PASS command_palette=DISABLED administrator=PRESERVED adversarial_mutations={$mutations}/{$mutations} database_writes=0 wp_options_writes=0\n";
