<?php
declare(strict_types=1);
require_once dirname(__DIR__,5).'/wp-load.php';require_once ABSPATH.'wp-admin/includes/user.php';
use VeciAhorra\Modules\ZonalAdmin\Identity\ZonalAdminRole;use VeciAhorra\Modules\ZonalAdmin\Repositories\ZonalSalesRepository;
function zdAssert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}global $wpdb;$p=$wpdb->prefix.'va_';$run='zd_'.bin2hex(random_bytes(5));$now=current_time('mysql');$user=0;$zone=0;$stores=[];$order=0;$payments=[];
try{$admin=(int)$wpdb->get_var("SELECT user_id FROM {$wpdb->usermeta} WHERE meta_key='{$wpdb->prefix}capabilities' AND meta_value LIKE '%administrator%' ORDER BY user_id LIMIT 1");$created=wp_create_user($run,wp_generate_password(30),$run.'@example.test');zdAssert(!is_wp_error($created),'Usuario');$user=(int)$created;(new WP_User($user))->set_role(ZonalAdminRole::ROLE);$wpdb->insert($p.'service_zones',['commune'=>$run,'name'=>$run,'status'=>'active','created_at'=>$now,'updated_at'=>$now]);$zone=(int)$wpdb->insert_id;$wpdb->insert($p.'zonal_admin_service_zones',['user_id'=>$user,'service_zone_id'=>$zone,'created_at'=>$now,'created_by'=>$admin]);foreach([['eligible','complete',$now],['incomplete','draft',null]]as[$key,$onboarding,$approved]){$wpdb->insert($p.'stores',['business_name'=>$run.' '.$key,'legal_name'=>$run,'owner_name'=>'Fixture','rut'=>substr(hash('sha256',$run.$key),0,16),'email'=>$run.$key.'@example.test','phone'=>'0','status'=>'active','onboarding_status'=>$onboarding,'approved_at'=>$approved,'created_at'=>$now,'updated_at'=>$now]);$stores[$key]=(int)$wpdb->insert_id;$wpdb->insert($p.'store_service_zones',['store_id'=>$stores[$key],'zone_id'=>$zone,'assigned_by'=>$admin,'assigned_at'=>$now]);}
 $wpdb->insert($p.'orders',['customer_id'=>$user,'minimarket_id'=>$stores['eligible'],'total'=>'1900.00','status'=>'paid','store_fulfillment_status'=>'awaiting_confirmation','created_at'=>$now,'updated_at'=>$now]);$order=(int)$wpdb->insert_id;$wpdb->insert($p.'order_items',['order_id'=>$order,'product_id'=>910000+$order,'inventory_id'=>920000+$order,'quantity'=>1,'unit_price'=>'1500.00','subtotal'=>'1500.00','created_at'=>$now,'updated_at'=>$now]);foreach([['failed',null],['paid',$now]]as$i=>[$status,$paidAt]){$wpdb->insert($p.'payments',['payment_reference'=>$run.'-'.$i,'customer_id'=>$user,'amount'=>'1900.00','currency'=>'CLP','status'=>$status,'paid_at'=>$paidAt,'created_at'=>$now,'updated_at'=>$now]);$payments[]=(int)$wpdb->insert_id;} $wpdb->insert($p.'payment_orders',['payment_id'=>$payments[1],'order_id'=>$order,'created_at'=>$now]);
 $repo=new ZonalSalesRepository();$from=(new DateTimeImmutable($now))->modify('-1 day')->format('Y-m-d H:i:s');$to=(new DateTimeImmutable($now))->modify('+1 day')->format('Y-m-d H:i:s');$check=static function(string $stage)use($repo,$user,$from,$to):void{$report=$repo->report($user,false,$from,$to,'sales','desc',1,20);zdAssert($report['summary']['active_stores']===1,$stage.': lifecycle compuesto');zdAssert($report['summary']['paid_orders']===1&&$report['summary']['product_sales']==='1500.00'&&$report['summary']['average_ticket']==='1500.00',$stage.': venta perdida o duplicada '.wp_json_encode($report['summary']));};
 $check('newly_paid');foreach(['confirmed','preparing','ready_for_pickup']as$stage){$wpdb->update($p.'orders',['store_fulfillment_status'=>$stage,'updated_at'=>$now],['id'=>$order]);$check($stage);} $check('courier_assigned');$check('picked_up');$wpdb->update($p.'orders',['status'=>'delivered','updated_at'=>$now],['id'=>$order]);$check('delivered');$wpdb->update($p.'orders',['status'=>'paid','updated_at'=>$now],['id'=>$order]);$check('pickup_completed');
 $wpdb->insert($p.'payments',['payment_reference'=>$run.'-hostile','customer_id'=>$user,'amount'=>'1900.00','currency'=>'CLP','status'=>'paid','paid_at'=>$now,'created_at'=>$now,'updated_at'=>$now]);$hostile=(int)$wpdb->insert_id;$payments[]=$hostile;$suppressed=$wpdb->suppress_errors(true);$duplicate=$wpdb->insert($p.'payment_orders',['payment_id'=>$hostile,'order_id'=>$order,'created_at'=>$now]);$wpdb->suppress_errors($suppressed);zdAssert($duplicate===false,'payment_orders permitió múltiples relaciones por Order.');$check('hostile_payment_relation');
 $schema=(string)file_get_contents(dirname(__DIR__,2).'/app/Database/Schemas/PaymentOrderSchema.php');$repository=(string)file_get_contents(dirname(__DIR__,2).'/app/Modules/ZonalAdmin/Repositories/ZonalSalesRepository.php');$storeFlow=(string)file_get_contents(dirname(__DIR__,2).'/app/Modules/Minimarket/Repository/MinimarketRepository.php');$delivery=(string)file_get_contents(dirname(__DIR__,2).'/app/Modules/Couriers/Repository/CourierDeliveryRepository.php');$pickup=(string)file_get_contents(dirname(__DIR__,2).'/app/Modules/Fulfillment/Completion/Service/FulfillmentCompletionProcessor.php');zdAssert(str_contains($schema,"unique('order_id'")&&str_contains($repository,'GROUP BY po.order_id')&&str_contains($repository,"o.status IN ('paid','delivered')"),'Autoridad de unicidad/durabilidad ausente.');zdAssert(str_contains($storeFlow,'SET store_fulfillment_status=')&&str_contains($delivery,"SET status='delivered'")&&str_contains($pickup,'pickup_fulfillment_completed'),'Autoridades fulfillment inesperadas.');echo "ZONAL_SALES_DURABILITY=PASS statuses=reserved,paid,delivered confirmed=PASS preparing=PASS ready_for_pickup=PASS assigned=PASS picked_up=PASS delivered=PASS pickup_completed=PASS failed_then_paid=PASS hostile_relation=REJECTED one_order=PASS one_subtotal=PASS lifecycle=COMPOSITE\n";
}finally{if($order){$wpdb->delete($p.'payment_orders',['order_id'=>$order]);foreach($payments as$payment)$wpdb->delete($p.'payments',['id'=>$payment]);$wpdb->delete($p.'order_items',['order_id'=>$order]);$wpdb->delete($p.'orders',['id'=>$order]);}if($stores){foreach($stores as$store)$wpdb->delete($p.'store_service_zones',['store_id'=>$store]);foreach($stores as$store)$wpdb->delete($p.'stores',['id'=>$store]);}if($user){$wpdb->delete($p.'zonal_admin_service_zones',['user_id'=>$user]);wp_delete_user($user);}if($zone)$wpdb->delete($p.'service_zones',['id'=>$zone]);}
