<?php
declare(strict_types=1);
function z3Assert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$root=dirname(__DIR__,2);$read=static fn(string $p):string=>(string)file_get_contents($root.'/'.$p);
$s=['page'=>$read('app/Modules/ZonalAdmin/Admin/ZonalStoresPage.php'),'view'=>$read('app/Modules/ZonalAdmin/Views/zonal-stores.php'),'js'=>$read('assets/admin/js/modules/zonal-stores/app.js'),'css'=>$read('assets/admin/css/zonal-stores.css'),'menu'=>$read('app/Admin/Menu.php'),'app'=>$read('app/Core/Application.php')];
$validate=static function(array $s):array{$e=[];$need=static function(bool $ok,string $code)use(&$e):void{if(!$ok)$e[]=$code;};
$need(str_contains($s['page'],"PAGE_SLUG = 'veciahorra-zonal-stores'")&&str_contains($s['page'],'Minimarkets de mi zona'),'Z01_MENU');$need(substr_count($s['view'],'<h1')===1&&str_contains($s['view'],'Administración zonal'),'Z02_H1');$need(str_contains($s['page'],'ZonalAdminRole::CAPABILITY_READ')&&str_contains($s['page'],"current_user_can('manage_options')"),'Z03_ACCESS');$need(str_contains($s['page'],'$hookSuffix !== $this->pageHook'),'Z04_ASSET_SCOPE');$need(str_contains($s['page'],'Config::PLUGIN_VERSION')&&str_contains($s['page'],"wp_create_nonce('wp_rest')"),'Z05_CONFIG');$need(str_contains($s['view'],'data-va-zonal-stores')&&str_contains($s['js'],"querySelector('[data-va-zonal-stores]')"),'Z06_ROOT');$need(str_contains($s['js'],"config.restUrl+'/'+String(Number(id))")&&str_contains($s['js'],"+'/transitions"),'Z07_ENDPOINTS');$need(!str_contains($s['js'],'/stores/')&&!str_contains($s['js'],'customer-panel')&&!str_contains($s['js'],'catalog'),'Z08_NO_GLOBAL_ENDPOINT');$need(str_contains($s['js'],'Cargando solicitudes')&&str_contains($s['js'],'Listado actualizado')&&str_contains($s['js'],'No hay solicitudes')&&str_contains($s['js'],'Reintentar'),'Z09_UI_STATES');$need(str_contains($s['js'],'AbortController')&&str_contains($s['js'],'sequence!==state.sequence'),'Z10_STALE');$need(str_contains($s['view'],'data-va-search')&&str_contains($s['view'],'data-va-state')&&str_contains($s['view'],'data-va-prev')&&str_contains($s['view'],'data-va-next'),'Z11_CONTROLS');$need(str_contains($s['js'],'item.service_zones')&&str_contains($s['js'],'decision_history'),'Z12_DETAIL');$need(str_contains($s['js'],"['approve','Aprobar']")&&str_contains($s['js'],"['observe','Observar']")&&str_contains($s['js'],"['reject','Rechazar']")&&!str_contains($s['js'],"['activate'"),'Z13_ACTIONS');$need(str_contains($s['js'],'maxLength=1000')&&str_contains($s['js'],'expected_updated_at'),'Z14_REASON_CAS');$need(str_contains($s['js'],'state.submitting')&&str_contains($s['js'],'409'),'Z15_DOUBLE_CAS');$need(str_contains($s['js'],'textContent')&&!str_contains($s['js'],'innerHTML'),'Z16_ESCAPING');$need(!preg_match('/localStorage|sessionStorage/',$s['js']),'Z17_STORAGE');$need(str_contains($s['view'],'aria-live="polite"')&&str_contains($s['js'],"event.key==='Escape'"),'Z18_A11Y');$need(str_contains($s['css'],'min-height:44px')&&str_contains($s['css'],'prefers-reduced-motion')&&str_contains($s['css'],'overflow-wrap:anywhere'),'Z19_RESPONSIVE');$need(str_contains($s['app'],'ZonalStoresPage::class')&&str_contains($s['menu'],'ZonalAdminRole::CAPABILITY_READ'),'Z20_COMPOSITION');return $e;};
z3Assert($validate($s)===[],'Base Z3: '.implode(',',$validate($s)));$mutations=[['page','veciahorra-zonal-stores','zonal-broken'],['view','<h1','<h2'],['page',"current_user_can('manage_options')","current_user_can('read')"],['page','$hookSuffix !== $this->pageHook','false'],['page',"wp_create_nonce('wp_rest')","'nonce'"],['view','data-va-zonal-stores','data-va-broken'],['js',"+'/transitions'","+'/activate'"],['js',"'use strict';","'use strict'; fetch('/veciahorra/v1/stores/');"],['js','Listado actualizado','Lista lista'],['js','AbortController','LegacyRequest'],['view','data-va-search','data-va-query'],['js','decision_history','private_history'],['js',"['approve','Aprobar']","['activate','Activar']"],['js','maxLength=1000','maxLength=0'],['js','state.submitting','state.ignored'],['js','textContent','innerHTML'],['js',"'use strict';","'use strict'; localStorage.setItem('x','y');"],['view','aria-live="polite"','aria-live="off"'],['css','min-height:44px','min-height:20px'],['app','ZonalStoresPage::class','ZonalStoresPageRemoved::class']];foreach($mutations as $i=>[$key,$from,$to]){$m=$s;z3Assert(str_contains($m[$key],$from),'Fixture '.($i+1).' ausente');$m[$key]=str_replace($from,$to,$m[$key]);z3Assert($validate($m)!==[],'Mutacion '.($i+1).' no rechazada');}
echo "ZONAL_ADMIN_Z3_STATIC=PASS adversarials=20/20 menu=PASS assets=SCOPED endpoints=ZONAL_ONLY accessibility=PASS\n";
