<?php
declare(strict_types=1);
namespace VeciAhorra\Modules\ServiceProviders\Admin;
use VeciAhorra\Modules\ServiceProviders\Domain\ServiceCatalog;use VeciAhorra\Modules\ServiceProviders\Domain\ServicePlanCatalog;use VeciAhorra\Modules\ServiceProviders\Service\ServiceProviderService;
final class ServiceProviderAdminPage
{
 public function __construct(private ServiceProviderService $service=new ServiceProviderService()){}public function register():void{add_action('admin_menu',[$this,'menu']);}public function menu():void{add_submenu_page('veciahorra','Prestadores de Servicios','Prestadores de Servicios','manage_options','veciahorra-service-providers',[$this,'render']);}
 public function render():void
 {
  if(!current_user_can('manage_options'))wp_die('No autorizado.');$message='';if($_SERVER['REQUEST_METHOD']==='POST'){check_admin_referer('va_provider_admin');try{$this->service->adminTransition(absint($_POST['provider_id']??0),sanitize_key((string)($_POST['transition']??'')),(string)($_POST['observation']??''));$message='Estado actualizado.';}catch(\Throwable$e){$message=$e->getMessage();}}
  $requestedPlan=ServicePlanCatalog::canonical(isset($_GET['plan'])?wp_unslash($_GET['plan']):null);$filters=['status'=>sanitize_key((string)($_GET['status']??'')),'plan'=>$requestedPlan??'','category_key'=>sanitize_key((string)($_GET['category']??''))];echo'<div class="wrap"><h1>Prestadores de Servicios</h1>';if($message)echo'<div class="notice notice-info"><p>'.esc_html($message).'</p></div>';echo'<form><input type="hidden" name="page" value="veciahorra-service-providers"><select name="status"><option value="">Todos los estados</option>';foreach(['draft','in_review','observed','approved','published','inactive']as$s)echo'<option '.selected($filters['status'],$s,false).'>'.$s.'</option>';echo'</select><select name="plan"><option value="">Todos los planes</option><option value="local" '.selected($filters['plan'],'local',false).'>Local</option><option value="featured" '.selected($filters['plan'],'featured',false).'>Destacado</option><option value="communal" '.selected($filters['plan'],'communal',false).'>Comunal</option></select><select name="category"><option value="">Todas las categorías</option>';foreach(ServiceCatalog::CATEGORIES as$k=>$c)echo'<option value="'.esc_attr($k).'">'.esc_html($c['label']).'</option>';echo'</select><button class="button">Filtrar</button></form><table class="widefat"><thead><tr><th>ID</th><th>Prestador</th><th>Plan</th><th>Categoría</th><th>Estado</th><th>RUT / contacto</th><th>Observación / acciones</th></tr></thead><tbody>';
  foreach($this->service->repository()->all($filters)as$r){echo'<tr><td>'.(int)$r['id'].'</td><td>'.esc_html($r['full_name'].' · '.$r['business_name']).'</td><td>'.esc_html(ServicePlanCatalog::label((string)$r['plan'])).'</td><td>'.esc_html($r['category_key'].' / '.$r['subcategory_key']).'</td><td>'.esc_html($r['status']).'</td><td>'.esc_html($r['rut'].' · '.$r['email'].' · '.$r['phone']).'</td><td><p>'.esc_html($r['admin_observation']).'</p>'.$this->actions((int)$r['id'],$r['status']).'</td></tr>';}
  echo'</tbody></table></div>';
 }
 private function actions(int$id,string$status):string{$map=['in_review'=>['observed','approved'],'observed'=>['inactive'],'approved'=>['published','inactive'],'published'=>['inactive']];$html='';foreach($map[$status]??[]as$t){$html.='<form method="post" style="display:inline-block;margin:2px">'.wp_nonce_field('va_provider_admin','_wpnonce',true,false).'<input type="hidden" name="provider_id" value="'.$id.'"><input type="hidden" name="transition" value="'.$t.'">'.($t==='observed'?'<input name="observation" required placeholder="Observación">':'').'<button class="button">'.esc_html($t).'</button></form>';}return$html;}
}
