<?php
declare(strict_types=1);
namespace VeciAhorra\Modules\Products\Import;
use VeciAhorra\Modules\Products\Domain\ProductLifecycleContract;

final class ProductBulkImportService
{
    public function __construct(private ProductBulkImportRepository $repository=new ProductBulkImportRepository(),private ProductLifecycleContract $lifecycle=new ProductLifecycleContract()){}
    public function preview(array $rows,array $parseErrors,array $images=[]):array
    {
        $accepted=[];$errors=$parseErrors;$declared=[];
        foreach($rows as $row){$resolved=$this->resolve($row,$errors);if($resolved===null)continue;if($row['image']!==''){$declared[$row['image']]=true;if(!isset($images[$row['image']])){$errors[]=$this->error($row,'La imagen declarada no está presente en el ZIP.');continue;}if(strcasecmp(pathinfo($row['image'],PATHINFO_FILENAME),$row['sku'])!==0){$errors[]=$this->error($row,'La imagen debe llamarse exactamente como el SKU.');continue;}$resolved['staged_image']=$images[$row['image']];}
            $product=$this->repository->product($row['sku']);try{$this->lifecycle->assertTransition((string)($product['status']??'draft'),$row['status']);}catch(\Throwable){$errors[]=$this->error($row,'La transición de estado no está permitida por el lifecycle productivo.');continue;}$sameImage=$row['image']!==''&&$product!==null&&$this->sameImage((int)($product['image_id']??0),$this->imageBytes($images[$row['image']]));if($sameImage)unset($resolved['staged_image']);$payload=$this->payload($row,$resolved,$product['image_id']??null);$change=$product===null?'create':($this->same($product,$payload)&&$sameImage?'unchanged':($row['image']===''&&$this->same($product,$payload)?'unchanged':'update'));$accepted[]=$row+$resolved+['product_id'=>$product===null?null:(int)$product['id'],'change'=>$change,'snapshot'=>$this->snapshot($product),'replaces_image'=>$row['image']!==''&&!$sameImage&&!empty($product['image_id'])];
        }
        foreach($images as $name=>$path)if(!isset($declared[$name]))$errors[]=['line'=>0,'sku'=>'','message'=>'Imagen sin SKU declarado en el CSV: '.$name.'.'];
        return['rows'=>$accepted,'errors'=>$errors,'created'=>$this->count($accepted,'create'),'updated'=>$this->count($accepted,'update'),'unchanged'=>$this->count($accepted,'unchanged')];
    }
    public function import(array $preview):array
    {
        if(!empty($preview['errors']))throw new \InvalidArgumentException('El archivo contiene errores. Corrige todas las filas rechazadas y vuelve a cargarlo. No se aplicó ningún cambio.');
        $attachments=[];$inventoryBefore=$this->repository->inventoryCount();$result=['created'=>0,'updated'=>0,'unchanged'=>0,'rejected'=>0];$this->repository->begin();
        try{$rows=$preview['rows'];usort($rows,static fn($a,$b)=>strcmp($a['sku'],$b['sku']));foreach($rows as $row){$current=$this->repository->product($row['sku'],true);if(!hash_equals($row['snapshot'],$this->snapshot($current)))throw new \RuntimeException('El catálogo cambió después de la vista previa.');$this->lifecycle->assertTransition((string)($current['status']??'draft'),$row['status']);$imageId=$current['image_id']??null;if(!empty($row['staged_image'])){$attachment=$this->attachment($this->imageBytes($row['staged_image']),$row['image']);$attachments[]=$attachment;$imageId=$attachment['id'];}$payload=$this->payload($row,$row,$imageId);if($current===null){$payload['slug']=$this->slug($row['name'],$row['sku']);$this->repository->create($payload,current_time('mysql'));$result['created']++;}elseif($this->same($current,$payload))$result['unchanged']++;else{$this->repository->update((int)$current['id'],$payload,(string)$current['updated_at'],$this->repository->nextUpdatedAt((string)$current['updated_at']));$result['updated']++;}}
            if($this->repository->inventoryCount()!==$inventoryBefore)throw new \RuntimeException('La importación intentó modificar inventario.');$this->repository->commit();return$result;
        }catch(\Throwable $e){$this->repository->rollback();foreach(array_reverse($attachments)as$a){foreach($a['files']as$file)if(is_file($file))@unlink($file);}throw new \RuntimeException('La importación fue cancelada sin aplicar cambios. '.$e->getMessage(),0,$e);}
    }
    private function resolve(array $row,array &$errors):?array{$category=$this->repository->term('product_cat',$row['category'],0);if($category===null){$errors[]=$this->error($row,'La categoría no existe o es ambigua.');return null;}$categoryId=(int)$category['term_id'];if($row['subcategory']!==''){$sub=$this->repository->term('product_cat',$row['subcategory'],$categoryId);if($sub===null){$errors[]=$this->error($row,'La subcategoría no existe bajo la categoría indicada.');return null;}$categoryId=(int)$sub['term_id'];}$brandId=$this->optionalTerm($row,'brand','product_brand',$errors);$unitId=$this->optionalTerm($row,'unit','pa_unidad',$errors);if($brandId===false||$unitId===false)return null;return['category_id'=>$categoryId,'brand_id'=>$brandId,'unit_id'=>$unitId];}
    private function optionalTerm(array $row,string $field,string $taxonomy,array &$errors):int|null|false{if($row[$field]==='')return null;$term=$this->repository->term($taxonomy,$row[$field]);if($term===null){$errors[]=$this->error($row,ucfirst($field).' no existe o es ambiguo.');return false;}return(int)$term['term_id'];}
    private function payload(array $r,array $x,mixed $imageId):array{return['name'=>$r['name'],'sku'=>$r['sku'],'description'=>$r['description']===''?null:$r['description'],'category_id'=>$x['category_id'],'brand_id'=>$x['brand_id'],'unit_id'=>$x['unit_id'],'image_id'=>$imageId===null?null:(int)$imageId,'status'=>$r['status']];}
    private function same(array $p,array $d):bool{foreach(['name','sku','description','category_id','brand_id','unit_id','image_id','status']as$k)if((string)($p[$k]??'')!==(string)($d[$k]??''))return false;return true;}
    private function snapshot(?array $p):string{return hash('sha256',wp_json_encode($p));}
    private function sameImage(int $id,string $bytes):bool{$path=$id>0?get_attached_file($id):false;return is_string($path)&&is_file($path)&&hash_equals(hash('sha256',$bytes),hash_file('sha256',$path));}
    private function imageBytes(mixed $image):string{if(is_string($image))return$image;if(is_array($image)&&isset($image['path'],$image['sha256'])&&is_string($image['path'])&&is_file($image['path'])){$bytes=file_get_contents($image['path']);if(is_string($bytes)&&hash_equals((string)$image['sha256'],hash('sha256',$bytes)))return$bytes;}throw new \RuntimeException('La imagen en staging ya no está disponible o cambió.');}
    private function slug(string $name,string $sku):string{$base=sanitize_title($name);$slug=$base;for($i=0;$this->repository->slugExists($slug);$i++)$slug=$base.'-'.sanitize_title($sku).($i?'-'.$i:'');return$slug;}
    private function attachment(string $bytes,string $name):array{require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/image.php';require_once ABSPATH.'wp-admin/includes/media.php';$copy=wp_tempnam($name);if(!$copy||file_put_contents($copy,$bytes)!==strlen($bytes))throw new \RuntimeException('No fue posible preparar una imagen.');$id=media_handle_sideload(['name'=>$name,'tmp_name'=>$copy,'error'=>0,'size'=>strlen($bytes)],0);if(is_wp_error($id)){@unlink($copy);throw new \RuntimeException('No fue posible incorporar una imagen válida.');}$main=get_attached_file((int)$id);$files=is_string($main)?[$main]:[];$meta=wp_get_attachment_metadata((int)$id);if(is_string($main)&&is_array($meta)){foreach($meta['sizes']??[]as$s)if(!empty($s['file']))$files[]=dirname($main).DIRECTORY_SEPARATOR.$s['file'];}return['id'=>(int)$id,'files'=>array_values(array_unique($files))];}
    private function error(array $r,string $m):array{return['line'=>(int)$r['line'],'sku'=>(string)$r['sku'],'message'=>$m];}
    private function count(array $r,string $c):int{return count(array_filter($r,static fn($x)=>$x['change']===$c));}
}
