<?php
declare(strict_types=1);
namespace VeciAhorra\Modules\ServiceProviders\Service;
use VeciAhorra\Modules\ServiceProviders\Domain\ServiceCatalog;use VeciAhorra\Modules\ServiceProviders\Repository\ServiceProviderRepository;
final class ServiceProviderService
{
 public function __construct(private ServiceProviderRepository $repo=new ServiceProviderRepository()){}
 public function validate(array $p):array
 {
  $allowed=['provider_id','full_name','rut','email','phone','plan','terms_accepted','photo_id','business_name','category_key','subcategory_key','description','commune','coverage','specialties','experience_years','schedule','emergency_service','whatsapp','contact_email'];if(array_diff(array_keys($p),$allowed)!==[])throw new \InvalidArgumentException('Campos no admitidos.');
  $s=static fn(string $k,int $max,bool $required=false):?string=>($v=sanitize_text_field((string)($p[$k]??'')))===''?($required?throw new \InvalidArgumentException("{$k} es obligatorio."):null):(strlen($v)>$max?throw new \InvalidArgumentException("{$k} excede longitud."):$v);
  $plan=(string)($p['plan']??'');if(!in_array($plan,['local','featured'],true))throw new \InvalidArgumentException('Plan invalido.');$category=(string)($p['category_key']??'');$subcategory=(string)($p['subcategory_key']??'');if(!ServiceCatalog::valid($category,$subcategory))throw new \InvalidArgumentException('Categoria o subcategoria invalida.');
  $specialties=array_values(array_filter(array_map('sanitize_text_field',(array)($p['specialties']??[]))));if(count($specialties)>5)throw new \InvalidArgumentException('Maximo 5 especialidades.');$photo=absint($p['photo_id']??0);if($photo>0&&!wp_attachment_is_image($photo))throw new \InvalidArgumentException('Foto invalida.');
  $email=$s('email',150,true);$contact=$s('contact_email',150,true);if(!is_email($email)||!is_email($contact))throw new \InvalidArgumentException('Correo invalido.');
  return ['full_name'=>$s('full_name',150,true),'rut'=>$s('rut',20,true),'email'=>$email,'phone'=>$s('phone',30,true),'plan'=>$plan,'terms_accepted'=>!empty($p['terms_accepted'])?1:0,'photo_id'=>$photo?:null,'business_name'=>$s('business_name',180,true),'category_key'=>$category,'subcategory_key'=>$subcategory,'description'=>sanitize_textarea_field((string)($p['description']??'')),'commune'=>$s('commune',120,true),'coverage'=>wp_json_encode(array_values(array_map('sanitize_text_field',(array)($p['coverage']??[])))),'specialties'=>wp_json_encode($specialties),'experience_years'=>max(0,absint($p['experience_years']??0)),'schedule'=>$s('schedule',180),'emergency_service'=>!empty($p['emergency_service'])?1:0,'whatsapp'=>$s('whatsapp',30),'contact_email'=>$contact];
 }
 public function save(int $userId,array $p):array
 {
  $meta=(int)get_user_meta($userId,\VeciAhorra\Modules\ServiceProviders\Identity\ServiceProviderRole::META_KEY,true);$spoof=absint($p['provider_id']??0);if($spoof>0&&$spoof!==$meta)throw new \DomainException('ownership_conflict');$data=$this->validate($p);$now=current_time('mysql',true);
  if($meta===0){$id=$this->repo->create([...$data,'status'=>'draft','admin_observation'=>null,'submitted_at'=>null,'approved_at'=>null,'published_at'=>null,'created_at'=>$now,'updated_at'=>$now]);update_user_meta($userId,\VeciAhorra\Modules\ServiceProviders\Identity\ServiceProviderRole::META_KEY,$id);}
  else{$row=$this->repo->find($meta)??throw new \OutOfBoundsException('not_found');if(!in_array($row['status'],['draft','observed'],true))throw new \DomainException('profile_not_editable');$id=$meta;$this->repo->update($id,[...$data,'updated_at'=>$now]);}
  return $this->private($this->repo->find($id));
 }
 public function submit(int $id):array{$r=$this->repo->find($id)??throw new \OutOfBoundsException();if(!in_array($r['status'],['draft','observed'],true)||!(int)$r['terms_accepted'])throw new \DomainException('cannot_submit');$now=current_time('mysql',true);$this->repo->update($id,['status'=>'in_review','submitted_at'=>$now,'admin_observation'=>null,'updated_at'=>$now]);return $this->private($this->repo->find($id));}
 public function adminTransition(int $id,string $to,?string $observation=null):array{$r=$this->repo->find($id)??throw new \OutOfBoundsException();$allowed=['in_review'=>['observed','approved'],'observed'=>['inactive'],'approved'=>['published','inactive'],'published'=>['inactive'],'inactive'=>[]];if(!in_array($to,$allowed[$r['status']]??[],true))throw new \DomainException('invalid_lifecycle');$now=current_time('mysql',true);$d=['status'=>$to,'updated_at'=>$now];if($to==='observed'){$d['admin_observation']=sanitize_textarea_field((string)$observation);if($d['admin_observation']==='')throw new \InvalidArgumentException('Observacion obligatoria.');}if($to==='approved')$d['approved_at']=$now;if($to==='published')$d['published_at']=$now;$this->repo->update($id,$d);return$this->private($this->repo->find($id));}
 public function private(?array $r):?array{if($r===null)return null;$r['coverage']=json_decode((string)$r['coverage'],true)?:[];$r['specialties']=json_decode((string)$r['specialties'],true)?:[];$r['photo_url']=$r['photo_id']?wp_get_attachment_image_url((int)$r['photo_id'],'medium')?:null:null;return$r;}
 public function public(array $r):array{return['id'=>(int)$r['id'],'photo_url'=>$r['photo_id']?wp_get_attachment_image_url((int)$r['photo_id'],'medium')?:null:null,'name'=>$r['full_name'],'business_name'=>$r['business_name'],'category_key'=>$r['category_key'],'subcategory_key'=>$r['subcategory_key'],'description'=>$r['description'],'commune'=>$r['commune'],'coverage'=>json_decode((string)$r['coverage'],true)?:[],'specialties'=>json_decode((string)$r['specialties'],true)?:[],'experience_years'=>(int)$r['experience_years'],'schedule'=>$r['schedule'],'emergency_service'=>(bool)$r['emergency_service'],'phone'=>$r['phone'],'whatsapp'=>$r['whatsapp'],'contact_email'=>$r['contact_email'],'verified'=>true,'featured'=>$r['plan']==='featured'];}
 public function repository():ServiceProviderRepository{return$this->repo;}
}
