<?php
declare(strict_types=1);
namespace VeciAhorra\Modules\Minimarket\Onboarding\ActivationSession;
use Throwable;use VeciAhorra\Core\Config;
final class StoreOnboardingActivationSessionRepository
{
    public function __construct(private ?\wpdb $db=null,private $reconciliationFactory=null){}
    public function findById(int $id):?StoreOnboardingActivationSession{if($id<1)throw new ActivationSessionException('activation_session_invalid_id');return $this->find('id',$id);}
    public function findByHash(string $hash):?StoreOnboardingActivationSession{$this->hash($hash);return $this->find('session_hash',$hash);}
    public function create(string $hash,int $applicationId,int $verificationId,int $generation,string $now):StoreOnboardingActivationSession
    {
        $this->hash($hash);StoreOnboardingActivationSession::timestamp($now);$expires=StoreOnboardingActivationSession::plus($now,900);$lock=$this->lockName('session',$hash);
        return $this->locked([$lock,$this->lockName('verification-generation',$verificationId.':'.$generation)],function()use($hash,$applicationId,$verificationId,$generation,$now,$expires){$existing=$this->find('session_hash',$hash,true);if($existing!==null){if($existing->applicationId===$applicationId&&$existing->verificationId===$verificationId&&$existing->generation===$generation&&$existing->createdAt===$now&&$existing->expiresAt===$expires)return$existing;throw new ActivationSessionException('activation_session_conflict');}$this->references($applicationId,$verificationId,$generation);$db=$this->db();$ok=$db->insert($this->table(),['session_hash'=>$hash,'application_id'=>$applicationId,'verification_id'=>$verificationId,'generation'=>$generation,'purpose'=>StoreOnboardingActivationSession::PURPOSE,'state'=>StoreOnboardingActivationSession::ACTIVE,'expires_at'=>$expires,'consumed_at'=>null,'invalidated_at'=>null,'failed_attempts'=>0,'last_attempt_at'=>null,'created_at'=>$now,'updated_at'=>$now]);if($ok!==1)throw new ActivationSessionException('activation_session_write_uncertain');return$this->find('session_hash',$hash,true)??throw new ActivationSessionException('activation_session_write_uncertain');});
    }
    public function recordFailedAttempt(int $id,string $expectedUpdatedAt,string $now):StoreOnboardingActivationSession{return $this->mutate($id,$expectedUpdatedAt,$now,function($s)use($now){if($s->state!==StoreOnboardingActivationSession::ACTIVE||$s->isExpired($now)||$s->failedAttempts>=5)throw new ActivationSessionException('activation_session_attempt_forbidden');return['failed_attempts'=>$s->failedAttempts+1,'last_attempt_at'=>$now,'updated_at'=>$now];});}
    public function consume(int $id,string $expectedUpdatedAt,string $now,bool $activationConfirmed):StoreOnboardingActivationSession
    {if(!$activationConfirmed)throw new ActivationSessionException('activation_session_confirmation_required');return$this->mutate($id,$expectedUpdatedAt,$now,function($s)use($now){if($s->state===StoreOnboardingActivationSession::CONSUMED)return[];if($s->state!==StoreOnboardingActivationSession::ACTIVE||$s->isExpired($now))throw new ActivationSessionException('activation_session_consumption_forbidden');return['state'=>StoreOnboardingActivationSession::CONSUMED,'consumed_at'=>$now,'updated_at'=>$now];},function($s)use($now){$this->invalidateOthers($s,$now);});}
    public function invalidate(int $id,string $expectedUpdatedAt,string $now):StoreOnboardingActivationSession{return$this->mutate($id,$expectedUpdatedAt,$now,function($s)use($now){if($s->state===StoreOnboardingActivationSession::INVALIDATED)return[];if($s->state!==StoreOnboardingActivationSession::ACTIVE)throw new ActivationSessionException('activation_session_invalidation_forbidden');return['state'=>StoreOnboardingActivationSession::INVALIDATED,'invalidated_at'=>$now,'updated_at'=>$now];});}
    public function cleanup(string $now,int $limit=100):int{StoreOnboardingActivationSession::timestamp($now);if($limit<1||$limit>500)throw new ActivationSessionException('activation_session_cleanup_invalid');$cut=StoreOnboardingActivationSession::plus($now,-2592000);$db=$this->db();$ids=$db->get_col($db->prepare("SELECT id FROM {$this->table()} WHERE (state IN ('consumed','invalidated') AND updated_at<=%s) OR (state='active' AND expires_at<=%s) ORDER BY id LIMIT %d",$cut,$cut,$limit));if(!is_array($ids)||$db->last_error!=='')throw new ActivationSessionException('activation_session_cleanup_failed');$deleted=0;foreach($ids as $raw){$id=(int)$raw;$deleted+=$this->locked([$this->lockName('session-id',(string)$id)],function()use($id,$cut){$s=$this->find('id',$id,true);if($s===null)return 0;$eligible=in_array($s->state,[StoreOnboardingActivationSession::CONSUMED,StoreOnboardingActivationSession::INVALIDATED],true)?$s->updatedAt<=$cut:$s->state===StoreOnboardingActivationSession::ACTIVE&&$s->expiresAt<=$cut;if(!$eligible)return 0;$db=$this->db();$n=$db->delete($this->table(),['id'=>$s->id,'state'=>$s->state,'updated_at'=>$s->updatedAt]);if($n!==1)throw new ActivationSessionException('activation_session_cleanup_uncertain');return 1;});}return$deleted;}
    private function mutate(int $id,string $expected,string $now,callable $change,?callable $after=null):StoreOnboardingActivationSession{StoreOnboardingActivationSession::timestamp($expected);StoreOnboardingActivationSession::timestamp($now);if($now<$expected)throw new ActivationSessionException('activation_session_timestamp_invalid');$observed=$this->find('id',$id)??throw new ActivationSessionException('activation_session_not_found');$locks=[$this->lockName('session-id',(string)$id),$this->lockName('verification-generation',$observed->verificationId.':'.$observed->generation)];return$this->locked($locks,function()use($id,$expected,$now,$change,$after){$s=$this->find('id',$id,true)??throw new ActivationSessionException('activation_session_not_found');$data=$change($s);if($data!==[]){if($s->updatedAt!==$expected)throw new ActivationSessionException('activation_session_concurrent_modification');$n=$this->db()->update($this->table(),$data,['id'=>$id,'state'=>$s->state,'updated_at'=>$expected]);if($n!==1)throw new ActivationSessionException('activation_session_write_uncertain');$s=$this->find('id',$id,true)??throw new ActivationSessionException('activation_session_write_uncertain');}if($after!==null)$after($s);return$s;});}
    private function invalidateOthers(StoreOnboardingActivationSession $s,string $now):void{$db=$this->db();$db->last_error='';$n=$db->query($db->prepare("UPDATE {$this->table()} SET state='invalidated',invalidated_at=%s,updated_at=%s WHERE verification_id=%d AND generation=%d AND id<>%d AND state='active'",$now,$now,$s->verificationId,$s->generation,$s->id));if($n===false||$db->last_error!=='')throw new ActivationSessionException('activation_session_write_uncertain');$remaining=(int)$db->get_var($db->prepare("SELECT COUNT(*) FROM {$this->table()} WHERE verification_id=%d AND generation=%d AND id<>%d AND state='active'",$s->verificationId,$s->generation,$s->id));if($db->last_error!==''||$remaining!==0)throw new ActivationSessionException('activation_session_write_uncertain');}
    private function references(int $a,int $v,int $g):void{if($a<1||$v<1||$g<1)throw new ActivationSessionException('activation_session_invalid_id');$db=$this->db();$apps=$db->prefix.Config::TABLE_PREFIX.'store_onboarding_applications';$vers=$db->prefix.Config::TABLE_PREFIX.'store_onboarding_email_verifications';$row=$db->get_row($db->prepare("SELECT a.id,v.id verification_id,v.application_id,v.generation,v.purpose FROM {$apps} a JOIN {$vers} v ON v.application_id=a.id WHERE a.id=%d AND v.id=%d FOR UPDATE",$a,$v),ARRAY_A);if(!is_array($row)||$db->last_error!==''||(int)$row['generation']!==$g||(string)$row['purpose']!==StoreOnboardingActivationSession::PURPOSE)throw new ActivationSessionException('activation_session_reference_invalid');}
    private function find(string $column,string|int $value,bool $lock=false):?StoreOnboardingActivationSession{$db=$this->db();$db->last_error='';$p=is_int($value)?'%d':'%s';$r=$db->get_row($db->prepare("SELECT * FROM {$this->table()} WHERE {$column}={$p}".($lock?' FOR UPDATE':''),$value),ARRAY_A);if($db->last_error!=='')throw new ActivationSessionException('activation_session_read_failed');if(!is_array($r))return null;try{return StoreOnboardingActivationSession::fromRow($r);}catch(Throwable){throw new ActivationSessionException('activation_session_read_failed');}}
    private function locked(array $locks,callable $work):mixed{$db=$this->db();sort($locks,SORT_STRING);$held=[];try{foreach($locks as $l){if((int)$db->get_var($db->prepare('SELECT GET_LOCK(%s,10)',$l))!==1)throw new ActivationSessionException('activation_session_lock_failed');$held[]=$l;}if($db->query('START TRANSACTION')===false)throw new ActivationSessionException('activation_session_transaction_failed');try{$result=$work();if($db->query('COMMIT')===false){foreach(array_reverse($held)as$l)$db->get_var($db->prepare('SELECT RELEASE_LOCK(%s)',$l));$held=[];if($result instanceof StoreOnboardingActivationSession&&$this->reconcileExpected($result,$locks))return$result;throw new ActivationSessionException('activation_session_outcome_uncertain');}return$result;}catch(Throwable $e){$db->query('ROLLBACK');if($e instanceof ActivationSessionException)throw$e;throw new ActivationSessionException('activation_session_outcome_uncertain');}}finally{foreach(array_reverse($held)as$l)$db->get_var($db->prepare('SELECT RELEASE_LOCK(%s)',$l));}}
    private function reconcileExpected(StoreOnboardingActivationSession $expected,array $locks):bool{try{$fresh=$this->reconciliationDb();$table=$fresh->prefix.Config::TABLE_PREFIX.'store_onboarding_activation_sessions';$held=[];try{foreach($locks as$lock){if((int)$fresh->get_var($fresh->prepare('SELECT GET_LOCK(%s,10)',$lock))!==1)return false;$held[]=$lock;}$fresh->last_error='';$row=$fresh->get_row($fresh->prepare("SELECT * FROM {$table} WHERE id=%d",$expected->id),ARRAY_A);if($fresh->last_error!==''||!is_array($row))return false;$actual=StoreOnboardingActivationSession::fromRow($row);return$actual==$expected;}finally{foreach(array_reverse($held)as$lock)$fresh->get_var($fresh->prepare('SELECT RELEASE_LOCK(%s)',$lock));}}catch(Throwable){return false;}}
    private function reconciliationDb():\wpdb{$source=$this->db();$database=(string)$source->get_var('SELECT DATABASE()');$original=(int)$source->get_var('SELECT CONNECTION_ID()');if($database==='')throw new ActivationSessionException('activation_session_outcome_uncertain');$factory=$this->reconciliationFactory;$fresh=is_callable($factory)?$factory($database):new \wpdb(DB_USER,DB_PASSWORD,$database,DB_HOST);if(!$fresh instanceof \wpdb||$fresh->last_error!==''||(int)$fresh->get_var('SELECT CONNECTION_ID()')===$original||(int)$fresh->get_var('SELECT @@session.in_transaction')!==0)throw new ActivationSessionException('activation_session_outcome_uncertain');$fresh->set_prefix($source->prefix);return$fresh;}
    private function db():\wpdb{if($this->db instanceof \wpdb)return$this->db;global$wpdb;if(!$wpdb instanceof \wpdb)throw new ActivationSessionException('activation_session_unavailable');return$this->db=$wpdb;}
    private function table():string{$db=$this->db();return$db->prefix.Config::TABLE_PREFIX.'store_onboarding_activation_sessions';}
    private function hash(string $h):void{if(strlen($h)!==32)throw new ActivationSessionException('activation_session_invalid_hash');}
    private function lockName(string $domain,string $value):string{return'r1dca_s_'.substr(hash('sha256',$domain."\0".$value),0,48);}
}
