<?php
declare(strict_types=1);
namespace VeciAhorra\Database\Migrations;
use RuntimeException;
use VeciAhorra\Core\Config;
use VeciAhorra\Database\Tables\StoreOnboardingRateLimitBucketsTable;
final class CreateStoreOnboardingRateLimitFoundation
{
    private const COLUMNS=['id'=>['bigint unsigned','NO',null,'auto_increment'],'bucket_hash'=>['binary(32)','NO',null,''],'domain'=>['varchar(32)','NO',null,''],'window_started_at'=>['datetime','NO',null,''],'window_seconds'=>['int unsigned','NO',null,''],'hit_count'=>['int unsigned','NO','0',''],'expires_at'=>['datetime','NO',null,''],'created_at'=>['datetime','NO',null,''],'updated_at'=>['datetime','NO',null,'']];
    private const INDEXES=['PRIMARY'=>[['id'],true],'onboarding_rate_limit_bucket_unique'=>[['bucket_hash'],true],'onboarding_rate_limit_cleanup'=>[['expires_at'],false],'onboarding_rate_limit_domain_window'=>[['domain','window_started_at'],false]];
    public function up():void{global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$s=new StoreOnboardingRateLimitBucketsTable();$wpdb->last_error='';$result=dbDelta($s->sql($this->table(),$wpdb->get_charset_collate()));if(!is_array($result)||(string)$wpdb->last_error!=='')throw new RuntimeException('r1dca_rate_schema_install_failed');$this->assertStructure();}
    public function assertStructure():void{global $wpdb;$table=$this->table();$wpdb->last_error='';$meta=$wpdb->get_row($wpdb->prepare('SELECT ENGINE,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s',$table),ARRAY_A);if(!is_array($meta)||$wpdb->last_error!==''||strtoupper((string)$meta['ENGINE'])!=='INNODB')throw new RuntimeException('r1dca_rate_schema_invalid:table');$contract=(string)$wpdb->get_charset_collate();preg_match('/CHARACTER SET\s+([^\s]+)/i',$contract,$c);preg_match('/COLLATE\s+([^\s]+)/i',$contract,$x);$charset=$wpdb->get_var($wpdb->prepare('SELECT CHARACTER_SET_NAME FROM information_schema.COLLATIONS WHERE COLLATION_NAME=%s',(string)$meta['TABLE_COLLATION']));if(!isset($c[1],$x[1])||strtolower((string)$charset)!==strtolower($c[1])||strtolower((string)$meta['TABLE_COLLATION'])!==strtolower($x[1]))throw new RuntimeException('r1dca_rate_schema_invalid:charset');$rows=$wpdb->get_results("SHOW COLUMNS FROM {$table}",ARRAY_A);if(!is_array($rows)||$wpdb->last_error!=='')throw new RuntimeException('r1dca_rate_schema_inspection_failed');$actual=[];foreach($rows as $r)$actual[(string)$r['Field']]=$r;if(array_keys($actual)!==array_keys(self::COLUMNS))throw new RuntimeException('r1dca_rate_schema_invalid:columns');foreach(self::COLUMNS as $name=>[$type,$null,$default,$extra]){$r=$actual[$name];$a=strtolower((string)$r['Type']);$ok=str_ends_with($type,' unsigned')?preg_match('/^'.strtok($type,' ').'(?:\(\d+\))? unsigned$/D',$a)===1:$a===$type;if(!$ok||$r['Null']!==$null||($r['Default']??null)!==$default||strtolower((string)$r['Extra'])!==$extra)throw new RuntimeException('r1dca_rate_schema_invalid:column.'.$name);}$all=$wpdb->get_results("SHOW INDEX FROM {$table}",ARRAY_A);if(!is_array($all)||$wpdb->last_error!=='')throw new RuntimeException('r1dca_rate_schema_inspection_failed');$group=[];foreach($all as $r)$group[(string)$r['Key_name']][]=$r;if(array_diff_key($group,self::INDEXES)!==[]||array_diff_key(self::INDEXES,$group)!==[])throw new RuntimeException('r1dca_rate_schema_invalid:indexes');foreach(self::INDEXES as $name=>[$cols,$unique]){$rs=$group[$name];usort($rs,fn($a,$b)=>(int)$a['Seq_in_index']<=>(int)$b['Seq_in_index']);if(array_map(fn($r)=>(string)$r['Column_name'],$rs)!==$cols)throw new RuntimeException('r1dca_rate_schema_invalid:index.'.$name);foreach($rs as $r)if((int)$r['Non_unique']!==($unique?0:1)||($r['Sub_part']??null)!==null)throw new RuntimeException('r1dca_rate_schema_invalid:index.'.$name);}}
    private function table():string{global $wpdb;return $wpdb->prefix.Config::TABLE_PREFIX.'store_onboarding_rate_limit_buckets';}
}
