<?php
declare(strict_types=1);
namespace VeciAhorra\Modules\Sectorization;
use VeciAhorra\Core\Config;
final class ServiceZoneRepository {
 private function t(string $n):string{global $wpdb;return $wpdb->prefix.Config::TABLE_PREFIX.$n;}
 public function active():array{global $wpdb;return $wpdb->get_results("SELECT id,commune,name,status FROM {$this->t('service_zones')} WHERE status='active' ORDER BY commune,name",ARRAY_A);}
 public function findActive(int $id):?array{global $wpdb;$r=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->t('service_zones')} WHERE id=%d AND status='active'",$id),ARRAY_A);return is_array($r)?$r:null;}
 public function storeAllowed(int $zoneId,int $storeId):bool{global $wpdb;return (int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$this->t('store_service_zones')} sz JOIN {$this->t('service_zones')} z ON z.id=sz.zone_id AND z.status='active' JOIN {$this->t('stores')} s ON s.id=sz.store_id AND s.status='active' WHERE sz.zone_id=%d AND sz.store_id=%d",$zoneId,$storeId))===1;}
 public function allowedStoreIds(int $zoneId):array{global $wpdb;return array_map('intval',$wpdb->get_col($wpdb->prepare("SELECT sz.store_id FROM {$this->t('store_service_zones')} sz JOIN {$this->t('service_zones')} z ON z.id=sz.zone_id AND z.status='active' JOIN {$this->t('stores')} s ON s.id=sz.store_id AND s.status='active' WHERE sz.zone_id=%d",$zoneId)));}
 public function all():array{global $wpdb;return $wpdb->get_results("SELECT z.*,GROUP_CONCAT(sz.store_id ORDER BY sz.store_id) store_ids FROM {$this->t('service_zones')} z LEFT JOIN {$this->t('store_service_zones')} sz ON sz.zone_id=z.id GROUP BY z.id ORDER BY z.commune,z.name",ARRAY_A);}
 public function save(array $d,int $admin):int{global $wpdb;$id=absint($d['id']??0);$row=['commune'=>sanitize_text_field((string)$d['commune']),'name'=>sanitize_text_field((string)$d['name']),'status'=>in_array($d['status']??'', ['active','inactive'],true)?$d['status']:'inactive','updated_at'=>current_time('mysql',true)];if($id){$wpdb->update($this->t('service_zones'),$row,['id'=>$id]);}else{$row['created_at']=$row['updated_at'];$wpdb->insert($this->t('service_zones'),$row);$id=(int)$wpdb->insert_id;}if($id<=0)throw new \RuntimeException('No fue posible guardar el sector.');$storeIds=array_values(array_unique(array_filter(array_map('absint',(array)($d['stores']??[])))));$wpdb->query('START TRANSACTION');try{$wpdb->delete($this->t('store_service_zones'),['zone_id'=>$id]);foreach($storeIds as $storeId){if((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$this->t('stores')} WHERE id=%d",$storeId))!==1)throw new \InvalidArgumentException('Minimarket inexistente.');$wpdb->insert($this->t('store_service_zones'),['store_id'=>$storeId,'zone_id'=>$id,'assigned_by'=>$admin,'assigned_at'=>current_time('mysql',true)]);} $wpdb->query('COMMIT');}catch(\Throwable $e){$wpdb->query('ROLLBACK');throw $e;}return $id;}
}
