<?php defined('ABSPATH')||exit;$labels=['draft'=>'Borrador','active'=>'Activo','inactive'=>'Inactivo'];$changes=['create'=>'Crear','update'=>'Actualizar','unchanged'=>'Sin cambios'];?>
<div class="wrap va-product-import"><h1>Carga masiva del catálogo maestro</h1><p class="description">Crea o actualiza productos por SKU. La vista previa no escribe productos ni inventarios; el archivo completo se aplica sólo al confirmar.</p>
<?php if($message!==''):?><div class="notice notice-error"><p><?=esc_html($message)?></p></div><?php endif;?>
<?php if(is_array($result)):?><div class="notice notice-success"><p><strong>Importación completada.</strong> Creados: <?=esc_html((string)$result['created'])?> · Actualizados: <?=esc_html((string)$result['updated'])?> · Sin cambios: <?=esc_html((string)$result['unchanged'])?>.</p></div><?php endif;?>
<section class="va-import-card"><h2>1. Descarga la plantilla</h2><p>CSV UTF-8, coma, máximo 1 MB y 1000 filas. Estados: Borrador, Activo o Inactivo mediante los valores internos <code>draft|active|inactive</code>.</p><form action="<?=esc_url(admin_url('admin-post.php'))?>" method="post"><input type="hidden" name="action" value="veciahorra_product_csv_template"><?php wp_nonce_field('veciahorra_product_csv_template');?><button class="button">Descargar plantilla y ejemplo</button></form></section>
<section class="va-import-card"><h2>2. Selecciona archivos y valida</h2><form action="<?=esc_url(admin_url('admin-post.php'))?>" method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="veciahorra_product_csv_preview"><?php wp_nonce_field('veciahorra_product_csv_preview');?><label><strong>Archivo CSV</strong><input name="product_csv" type="file" accept=".csv,text/csv" required></label><label><strong>ZIP de imágenes (opcional)</strong><input name="product_images" type="file" accept=".zip,application/zip"></label><button class="button button-primary">Validar y ver vista previa</button></form><p>No se aceptan URLs ni SVG. El ZIP admite hasta 1000 JPG, PNG o WEBP, 5 MB por imagen, 20 MB comprimidos y 25 MB expandidos. Cada archivo debe llamarse exactamente como su SKU.</p></section>
<?php if(is_array($preview)):?><section class="va-import-card"><h2>3. Vista previa</h2><p><strong><?=count($preview['rows'])?></strong> válidas: <?=$preview['created']?> por crear, <?=$preview['updated']?> por actualizar y <?=$preview['unchanged']?> sin cambios. <strong><?=count($preview['errors'])?></strong> rechazadas.</p>
<?php if($preview['rows']!==[]):?><div class="va-import-table"><table class="widefat striped"><thead><tr><th>Fila</th><th>SKU</th><th>Nombre</th><th>Categoría</th><th>Estado</th><th>Imagen</th><th>Cambio</th></tr></thead><tbody><?php foreach($preview['rows']as$r):?><tr><td><?=$r['line']?></td><td><?=esc_html($r['sku'])?></td><td><?=esc_html($r['name'])?></td><td><?=esc_html($r['category'].($r['subcategory']!==''?' › '.$r['subcategory']:''))?></td><td><?=esc_html($labels[$r['status']]??$r['status'])?></td><td><?=esc_html($r['image']===''?'Sin imagen':($r['replaces_image']?'Reemplazar':'Agregar'))?></td><td><?=esc_html($changes[$r['change']]??$r['change'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php if($preview['errors']!==[]):?><div class="notice notice-error inline"><p><strong>El archivo contiene errores. Corrige todas las filas rechazadas y vuelve a cargarlo. No se aplicó ningún cambio.</strong></p></div><table class="widefat striped"><thead><tr><th>Fila</th><th>SKU</th><th>Error</th></tr></thead><tbody><?php foreach($preview['errors']as$e):?><tr><td><?=$e['line']?></td><td><?=esc_html($e['sku'])?></td><td><?=esc_html($e['message'])?></td></tr><?php endforeach;?></tbody></table><p><a class="button" href="<?=esc_url(wp_nonce_url(admin_url('admin-post.php?action=veciahorra_product_csv_errors&va_token='.$token),'veciahorra_product_csv_errors_'.$token))?>">Descargar informe de errores</a></p><?php endif;?>
<?php if($preview['rows']!==[]&&$preview['errors']===[]&&empty($preview['completed'])):?><form action="<?=esc_url(admin_url('admin-post.php'))?>" method="post" class="va-import-confirm"><input type="hidden" name="action" value="veciahorra_product_csv_confirm"><input type="hidden" name="va_token" value="<?=esc_attr($token)?>"><?php wp_nonce_field('veciahorra_product_csv_confirm');?><p>Se volverán a validar los snapshots y se aplicará todo en una transacción. Los attachments nuevos se compensan si ocurre un rollback.</p><button class="button button-primary">Confirmar importación</button></form><?php endif;?></section><?php endif;?></div>
